//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (connection.h)
//     by BogDB. Minimal programmatic facade to support direct write paths.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Antlr4.Runtime;
using BogDb.Core.Storage.BufferManager;
using BogDb.Core.Common;
using BogDb.Core.Common.Diagnostics;
using BogDb.Core.Common.FileSystem;
using BogDb.Core.Catalog;
using BogDb.Core.Parser;
using BogDb.Core.Parser.Antlr4;
using BogDb.Core.Binder;
using BogDb.Core.Planner;
using BogDb.Core.Optimizer;
using BogDb.Core.Processor;
using BogDb.Core.GraphDataScience;
using BogDb.Core.Extraction;
using BogDb.Core.Extension;
using BogDb.Core.Main.QueryResult;

namespace BogDb.Core.Main;

/// <summary>
/// Connection holds the active session and Transaction state interacting with 
/// the Database catalog and storage buffers. Bypasses Cypher Planner for embedded writes.
/// </summary>
public sealed class BogConnection : IDisposable
{
    private readonly BogDatabase _database;
    private Transaction.Transaction _activeTransaction;
    private int _interruptRequested;
    public ClientContext ClientContext { get; }
    
    internal BogDatabase Database => _database;

    /// <summary>
    /// The alias of the currently-selected attached database, set by USE.
    /// Null when no specific attached database is selected.
    /// </summary>
    public string? DefaultDatabaseAlias { get; set; }

    public BogConnection(BogDatabase database)
    {
        _database = database;
        ClientContext = new ClientContext(this);
    }

    public void BeginWriteTransaction()
    {
        if (_activeTransaction != null || ClientContext.ActiveTransaction != null)
            throw new InvalidOperationException("Transaction already active.");

        EnsureDatabaseWritable();
        StartTransaction(BogDb.Core.Transaction.TransactionType.WRITE);
        _activeTransaction = ClientContext.ActiveTransaction;
    }

    public void Commit()
    {
        var transaction = _activeTransaction ?? ClientContext.ActiveTransaction;
        if (transaction == null)
            throw new InvalidOperationException("No active transaction.");

        ClientContext.Commit();
        _database.PersistState();
        
        // In a full implementation, we flush WAL and update Catalog isolation version
        _database.Catalog.IncrementVersion();
        _database.MetricsRegistry.RecordCommit();

        _activeTransaction = null;
    }

    public void Rollback()
    {
        var transaction = _activeTransaction ?? ClientContext.ActiveTransaction;
        if (transaction == null)
            throw new InvalidOperationException("No active transaction.");

        ClientContext.Rollback();
        if (transaction.IsWriteTransaction())
            _database.DiscardPendingRecoveryArtifacts(transaction);

        _database.MetricsRegistry.RecordRollback();
        _activeTransaction = null;
    }

    /// <summary>
    /// Executes a block of direct-write operations inside a single write transaction.
    /// If the caller already has an active write transaction, the work is folded into it.
    /// Otherwise, this method owns the transaction lifetime and performs a single persist.
    /// </summary>
    public void ExecuteWriteTransaction(Action action)
    {
        ArgumentNullException.ThrowIfNull(action);

        var startedLocalTransaction = false;
        try
        {
            if (ClientContext.ActiveTransaction == null)
            {
                EnsureDatabaseWritable();
                StartTransaction(BogDb.Core.Transaction.TransactionType.WRITE);
                _activeTransaction = ClientContext.ActiveTransaction;
                startedLocalTransaction = true;
            }

            action();

            if (startedLocalTransaction)
            {
                ClientContext.Commit();
                _database.PersistState();
                _database.Catalog.IncrementVersion();
                _database.MetricsRegistry.RecordCommit();
                _activeTransaction = null;
            }
        }
        catch
        {
            if (startedLocalTransaction && ClientContext.ActiveTransaction != null)
            {
                var rollbackTx = ClientContext.ActiveTransaction;
                ClientContext.Rollback();
                if (rollbackTx != null && rollbackTx.IsWriteTransaction())
                    _database.DiscardPendingRecoveryArtifacts(rollbackTx);
                _database.MetricsRegistry.RecordRollback();
                _activeTransaction = null;
            }

            throw;
        }
    }

    /// <summary>
    /// Commits the active transaction for schema-only changes.
    /// Even without graph data mutations, the schema surface must be durable
    /// across crash/reopen boundaries, so we persist the catalog + empty table snapshot.
    /// </summary>
    public void CommitSchemaOnly()
    {
        var transaction = _activeTransaction ?? ClientContext.ActiveTransaction;
        if (transaction == null)
            throw new InvalidOperationException("No active transaction.");

        ClientContext.Commit();
        _database.PersistState();
        _database.Catalog.IncrementVersion();
        _database.MetricsRegistry.RecordCommit();

        _activeTransaction = null;
    }

    /// <summary>
    /// Phase 7: The Master Query endpoint compiling string statements into
    /// Vectorized physical tuples over native value vectors.
    /// </summary>
    public QueryResult.QueryResult Query(string query)
        => Query(query, null, null);

    public QueryResult.QueryResult Query(string query, BogDbQueryMetricsOptions? metricsOptions)
        => Query(query, null, metricsOptions);

    /// <summary>
    /// Creates a fluent Cypher query builder.
    /// Chain parameters and choose a materialization strategy.
    /// <example>
    /// <code>
    /// // Parameterized query with LINQ projection
    /// var names = conn.Cypher("MATCH (p:Person) WHERE p.age > $minAge RETURN p.name")
    ///     .Param("minAge", 30)
    ///     .Select(row => row.GetString("p.name"));
    ///
    /// // Scalar aggregate
    /// var count = conn.Cypher("MATCH (p:Person) RETURN COUNT(*) AS cnt")
    ///     .Scalar&lt;long&gt;();
    ///
    /// // ForEach with side effects
    /// conn.Cypher("MATCH (p:Person) RETURN p.id, p.salary")
    ///     .ForEach(row => Console.WriteLine($"{row.GetString("p.id")}: {row.GetDouble("p.salary")}"));
    /// </code>
    /// </example>
    /// </summary>
    public CypherFluentQuery Cypher(string cypherQuery)
        => new CypherFluentQuery(this, cypherQuery);

    /// <summary>
    /// Creates a fluent graph mutation builder.
    /// Queue schema, node, and edge operations, then commit them all at once.
    /// <example>
    /// <code>
    /// conn.Graph()
    ///     .EnsureNodeTable("Person", new() { ["id"] = STRING, ["name"] = STRING })
    ///     .AddNode("Person", "p1", new { name = "Alice" })
    ///     .AddNode("Person", "p2", new { name = "Bob" })
    ///     .AddEdge("KNOWS", "p1", "p2", new { since = 2020 })
    ///     .Commit();
    /// </code>
    /// </example>
    /// </summary>
    public GraphMutationBuilder Graph()
        => new GraphMutationBuilder(this);

    public BogDbPreparedStatement Prepare(string query)
    {
        try
        {
            var preparedMetadata = DescribePreparedStatement(query);
            return new BogDbPreparedStatement(
                this,
                query,
                isSuccess: true,
                errorMessage: string.Empty,
                parameterNames: ExtractParameterNames(query),
                resultColumns: preparedMetadata.ResultColumns,
                parameterExpectedTypes: preparedMetadata.ParameterExpectedTypes);
        }
        catch (Exception ex)
        {
            return new BogDbPreparedStatement(
                this,
                query,
                isSuccess: false,
                errorMessage: ex.Message,
                parameterNames: ExtractParameterNames(query));
        }
    }

    public TimeSpan QueryTimeout
    {
        get => ClientContext.TimeoutInMs == 0
            ? Timeout.InfiniteTimeSpan
            : TimeSpan.FromMilliseconds(ClientContext.TimeoutInMs);
        set
        {
            if (value < Timeout.InfiniteTimeSpan)
                throw new ArgumentOutOfRangeException(nameof(value));

            ClientContext.TimeoutInMs = value == Timeout.InfiniteTimeSpan
                ? 0
                : checked((ulong)Math.Ceiling(value.TotalMilliseconds));
        }
    }

    public void SetQueryTimeout(TimeSpan timeout) => QueryTimeout = timeout;

    public void SetQueryTimeout(long milliseconds)
    {
        if (milliseconds < Timeout.Infinite)
            throw new ArgumentOutOfRangeException(nameof(milliseconds));

        QueryTimeout = milliseconds == Timeout.Infinite
            ? Timeout.InfiniteTimeSpan
            : TimeSpan.FromMilliseconds(milliseconds);
    }

    public void Interrupt() => Interlocked.Exchange(ref _interruptRequested, 1);

    public QueryResult.QueryResult Execute(BogDbPreparedStatement preparedStatement)
    {
        ArgumentNullException.ThrowIfNull(preparedStatement);
        return Query(preparedStatement.Query, preparedStatement.Bindings, null);
    }

    public Task<QueryResult.QueryResult> ExecuteAsync(BogDbPreparedStatement preparedStatement)
    {
        ArgumentNullException.ThrowIfNull(preparedStatement);
        return QueryAsync(preparedStatement.Query, preparedStatement.Bindings);
    }

    public QueryResult.QueryResult Query(string query, IReadOnlyDictionary<string, object?>? parameters)
        => Query(query, parameters, null);

    public QueryResult.QueryResult Query(
        string query,
        IReadOnlyDictionary<string, object?>? parameters,
        BogDbQueryMetricsOptions? metricsOptions)
    {
        var startedAt = Stopwatch.StartNew();
        var queryMetrics = new QueryMetricsContext(metricsOptions);
        queryMetrics.Start();
        ClientContext.CurrentQueryMetrics = queryMetrics;

        // ── Context for table functions and GDS scalar functions ─────────────────
        // P1-053: wire DB catalog into scalar table-function stubs.
        Function.Table.TableFunctions.SetCatalogContext(_database);
        // Wire DB into GDS scalar functions (node_degree, has_path, graph_density, k_hop_count).
        Function.Gds.GdsFunctions.SetDatabaseContext(_database);

        var trimmed = query.Trim();

        // ── COMMIT / ROLLBACK without BEGIN ─────────────────────────────────────
        if (_activeTransaction == null && ClientContext.ActiveTransaction == null)
        {
            var upper = trimmed.ToUpperInvariant();
            if (upper == "COMMIT")
                return FinalizeQueryResult(
                    QueryResult.QueryResult.FromError("Cannot COMMIT: no active transaction."),
                    queryMetrics,
                    success: false);
            if (upper == "ROLLBACK")
                return FinalizeQueryResult(
                    QueryResult.QueryResult.FromError("Cannot ROLLBACK: no active transaction."),
                    queryMetrics,
                    success: false);
        }

        // ── Window function intercept ────────────────────────────────────────────
        if (Processor.Operator.Window.WindowFunctionService.IsWindowQuery(trimmed))
            return FinalizeQueryResult(
                Processor.Operator.Window.WindowFunctionService.Execute(this, trimmed),
                queryMetrics,
                success: true);

        // ── GDS CALL intercept ───────────────────────────────────────────────────
        var gdsResult = TryExecuteGdsCall(trimmed);
        if (gdsResult != null)
            return FinalizeQueryResult(gdsResult, queryMetrics, success: gdsResult.IsSuccess);

        var startedLocalTransaction = false;
        try
        {
            ThrowIfInterruptedOrTimedOut(startedAt);

            query = NormalizePlannerLoadFromLiteralPath(query);

            // 0.5. Pre-process CALL { subquery } blocks before ANTLR parsing
            var callSubqueryPreprocessor = new Parser.Antlr4.CallSubqueryPreprocessor();
            query = callSubqueryPreprocessor.Preprocess(query);

            // 1. Parse
            var inputStream = new Antlr4.Runtime.AntlrInputStream(query);
            var lexer = new CypherLexer(inputStream);
            var syntaxErrors = new List<string>();
            lexer.RemoveErrorListeners();
            lexer.AddErrorListener(new QueryLexerSyntaxErrorListener(syntaxErrors));
            var tokenStream = new Antlr4.Runtime.CommonTokenStream(lexer);
            var parser = new CypherParser(tokenStream);
            parser.RemoveErrorListeners();
            parser.AddErrorListener(new QuerySyntaxErrorListener(syntaxErrors));
            var root = parser.ku_Statements();
            ThrowIfInterruptedOrTimedOut(startedAt);
            if (syntaxErrors.Count > 0)
            {
                return QueryResult.QueryResult.FromError(string.Join(Environment.NewLine, syntaxErrors));
            }
            var transformer = new Parser.Antlr4.Transformer(root, callSubqueryPreprocessor.ExtractedBodies);
            var statements = transformer.Transform();
            ThrowIfInterruptedOrTimedOut(startedAt);

            if (statements.Count == 0)
                return QueryResult.QueryResult.FromError("No statement was parsed from the provided query.");

            // For Phase 7 testing, we assume single-statement queries.
            var statement = statements[0];

            // Transaction control statements are handled directly at connection level.
            if (statement.GetStatementType() == StatementType.TRANSACTION)
            {
                return ExecuteTransactionStatement((TransactionStatement)statement);
            }

            if (ClientContext.ActiveTransaction == null)
            {
                StartTransaction(
                    RequiresWriteTransaction(statement)
                        ? BogDb.Core.Transaction.TransactionType.WRITE
                        : BogDb.Core.Transaction.TransactionType.READ_ONLY);
                startedLocalTransaction = true;
            }

            // 2. Bind
            var binder = new BogDb.Core.Binder.Binder(
                _database.Catalog,
                ReadCopyCsvHeader,
                name => _database.TryGetExtensionOption(name, out var option) ? option : null);
            var boundStatement = binder.Bind(statement);
            ThrowIfInterruptedOrTimedOut(startedAt);

            if (TryExecuteDdlStatement(statement, boundStatement, out var ddlResult))
            {
                if (startedLocalTransaction)
                {
                    ClientContext.Commit();
                    _database.PersistState();
                    startedLocalTransaction = false;
                }

                return ddlResult;
            }

            // 3. Plan
            var planner = new BogDb.Core.Planner.Planner(_database);
            var logicalPlan = planner.GetBestPlan(boundStatement);
            ThrowIfInterruptedOrTimedOut(startedAt);

            // 4. Optimize
            var optimizer = new Optimizer.Optimizer(_database);
            optimizer.Optimize(logicalPlan);
            ThrowIfInterruptedOrTimedOut(startedAt);

            // 5. Execute 
            var planMapper = new PlanMapper(_database);
            var physicalPlan = planMapper.MapLogicalPlanToPhysical(logicalPlan);
            ThrowIfInterruptedOrTimedOut(startedAt);

            if (boundStatement is BoundExplain explain)
            {
                var explainText = explain.ExplainType == ExplainType.LOGICAL_PLAN
                    ? PlanPrinter.Print(logicalPlan)
                    : PhysicalPlanPrinter.Print(physicalPlan);
                var explainResult = QueryResult.QueryResult.FromOrderedRows(
                    new[]
                    {
                        new Dictionary<string, object?>
                        {
                            ["explain result"] = explainText
                        }
                    },
                    new[] { "explain result" });

                if (startedLocalTransaction)
                {
                    ClientContext.Commit();
                    _database.PersistState();
                    startedLocalTransaction = false;
                }

                return FinalizeQueryResult(explainResult, queryMetrics, success: true);
            }
        
            var execContext = new BogDb.Core.Processor.ExecutionContext(ClientContext.ActiveTransaction, _database.BufferManager, _database)
            {
                ParameterBindings = NormalizeParameterBindings(parameters),
                QueryMetrics = queryMetrics
            };
        
            // 6. Aggregate
            // Extract RETURN-clause column names so QueryResult can expose them via GetAsDictionary().
            var columnNames = System.Array.Empty<string>();
            var columnTypes = System.Array.Empty<LogicalTypeID>();
            if (boundStatement is BogDb.Core.Binder.BoundRegularQuery rq
                && rq.GetSingleQuery(0).HasReturnClause())
            {
                var items = rq.GetSingleQuery(0).ReturnClause!.Items;
                columnNames = items.Select(it => it.ColumnName).ToArray();
                columnTypes = items.Select(it => it.Expression.DataType).ToArray();
            }

            var resultCollector = new BogDb.Core.Processor.Operator.Result.ResultCollector(physicalPlan.LastOperator, 999, columnNames);
            resultCollector.GetNextTuple(execContext);
            ThrowIfInterruptedOrTimedOut(startedAt);

            if (startedLocalTransaction)
            {
                ClientContext.Commit();
                _database.PersistState();
                startedLocalTransaction = false;
            }

            return FinalizeQueryResult(new QueryResult.QueryResult(resultCollector, columnTypes), queryMetrics, success: true);
        }
        catch (Exception ex)
        {
            if (startedLocalTransaction)
            {
                var rollbackTx = ClientContext.ActiveTransaction;
                try
                {
                    ClientContext.Rollback();
                    if (rollbackTx != null && rollbackTx.IsWriteTransaction())
                        _database.DiscardPendingRecoveryArtifacts(rollbackTx);
                }
                catch
                {
                    // Preserve the original query error in returned QueryResult.
                }
            }
            return FinalizeQueryResult(QueryResult.QueryResult.FromError(ex.Message), queryMetrics, success: false);
        }
        finally
        {
            ClientContext.CurrentQueryMetrics = null;
        }
    }

    public GraphShard ExtractGraphNeighborhood(
        string seedTable,
        object seedNodeId,
        GraphShardExtractionOptions? options = null)
    {
        var stopwatch = Stopwatch.StartNew();
        var result = new GraphShardExtractor(_database).ExtractNeighborhood(seedTable, seedNodeId, options, GetCurrentTransactionOrNull());
        _database.MetricsRegistry.RecordExtraction(stopwatch.Elapsed.TotalMilliseconds);
        return result;
    }

    public GraphShard ExtractGraphNeighborhood(
        IEnumerable<GraphNodeSelector> seeds,
        GraphShardExtractionOptions? options = null)
    {
        var stopwatch = Stopwatch.StartNew();
        var result = new GraphShardExtractor(_database).ExtractNeighborhood(seeds, options, GetCurrentTransactionOrNull());
        _database.MetricsRegistry.RecordExtraction(stopwatch.Elapsed.TotalMilliseconds);
        return result;
    }

    public GraphShard ExtractGraphNodeSet(
        IEnumerable<GraphNodeSelector> nodes,
        GraphShardExtractionOptions? options = null)
    {
        var stopwatch = Stopwatch.StartNew();
        var result = new GraphShardExtractor(_database).ExtractNodeSet(nodes, options, GetCurrentTransactionOrNull());
        _database.MetricsRegistry.RecordExtraction(stopwatch.Elapsed.TotalMilliseconds);
        return result;
    }

    public string ExportGraphNeighborhoodAsJson(
        string seedTable,
        object seedNodeId,
        GraphShardExtractionOptions? options = null,
        bool writeIndented = false)
        => GraphShardJson.Serialize(
            ExtractGraphNeighborhood(seedTable, seedNodeId, options),
            writeIndented);

    public string ExportGraphNeighborhoodAsJson(
        IEnumerable<GraphNodeSelector> seeds,
        GraphShardExtractionOptions? options = null,
        bool writeIndented = false)
        => GraphShardJson.Serialize(
            ExtractGraphNeighborhood(seeds, options),
            writeIndented);

    public string ExportGraphNodeSetAsJson(
        IEnumerable<GraphNodeSelector> nodes,
        GraphShardExtractionOptions? options = null,
        bool writeIndented = false)
        => GraphShardJson.Serialize(
            ExtractGraphNodeSet(nodes, options),
            writeIndented);

    private QueryResult.QueryResult ExecuteTransactionStatement(TransactionStatement statement)
    {
        try
        {
            switch (statement.Command)
            {
                case TransactionCommand.BEGIN:
                    if (ClientContext.ActiveTransaction != null)
                        throw new InvalidOperationException("Transaction already active.");
                    StartTransaction(statement.IsReadOnly
                        ? BogDb.Core.Transaction.TransactionType.READ_ONLY
                        : BogDb.Core.Transaction.TransactionType.WRITE);
                    break;
                case TransactionCommand.COMMIT:
                    ClientContext.Commit();
                    _database.PersistState();
                    _database.MetricsRegistry.RecordCommit();
                    break;
                case TransactionCommand.ROLLBACK:
                    var rollbackTx = ClientContext.ActiveTransaction;
                    ClientContext.Rollback();
                    if (rollbackTx != null && rollbackTx.IsWriteTransaction())
                        _database.DiscardPendingRecoveryArtifacts(rollbackTx);
                    _database.MetricsRegistry.RecordRollback();
                    break;
                case TransactionCommand.CHECKPOINT:
                    _database.PersistState();
                    break;
                default:
                    throw new NotSupportedException($"Unsupported transaction command: {statement.Command}");
            }

            var noOp = new BogDb.Core.Processor.Operator.NoOpPhysicalOperator(0);
            var collector = new BogDb.Core.Processor.Operator.Result.ResultCollector(noOp, 999);
            var execContext = new BogDb.Core.Processor.ExecutionContext(
                BogDb.Core.Transaction.Transaction.DUMMY_TRANSACTION, _database.BufferManager);
            collector.GetNextTuple(execContext);
            return new QueryResult.QueryResult(collector);
        }
        catch (Exception ex)
        {
            return QueryResult.QueryResult.FromError(ex.Message);
        }
    }

    /// <summary>
    /// Asynchronous Task-based equivalent for non-blocking UI pipelines.
    /// </summary>
    public Task<QueryResult.QueryResult> QueryAsync(string query)
    {
        return Task.Run(() => Query(query));
    }

    public Task<QueryResult.QueryResult> QueryAsync(string query, BogDbQueryMetricsOptions? metricsOptions)
    {
        return Task.Run(() => Query(query, metricsOptions));
    }

    public Task<QueryResult.QueryResult> QueryAsync(string query, IReadOnlyDictionary<string, object?>? parameters)
    {
        return Task.Run(() => Query(query, parameters));
    }

    public Task<QueryResult.QueryResult> QueryAsync(
        string query,
        IReadOnlyDictionary<string, object?>? parameters,
        BogDbQueryMetricsOptions? metricsOptions)
    {
        return Task.Run(() => Query(query, parameters, metricsOptions));
    }

    private static bool RequiresWriteTransaction(Statement statement)
    {
        switch (statement.GetStatementType())
        {
            case StatementType.CREATE_TABLE:
            case StatementType.DROP:
            case StatementType.ALTER:
            case StatementType.CREATE_MACRO:
            case StatementType.ATTACH_DATABASE:
            case StatementType.DETACH_DATABASE:
            case StatementType.USE_DATABASE:
            case StatementType.EXTENSION:
                return true;
        }

        if (statement is not RegularQuery regularQuery)
            return false;

        for (var i = 0; i < regularQuery.GetNumSingleQueries(); i++)
        {
            if (regularQuery.GetSingleQuery(i).GetNumUpdatingClauses() > 0)
                return true;
        }

        return false;
    }

    private bool TryExecuteDdlStatement(Statement statement, BoundStatement boundStatement, out QueryResult.QueryResult result)
    {
        switch (statement)
        {
            case CreateNodeTable createNode when boundStatement is BoundCreateNodeTable boundCreateNode:
            {
                EnsureNodeTableWithDefinitions(createNode.TableName, ToPropertyDefinitions(boundCreateNode.Info.Properties));
                result = CreateNoOpSuccessResult();
                return true;
            }
            case CreateRelTable createRel when boundStatement is BoundCreateRelTable boundCreateRel:
            {
                EnsureRelTableWithDefinitions(
                    createRel.TableName,
                    createRel.SrcTableName,
                    createRel.DstTableName,
                    ToPropertyDefinitions(boundCreateRel.Info.Properties));
                result = CreateNoOpSuccessResult();
                return true;
            }
            case DropTable dropTable when boundStatement is BoundDropTable:
            {
                _database.DropTable(GetRequiredWriteTransaction(), dropTable.TableName);
                result = CreateNoOpSuccessResult();
                return true;
            }
            case AlterTableAddProperty alterAddProperty:
            {
                var defaultValue = GetLiteralDefaultValue(alterAddProperty.DefaultExpression, out var defaultExpressionName);

                _database.AlterTableAddProperty(
                    GetRequiredWriteTransaction(),
                    alterAddProperty.TableName,
                    alterAddProperty.PropertyName,
                    ParseLogicalType(alterAddProperty.TypeName),
                    alterAddProperty.TypeName,
                    defaultValue,
                    defaultExpressionName);
                result = CreateNoOpSuccessResult();
                return true;
            }
            case AlterTableDropProperty alterDropProperty:
            {
                _database.AlterTableDropProperty(
                    GetRequiredWriteTransaction(),
                    alterDropProperty.TableName,
                    alterDropProperty.PropertyName);
                result = CreateNoOpSuccessResult();
                return true;
            }
            case AlterTableRenameTable alterRenameTable:
            {
                _database.AlterTableRename(
                    GetRequiredWriteTransaction(),
                    alterRenameTable.TableName,
                    alterRenameTable.NewTableName);
                result = CreateNoOpSuccessResult();
                return true;
            }
            case AlterTableRenameProperty alterRenameProperty:
            {
                _database.AlterTableRenameProperty(
                    GetRequiredWriteTransaction(),
                    alterRenameProperty.TableName,
                    alterRenameProperty.OldPropertyName,
                    alterRenameProperty.NewPropertyName);
                result = CreateNoOpSuccessResult();
                return true;
            }
            case AlterTableConnectionChange alterConnectionChange:
            {
                _database.AlterTableConnectionChange(
                    GetRequiredWriteTransaction(),
                    alterConnectionChange.TableName,
                    alterConnectionChange.IsAdd,
                    alterConnectionChange.IgnoreIfPresentOrMissing,
                    alterConnectionChange.FromTableName,
                    alterConnectionChange.ToTableName);
                result = CreateNoOpSuccessResult();
                return true;
            }
            case AttachDatabaseStatement when boundStatement is BoundAttachDatabase boundAttach:
            {
                var dbType = boundAttach.DbType.ToUpperInvariant();
                if (!_database.TryResolveStorageExtension(dbType, out var storageExtension))
                {
                    var errMsg = $"No loaded extension can handle database type: {dbType}.";
                    if (string.Equals(dbType, "DUCKDB", StringComparison.OrdinalIgnoreCase))
                        errMsg += "\nDid you forget to load duckdb extension?\nYou can load it by: LOAD EXTENSION duckdb;";
                    else if (string.Equals(dbType, "POSTGRES", StringComparison.OrdinalIgnoreCase))
                        errMsg += "\nDid you forget to load postgres extension?\nYou can load it by: LOAD EXTENSION postgres;";
                    throw new InvalidOperationException(errMsg);
                }
                var attachedDb = storageExtension.Attach(_database, boundAttach.Alias, boundAttach.Path, boundAttach.Options);
                _database.AddAttachedDatabase(attachedDb);
                result = CreateMessageResult("Attached database successfully.");
                return true;
            }
            case DetachDatabaseStatement when boundStatement is BoundDetachDatabase boundDetach:
            {
                if (!_database.RemoveAttachedDatabase(boundDetach.DbName))
                    throw new InvalidOperationException($"Database '{boundDetach.DbName}' is not attached.");
                // Clear default database reference if detaching the current default
                if (string.Equals(DefaultDatabaseAlias, boundDetach.DbName, StringComparison.OrdinalIgnoreCase))
                    DefaultDatabaseAlias = null;
                result = CreateMessageResult("Detached database successfully.");
                return true;
            }
            case UseDatabaseStatement when boundStatement is BoundUseDatabase boundUse:
            {
                if (!_database.TryGetAttachedDatabase(boundUse.DbName, out _))
                    throw new InvalidOperationException($"Database '{boundUse.DbName}' is not attached.");
                DefaultDatabaseAlias = boundUse.DbName;
                result = CreateMessageResult("Used database successfully.");
                return true;
            }
            default:
                result = null!;
                return false;
        }
    }

    private static IReadOnlyDictionary<string, object?>? NormalizeParameterBindings(
        IReadOnlyDictionary<string, object?>? parameters)
    {
        if (parameters == null || parameters.Count == 0)
            return null;

        var normalized = new Dictionary<string, object?>(parameters.Count, StringComparer.OrdinalIgnoreCase);
        foreach (var (key, value) in parameters)
        {
            if (string.IsNullOrWhiteSpace(key))
                throw new InvalidOperationException("Parameter names cannot be empty.");

            var normalizedKey = key[0] == '$' ? key[1..] : key;
            if (string.IsNullOrWhiteSpace(normalizedKey))
                throw new InvalidOperationException("Parameter names cannot be empty.");

            normalized[normalizedKey] = value;
        }

        return normalized;
    }

    private PreparedStatementMetadata DescribePreparedStatement(string query)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(query);

        var normalizedQuery = NormalizePlannerLoadFromLiteralPath(query);
        var preprocCallSub = new Parser.Antlr4.CallSubqueryPreprocessor();
        normalizedQuery = preprocCallSub.Preprocess(normalizedQuery);
        var inputStream = new AntlrInputStream(normalizedQuery);
        var lexer = new CypherLexer(inputStream);
        var syntaxErrors = new List<string>();
        lexer.RemoveErrorListeners();
        lexer.AddErrorListener(new QueryLexerSyntaxErrorListener(syntaxErrors));
        var tokenStream = new CommonTokenStream(lexer);
        var parser = new CypherParser(tokenStream);
        parser.RemoveErrorListeners();
        parser.AddErrorListener(new QuerySyntaxErrorListener(syntaxErrors));
        var root = parser.ku_Statements();
        if (syntaxErrors.Count > 0)
            throw new InvalidOperationException(string.Join(Environment.NewLine, syntaxErrors));

        var transformer = new Parser.Antlr4.Transformer(root, preprocCallSub.ExtractedBodies);
        var statements = transformer.Transform();
        if (statements.Count == 0)
            throw new InvalidOperationException("No statement was parsed from the provided query.");
        if (statements.Count > 1)
            throw new InvalidOperationException("Prepared statements currently support a single statement only.");

        var statement = statements[0];
        if (statement.GetStatementType() == StatementType.TRANSACTION)
            throw new InvalidOperationException("Transaction statements cannot be prepared.");

        var binder = new BogDb.Core.Binder.Binder(
            _database.Catalog,
            ReadCopyCsvHeader,
            name => _database.TryGetExtensionOption(name, out var option) ? option : null);
        var boundStatement = binder.Bind(statement);
        return BuildPreparedStatementMetadata(boundStatement, binder.ParameterExpectedTypes);
    }

    private static PreparedStatementMetadata BuildPreparedStatementMetadata(
        BoundStatement boundStatement,
        IReadOnlyDictionary<string, LogicalTypeID> parameterExpectedTypes)
    {
        var preparedParameterTypes = parameterExpectedTypes.ToDictionary(
            pair => pair.Key,
            pair => BogDbLogicalType.FromId(pair.Value),
            StringComparer.OrdinalIgnoreCase);

        if (boundStatement is BoundRegularQuery regularQuery &&
            regularQuery.GetNumSingleQueries() > 0 &&
            regularQuery.GetSingleQuery(0).HasReturnClause())
        {
            var resultColumns = regularQuery
                .GetSingleQuery(0)
                .ReturnClause!
                .Items
                .Select((item, ordinal) => new BogDbColumnDescriptor(
                    item.ColumnName,
                    ordinal,
                    BogDbLogicalType.FromId(item.Expression.DataType)))
                .ToArray();
            return new PreparedStatementMetadata(resultColumns, preparedParameterTypes);
        }

        return new PreparedStatementMetadata(Array.Empty<BogDbColumnDescriptor>(), preparedParameterTypes);
    }

    private void ThrowIfInterruptedOrTimedOut(Stopwatch stopwatch)
    {
        if (Interlocked.Exchange(ref _interruptRequested, 0) == 1)
            throw new OperationCanceledException("Query execution was interrupted.");

        var timeoutMs = ClientContext.TimeoutInMs;
        if (timeoutMs > 0 && stopwatch.ElapsedMilliseconds > (long)timeoutMs)
            throw new TimeoutException($"Query execution exceeded the configured timeout of {timeoutMs} ms.");
    }

    private static IReadOnlyList<string> ExtractParameterNames(string query)
    {
        if (string.IsNullOrWhiteSpace(query))
            return Array.Empty<string>();

        var matches = System.Text.RegularExpressions.Regex.Matches(
            query,
            @"(?<![A-Za-z0-9_])\$(?<name>[A-Za-z_][A-Za-z0-9_]*)");

        if (matches.Count == 0)
            return Array.Empty<string>();

        var ordered = new List<string>(matches.Count);
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (System.Text.RegularExpressions.Match match in matches)
        {
            var parameterName = match.Groups["name"].Value;
            if (seen.Add(parameterName))
                ordered.Add(parameterName);
        }

        return ordered;
    }

    private static List<PropertyDefinition> ToPropertyDefinitions(IReadOnlyList<BoundColumnDefinition> properties)
    {
        var result = new List<PropertyDefinition>(properties.Count);
        foreach (var property in properties)
        {
            result.Add(new PropertyDefinition(
                new ColumnDefinition(property.Name, property.Type, property.DeclaredType)));
        }

        return result;
    }

    private static LogicalTypeID ParseLogicalType(string typeName)
        => DeclaredTypeDescriptor.Parse(typeName).RuntimeType;

    private static object? GetLiteralDefaultValue(ParsedExpression? defaultExpression, out string defaultExpressionName)
    {
        defaultExpressionName = string.Empty;
        if (defaultExpression == null)
            return null;
        if (defaultExpression is not ParsedLiteralExpression literal)
            throw new InvalidOperationException("ALTER TABLE ... ADD ... DEFAULT currently supports literal defaults only.");

        defaultExpressionName = literal.GetRawName();
        return literal.Value;
    }

    private QueryResult.QueryResult CreateNoOpSuccessResult()
    {
        var noOp = new BogDb.Core.Processor.Operator.NoOpPhysicalOperator(0);
        var collector = new BogDb.Core.Processor.Operator.Result.ResultCollector(noOp, 999);
        var execContext = new BogDb.Core.Processor.ExecutionContext(
            BogDb.Core.Transaction.Transaction.DUMMY_TRANSACTION, _database.BufferManager);
        collector.GetNextTuple(execContext);
        return new QueryResult.QueryResult(collector);
    }

    private QueryResult.QueryResult FinalizeQueryResult(
        QueryResult.QueryResult result,
        QueryMetricsContext queryMetrics,
        bool success)
    {
        var totalMilliseconds = queryMetrics.Stop();
        var executionMetrics = queryMetrics.BuildExecutionMetrics(result.GetNumTuples());
        result.AttachTotalMilliseconds(totalMilliseconds);
        result.AttachExecutionMetrics(executionMetrics);
        _database.MetricsRegistry.RecordQuery(success && result.IsSuccess, totalMilliseconds, executionMetrics);
        return result;
    }

    private QueryResult.QueryResult CreateMessageResult(string message)
    {
        return QueryResult.QueryResult.FromOrderedRows(
            new[]
            {
                new Dictionary<string, object?>
                {
                    ["result"] = message
                }
            },
            new[] { "result" });
    }

    // ── GDS CALL helper ──────────────────────────────────────────────────────────

    private static readonly System.Text.RegularExpressions.Regex _gdsCallRegex =
        new System.Text.RegularExpressions.Regex(
            @"^CALL\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*\((?<args>[^)]*)\)\s*(?:YIELD|RETURN)\s+\*\s*;?$",
            System.Text.RegularExpressions.RegexOptions.IgnoreCase |
            System.Text.RegularExpressions.RegexOptions.Compiled);

    /// <summary>
    /// Intercepts <c>CALL algorithmName([args]) YIELD *</c> / <c>RETURN *</c>
    /// for registered GDS algorithms, runs the algorithm, and returns results
    /// as a <see cref="QueryResult.QueryResult"/>.
    /// Falls through to the Cypher parser for non-GDS CALL statements.
    /// </summary>
    private QueryResult.QueryResult? TryExecuteGdsCall(string query)
    {
        var match = _gdsCallRegex.Match(query);
        if (!match.Success) return null;

        var algoName = match.Groups["name"].Value;
        if (!GdsRegistry.IsGdsFunction(algoName)) return null;

        // Parse simple positional/keyword args from the argument string
        var argsRaw = match.Groups["args"].Value.Trim();
        var opts    = ParseGdsCallOptions(argsRaw);

        try
        {
            var op   = new PhysicalGdsCall(_database, algoName, opts, GetCurrentTransactionOrNull());
            var cols = op.OutputColumns;
            var rows = new List<Dictionary<string, object?>>();
            while (op.Next(out var row)) rows.Add(row);
            return QueryResult.QueryResult.FromTableFunctionRows(rows);
        }
        catch (Exception ex)
        {
            return QueryResult.QueryResult.FromError(ex.Message);
        }
    }

    /// <summary>
    /// Parses a CALL argument list into <see cref="GdsCallOptions"/>.
    /// Supports:
    ///   CALL algo('sourceId', maxIter, dampingFactor)    — positional
    ///   No args                                          — defaults
    /// </summary>
    private static GdsCallOptions ParseGdsCallOptions(string argsRaw)
    {
        if (string.IsNullOrWhiteSpace(argsRaw)) return GdsCallOptions.Defaults;

        // Split on commas (simple; does not handle nested parens)
        var parts = argsRaw.Split(',', StringSplitOptions.RemoveEmptyEntries);
        NodeId? sourceNode = null;
        int maxIter = 20;
        double damping = 0.85;
        string? weightProp = null;
        string direction = "OUT";

        for (int i = 0; i < parts.Length; i++)
        {
            var part = parts[i].Trim().Trim('\'', '"');
            switch (i)
            {
                case 0:
                    // First arg: source node id (string "offset" or "table:offset")
                    if (ulong.TryParse(part, out ulong off))
                        sourceNode = new NodeId(off);
                    else if (part.Contains(':'))
                    {
                        var seg = part.Split(':');
                        if (uint.TryParse(seg[0], out var tid) &&
                            ulong.TryParse(seg[1], out var o2))
                            sourceNode = new NodeId(o2, tid);
                    }
                    break;
                case 1:
                    if (int.TryParse(part, out var mi)) maxIter = mi;
                    break;
                case 2:
                    if (double.TryParse(part,
                        System.Globalization.NumberStyles.Float,
                        System.Globalization.CultureInfo.InvariantCulture, out var d))
                        damping = d;
                    break;
                case 3:
                    weightProp = string.IsNullOrWhiteSpace(part) ? null : part;
                    break;
                case 4:
                    direction = part.ToUpperInvariant() switch
                    {
                        "IN"   => "IN",
                        "BOTH" => "BOTH",
                        _      => "OUT",
                    };
                    break;
            }
        }

        return new GdsCallOptions
        {
            SourceNode     = sourceNode,
            MaxIterations  = maxIter,
            DampingFactor  = damping,
            WeightProperty = weightProp,
            Direction      = direction,
        };
    }

    // ── LOAD FROM helper ─────────────────────────────────────────────────────────
    private static readonly System.Text.RegularExpressions.Regex _loadFromRegex =
        new System.Text.RegularExpressions.Regex(
            @"^LOAD(?:\s+WITH\s+HEADERS\s*\(.*?\))?\s+FROM\s+[""'](?<path>.*?)[""']",
            System.Text.RegularExpressions.RegexOptions.IgnoreCase |
            System.Text.RegularExpressions.RegexOptions.Singleline);

    private static string NormalizePlannerLoadFromLiteralPath(string query)
    {
        var match = _loadFromRegex.Match(query.Trim());
        if (!match.Success)
            return query;

        var source = match.Groups["path"].Value;
        if (string.IsNullOrWhiteSpace(source) || !source.Contains('\\'))
            return query;

        var normalizedSource = source.Replace('\\', '/');
        return query.Replace(match.Groups["path"].Value, normalizedSource);
    }

    private static string ResolveFilePath(string path)
    {
        if (System.IO.File.Exists(path)) return path;

        // Strip leading ../ segments and search upward from binary dir
        var normalised = path.Replace('\\', System.IO.Path.DirectorySeparatorChar);
        var segments = normalised.Split(System.IO.Path.DirectorySeparatorChar, StringSplitOptions.RemoveEmptyEntries);
        var tail = string.Join(System.IO.Path.DirectorySeparatorChar.ToString(),
            segments.SkipWhile(s => s == ".."));

        var dir = new System.IO.DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            var candidate = System.IO.Path.Combine(dir.FullName, tail);
            if (System.IO.File.Exists(candidate)) return candidate;
            dir = dir.Parent;
        }
        return path; // Let the function raise FileNotFoundException
    }

    private string ResolveReadablePath(string path)
        => IsRegisteredFileSystemPath(path) ? path : ResolveFilePath(path);

    private List<string> ReadCopyCsvHeader(string path)
        => Processor.Operator.Persistent.Reader.CSV.CsvFileAccess.ReadCsvHeader(_database, path);
    // ─────────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Executes a sequential .cypher file script extracting statements delimited by semicolons natively.
    /// </summary>
    public void ExecuteScript(string filePath)
    {
        string content = ReadAllTextFromPath(filePath);
        var queries = content.Split(';', StringSplitOptions.RemoveEmptyEntries);
        foreach (var q in queries)
        {
            if (string.IsNullOrWhiteSpace(q)) continue;
            Query(q);
        }
    }

    /// <summary>
    /// Phase 33: LINQ Integration allowing native Queryable tracking across generic Entity configurations natively.
    /// </summary>
    public System.Linq.IQueryable<T> AsQueryable<T>(string label = "")
    {
        var provider = new BogDb.Core.Linq.BogDbQueryProvider(this, string.IsNullOrEmpty(label) ? typeof(T).Name : label);
        return new BogDb.Core.Linq.BogDbQueryable<T>(provider, System.Linq.Expressions.Expression.Constant(this));
    }

    /// <summary>
    /// Returns true if a table with the given name already exists in the catalog.
    /// Does not require an active transaction.
    /// </summary>
    public bool HasTable(string tableName)
        => _database.Catalog.ContainsTable(null, tableName);

    /// <summary>
    /// Creates an index on <paramref name="propertyName"/> for <paramref name="tableName"/>
    /// and rebuilds it from existing in-memory node data.
    /// Does not require an active write transaction.
    /// </summary>
    public void CreateIndex(string tableName, string propertyName)
    {
        EnsureDatabaseWritable();
        _database.CreateIndex(tableName, propertyName);
        _database.MetricsRegistry.AddIndexLookups(1);
    }

    public void EnsureNodeTable(string tableName)
        => EnsureNodeTable(tableName, new Dictionary<string, LogicalTypeID>());

    public void EnsureNodeTable(string tableName, Dictionary<string, LogicalTypeID> properties)
    {
        var propertyDefinitions = new List<PropertyDefinition>(properties.Count);
        foreach (var prop in properties)
        {
            propertyDefinitions.Add(new PropertyDefinition(new ColumnDefinition(prop.Key, prop.Value)));
        }

        EnsureNodeTableWithDefinitions(tableName, propertyDefinitions);
    }

    private void EnsureNodeTableWithDefinitions(string tableName, IReadOnlyList<PropertyDefinition> properties)
    {
        var transaction = GetRequiredWriteTransaction();

        if (_database.Catalog.ContainsTable(transaction, tableName))
            return;

        var entry = new NodeTableCatalogEntry(tableName, 0); 
        foreach (var propDef in properties)
        {
            entry.AddProperty(propDef);
        }
        _database.Catalog.CreateTableEntry(transaction, entry);
        
        var table = new NodeTableData();
        _database.BindTablePersistenceSurface(tableName, table);
        _database.NodeTables[tableName] = table;
        
        _database.StorageManager.GetWAL().LogCreateTableRecord(checked((uint)entry.TableID), entry);
    }

    public void EnsureRelTable(string tableName, string fromTable, string toTable)
        => EnsureRelTable(tableName, fromTable, toTable, new Dictionary<string, LogicalTypeID>());

    public void EnsureRelTable(string tableName, string fromTable, string toTable, Dictionary<string, LogicalTypeID> properties)
    {
        var propertyDefinitions = new List<PropertyDefinition>(properties.Count);
        foreach (var prop in properties)
        {
            propertyDefinitions.Add(new PropertyDefinition(new ColumnDefinition(prop.Key, prop.Value)));
        }

        EnsureRelTableWithDefinitions(tableName, fromTable, toTable, propertyDefinitions);
    }

    private void EnsureRelTableWithDefinitions(string tableName, string fromTable, string toTable, IReadOnlyList<PropertyDefinition> properties)
    {
        var transaction = GetRequiredWriteTransaction();

        if (_database.Catalog.ContainsTable(transaction, tableName))
            return;

        var entry = new RelGroupCatalogEntry(tableName, fromTable, toTable); 
        foreach (var propDef in properties)
        {
            entry.AddProperty(propDef);
        }
        _database.Catalog.CreateTableEntry(transaction, entry);
        
        var table = new RelTableData(fromTable, toTable);
        _database.BindTablePersistenceSurface(tableName, table);
        _database.RelTables[tableName] = table;
        
        _database.StorageManager.GetWAL().LogCreateTableRecord(checked((uint)entry.TableID), entry);
    }

    public void UpsertNode(string tableName, object id, Dictionary<string, object> properties)
    {
        var transaction = GetRequiredWriteTransaction();

        if (!_database.NodeTables.TryGetValue(tableName, out var table))
        {
            table = new NodeTableData();
            _database.BindTablePersistenceSurface(tableName, table);
            _database.NodeTables[tableName] = table;
        }

        var normalized = NormalizeProperties(tableName, properties);
        ApplyCatalogDefaults(tableName, normalized);
        normalized = CoercePropertiesForTable(tableName, normalized);
        table.Upsert(transaction, id, normalized);
        _database.GraphLog.AppendNode(tableName, id, normalized);
        UpdateIndexesForNode(tableName, transaction, id, normalized, table);
        _database.MetricsRegistry.AddNodesWritten(1);
    }

    /// <summary>
    /// Upserts a node directly into the in-memory node table and appends to the graph log,
    /// bypassing the Cypher parser. Use this for reliable bulk-write paths where MERGE
    /// Cypher parity is not yet guaranteed.
    /// </summary>
    public void UpsertNodeById(string tableName, string id, Dictionary<string, object> properties)
    {
        ExecuteDirectWrite(() =>
        {
            if (!_database.NodeTables.TryGetValue(tableName, out var table))
            {
                table = new NodeTableData();
                _database.BindTablePersistenceSurface(tableName, table);
                _database.NodeTables[tableName] = table;
            }
            var normalized = NormalizeProperties(tableName, properties);
            ApplyCatalogDefaults(tableName, normalized);
            normalized = CoercePropertiesForTable(tableName, normalized);
            table.Upsert(GetRequiredWriteTransaction(), id, normalized);
            _database.GraphLog.AppendNode(tableName, id, normalized);
            UpdateIndexesForNode(tableName, GetRequiredWriteTransaction(), id, normalized, table);
            _database.MetricsRegistry.AddNodesWritten(1);
        });
    }

    public void UpsertRelationship(string relationshipTableName, object fromNodeId, object toNodeId, Dictionary<string, object> properties)
    {
        var transaction = GetRequiredWriteTransaction();

        if (!_database.RelTables.TryGetValue(relationshipTableName, out var table))
        {
            table = new RelTableData();
            _database.BindTablePersistenceSurface(relationshipTableName, table);
            _database.RelTables[relationshipTableName] = table;
        }

        var key = new EdgeKey(fromNodeId, toNodeId);
        var normalized = NormalizeProperties(relationshipTableName, properties);
        ApplyCatalogDefaults(relationshipTableName, normalized);
        normalized = CoercePropertiesForTable(relationshipTableName, normalized);
        table.Upsert(transaction, key, normalized);
        _database.GraphLog.AppendRel(relationshipTableName, fromNodeId, toNodeId, normalized);
        _database.MetricsRegistry.AddRelationshipsWritten(1);
    }

    /// <summary>
    /// Upserts a relationship directly into the in-memory rel table and appends to the graph log,
    /// bypassing the Cypher parser. Use this for reliable bulk-write paths where MERGE
    /// Cypher parity is not yet guaranteed.
    /// </summary>
    public void UpsertRelationshipById(
        string tableName,
        string fromId,
        string toId,
        Dictionary<string, object> properties)
    {
        ExecuteDirectWrite(() =>
        {
            if (!_database.RelTables.TryGetValue(tableName, out var table))
            {
                table = new RelTableData();
                _database.BindTablePersistenceSurface(tableName, table);
                _database.RelTables[tableName] = table;
            }
            var key = new EdgeKey(fromId, toId);
            var normalized = NormalizeProperties(tableName, properties);
            ApplyCatalogDefaults(tableName, normalized);
            normalized = CoercePropertiesForTable(tableName, normalized);
            table.Upsert(GetRequiredWriteTransaction(), key, normalized);
            _database.GraphLog.AppendRel(tableName, fromId, toId, normalized);
            _database.MetricsRegistry.AddRelationshipsWritten(1);
        });
    }

    private static Dictionary<string, object> NormalizeProperties(string tableName, Dictionary<string, object> properties)
    {
        var normalized = new Dictionary<string, object>(properties.Count, StringComparer.OrdinalIgnoreCase);
        foreach (var (key, value) in properties)
        {
            normalized[key] = TypeCoercionHelper.Normalize(value) ?? string.Empty;
        }
        return normalized;
    }

    private Dictionary<string, object> CoercePropertiesForTable(string tableName, Dictionary<string, object> properties)
    {
        var entry = _database.Catalog.GetTableCatalogEntry(GetCurrentTransactionOrNull(), tableName, useInternal: false);
        return Catalog.PropertyValueCoercion.CoerceProperties(entry, properties);
    }

    private void ApplyCatalogDefaults(string tableName, Dictionary<string, object> properties)
    {
        var entry = _database.Catalog.GetTableCatalogEntry(GetCurrentTransactionOrNull(), tableName, useInternal: false);
        if (entry == null)
            return;

        foreach (var property in entry.GetProperties())
        {
            if (properties.ContainsKey(property.Name) || string.IsNullOrWhiteSpace(property.DefaultExpressionName))
                continue;

            if (TryParseDefaultLiteral(property.DefaultExpressionName, out var defaultValue))
                properties[property.Name] = defaultValue!;
        }
    }

    private static bool TryParseDefaultLiteral(string raw, out object? value)
    {
        value = null;
        if (string.IsNullOrWhiteSpace(raw))
            return false;

        var trimmed = raw.Trim();
        if (string.Equals(trimmed, "null", StringComparison.OrdinalIgnoreCase))
            return true;
        if (string.Equals(trimmed, "true", StringComparison.OrdinalIgnoreCase))
        {
            value = true;
            return true;
        }
        if (string.Equals(trimmed, "false", StringComparison.OrdinalIgnoreCase))
        {
            value = false;
            return true;
        }
        if ((trimmed.StartsWith("'") && trimmed.EndsWith("'")) || (trimmed.StartsWith("\"") && trimmed.EndsWith("\"")))
        {
            value = trimmed[1..^1]
                .Replace("\\'", "'")
                .Replace("\\\"", "\"")
                .Replace("\\\\", "\\")
                .Replace("\\n", "\n")
                .Replace("\\t", "\t")
                .Replace("\\r", "\r");
            return true;
        }
        if (long.TryParse(trimmed, out var longValue))
        {
            value = longValue;
            return true;
        }
        if (double.TryParse(trimmed, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var doubleValue))
        {
            value = doubleValue;
            return true;
        }

        return false;
    }

    private void UpdateIndexesForNode(string tableName, BogDb.Core.Transaction.Transaction tx, object id, Dictionary<string, object> props, NodeTableData table)
        => _database.UpdateNodeIndexes(tableName, tx, id, props, table);

    private string FormatValue(object value)
    {
        return value switch
        {
            string s => $"'{s}'",
            DateTime d => $"date('{d:yyyy-MM-dd}')",
            bool b => b ? "true" : "false",
            _ => value.ToString() ?? "null"
        };
    }
    
    public Dictionary<string, object>? ReadNode(string tableName, object id)
    {
        var tx = _activeTransaction ?? ClientContext.ActiveTransaction;
        if (_database.NodeTables.TryGetValue(tableName, out var table))
        {
            Dictionary<string, object>? props;
            var found = tx is null
                ? table.TryGetProperties(id, out props)
                : table.TryGetProperties(tx, id, out props);
            if (found)
            {
                _database.MetricsRegistry.AddNodeReads(1);
                return NormalizeReadProperties(tableName, props);
            }
        }
        return null;
    }

    /// <summary>
    /// Returns the names of all node tables currently registered in the database.
    /// </summary>
    public IReadOnlyList<string> GetNodeTableNames()
        => new List<string>(_database.NodeTables.Keys);

    /// <summary>
    /// Returns the properties of a node identified by <paramref name="id"/> by
    /// searching all node tables. Returns null if not found.
    /// </summary>
    public Dictionary<string, object>? GetNodeById(string id, out string? tableName)
    {
        var tx = _activeTransaction ?? ClientContext.ActiveTransaction;
        foreach (var (name, table) in _database.NodeTables)
        {
            Dictionary<string, object>? props;
            var found = tx is null
                ? table.TryGetProperties(id, out props)
                : table.TryGetProperties(tx, id, out props);
            if (found)
            {
                _database.MetricsRegistry.AddNodeReads(1);
                tableName = name;
                return NormalizeReadProperties(name, props);
            }
        }
        tableName = null;
        return null;
    }

    /// <summary>
    /// Returns all outgoing edges from <paramref name="fromId"/>.  
    /// Each result tuple is (tableName, toId, properties).
    /// Optionally filtered by relationship table name.
    /// </summary>
    public IReadOnlyList<(string TableName, string FromId, string ToId, Dictionary<string, object> Properties)>
        GetOutgoingEdges(string fromId, string? label = null)
    {
        var tx = _activeTransaction ?? ClientContext.ActiveTransaction;
        var results = new List<(string, string, string, Dictionary<string, object>)>();
        foreach (var (tableName, tableData) in _database.RelTables)
        {
            if (label is not null && !string.Equals(tableName, label, StringComparison.Ordinal))
                continue;

            var rows = tx is null
                ? tableData.EnumerateRows()
                : tableData.EnumerateRows(tx);
            foreach (var (key, props) in rows)
            {
                var from = key.From?.ToString();
                if (!string.Equals(from, fromId, StringComparison.Ordinal))
                    continue;

                var to = key.To?.ToString() ?? string.Empty;
                results.Add((tableName, fromId, to, NormalizeReadProperties(tableName, props)));
            }
        }
        _database.MetricsRegistry.AddRelReads(results.Count);
        return results;
    }

    /// <summary>
    /// Returns all incoming edges to <paramref name="toId"/>.
    /// Each result tuple is (tableName, fromId, toId, properties).
    /// Optionally filtered by relationship table name.
    /// </summary>
    public IReadOnlyList<(string TableName, string FromId, string ToId, Dictionary<string, object> Properties)>
        GetIncomingEdges(string toId, string? label = null)
    {
        var tx = _activeTransaction ?? ClientContext.ActiveTransaction;
        var results = new List<(string, string, string, Dictionary<string, object>)>();
        foreach (var (tableName, tableData) in _database.RelTables)
        {
            if (label is not null && !string.Equals(tableName, label, StringComparison.Ordinal))
                continue;

            var rows = tx is null
                ? tableData.EnumerateRows()
                : tableData.EnumerateRows(tx);
            foreach (var (key, props) in rows)
            {
                var to = key.To?.ToString();
                if (!string.Equals(to, toId, StringComparison.Ordinal))
                    continue;

                var from = key.From?.ToString() ?? string.Empty;
                results.Add((tableName, from, toId, NormalizeReadProperties(tableName, props)));
            }
        }
        _database.MetricsRegistry.AddRelReads(results.Count);
        return results;
    }

    private Dictionary<string, object> NormalizeReadProperties(
        string tableName,
        Dictionary<string, object>? props)
    {
        if (props is null)
            return new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase);

        var entry = _database.Catalog.GetTableCatalogEntry(GetCurrentTransactionOrNull(), tableName, useInternal: false);
        return Catalog.PropertyValueCoercion.CoerceProperties(entry, props);
    }

    private bool IsRegisteredFileSystemPath(string filePath)
    {
        var schemeSeparator = filePath.IndexOf("://", StringComparison.Ordinal);
        if (schemeSeparator <= 0)
            return false;

        var scheme = filePath[..schemeSeparator];
        return _database.TryGetFileSystem(scheme, out _);
    }

    private string ReadAllTextFromPath(string filePath)
    {
        if (TryReadAllTextFromRegisteredFileSystem(filePath, out var content))
            return content;

        if (!System.IO.File.Exists(filePath))
            throw new System.IO.FileNotFoundException("Cypher script not found.", filePath);

        return System.IO.File.ReadAllText(filePath);
    }

    private bool TryReadAllTextFromRegisteredFileSystem(string filePath, out string content)
    {
        content = string.Empty;
        var schemeSeparator = filePath.IndexOf("://", StringComparison.Ordinal);
        if (schemeSeparator <= 0)
            return false;

        var scheme = filePath[..schemeSeparator];
        if (!_database.TryGetFileSystem(scheme, out var fileSystem))
            return false;

        using var fileInfo = fileSystem.OpenFile(filePath, FileFlags.Read);
        var fileSize = checked((int)fileInfo.GetFileSize());
        var buffer = new byte[fileSize];
        fileInfo.Read(buffer, 0);
        content = System.Text.Encoding.UTF8.GetString(buffer);
        return true;
    }

    public void Dispose()
    {
        // Roll back any transaction still open at dispose time. Without this, disposing a connection with
        // an uncommitted write transaction — e.g. an exception escaping a `using` block — leaves the
        // transaction registered forever: the single-writer slot is never released and every later write on
        // any connection fails "Only one write transaction". SqlConnection/SQLite roll back on dispose the
        // same way. Best-effort — Dispose must not throw.
        if ((_activeTransaction ?? ClientContext.ActiveTransaction) != null)
        {
            try { Rollback(); }
            catch { /* releasing the slot is best-effort; Dispose cannot propagate an exception */ }
        }

        _activeTransaction = null;
        ClientContext.Dispose();
    }

    internal Transaction.Transaction? GetCurrentTransactionOrNull()
        => _activeTransaction ?? ClientContext.ActiveTransaction;

    private void ExecuteDirectWrite(Action action)
    {
        ExecuteWriteTransaction(action);
    }

    private void StartTransaction(BogDb.Core.Transaction.TransactionType type)
    {
        if (type == BogDb.Core.Transaction.TransactionType.WRITE)
        {
            EnsureDatabaseWritable();
        }

        ClientContext.StartTransaction(type);
        var transaction = ClientContext.ActiveTransaction;
        if (transaction != null && transaction.IsWriteTransaction())
        {
            transaction.CaptureRecoveryOffsets(
                _database.StorageManager.GetWAL().GetFileSize(),
                _database.GraphLog.GetFileSize());
        }
    }

    private Transaction.Transaction GetRequiredWriteTransaction()
    {
        if (_database.IsReadOnly)
            throw new InvalidOperationException("Database is open in read-only mode.");

        var transaction = GetCurrentTransactionOrNull();
        if (transaction == null || !transaction.IsWriteTransaction())
            throw new InvalidOperationException("Requires write transaction.");
        return transaction;
    }

    private void EnsureDatabaseWritable()
    {
        if (_database.IsReadOnly)
            throw new InvalidOperationException("Database is open in read-only mode.");
    }

    private sealed class QuerySyntaxErrorListener(List<string> errors) : BaseErrorListener
    {
        public override void SyntaxError(
            TextWriter output,
            IRecognizer recognizer,
            IToken offendingSymbol,
            int line,
            int charPositionInLine,
            string msg,
            RecognitionException e)
        {
            errors.Add($"Syntax error at line {line}, column {charPositionInLine}: {msg}");
        }
    }

    private sealed class QueryLexerSyntaxErrorListener(List<string> errors) : IAntlrErrorListener<int>
    {
        public void SyntaxError(
            TextWriter output,
            IRecognizer recognizer,
            int offendingSymbol,
            int line,
            int charPositionInLine,
            string msg,
            RecognitionException e)
        {
            errors.Add($"Syntax error at line {line}, column {charPositionInLine}: {msg}");
        }
    }

    private readonly record struct PreparedStatementMetadata(
        IReadOnlyList<BogDbColumnDescriptor> ResultColumns,
        IReadOnlyDictionary<string, BogDbLogicalType> ParameterExpectedTypes);
}
