//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (client_context.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using BogDb.Core.Common.Diagnostics;
using BogDb.Core.Transaction;

namespace BogDb.Core.Main;

/// <summary>
/// Scopes global variables specific to a client query sequence including
/// isolation timeouts, currently active transactions, and diagnostic warnings.
/// </summary>
public sealed class ClientContext : IDisposable
{
    private readonly BogConnection _connection;
    public Transaction.Transaction ActiveTransaction { get; private set; }
    internal QueryMetricsContext? CurrentQueryMetrics { get; set; }
    
    // Performance Configuration Constants
    public ulong TimeoutInMs { get; set; } = 0; // 0 = Infinite

    public ClientContext(BogConnection connection)
    {
        _connection = connection;
    }

    public void StartTransaction(TransactionType type = TransactionType.READ_ONLY)
    {
        ActiveTransaction = _connection.Database.TransactionManager.BeginTransaction(this, type);
    }

    public void Commit()
    {
        if (ActiveTransaction != null)
        {
            _connection.Database.TransactionManager.Commit(this, ActiveTransaction);
            ActiveTransaction = null;
        }
    }

    public void Rollback()
    {
        if (ActiveTransaction != null)
        {
            _connection.Database.TransactionManager.Rollback(this, ActiveTransaction);
            ActiveTransaction = null;
        }
    }

    public void Dispose()
    {
        // Cancel outstanding query tokens if active
        GC.SuppressFinalize(this);
    }
}
