//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (logical_semi_masker.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations where applicable.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using BogDb.Core.Binder;
using BogDb.Core.Common;

namespace BogDb.Core.Planner.Operator.Sip;

public enum SemiMaskKeyType : byte
{
    NODE = 0,
    PATH = 1,
    NODE_ID_LIST = 2
}

public enum SemiMaskTargetType : byte
{
    SCAN_NODE = 0,
    RECURSIVE_EXTEND_INPUT_NODE = 2,
    RECURSIVE_EXTEND_OUTPUT_NODE = 3,
    RECURSIVE_EXTEND_PATH_NODE = 4,
    GDS_GRAPH_NODE = 5
}

public abstract class ExtraKeyInfo
{
    public abstract ExtraKeyInfo Copy();
}

public sealed class ExtraPathKeyInfo : ExtraKeyInfo
{
    public ExtendDirection Direction { get; }

    public ExtraPathKeyInfo(ExtendDirection direction)
    {
        Direction = direction;
    }

    public override ExtraKeyInfo Copy() => new ExtraPathKeyInfo(Direction);
}

public sealed class ExtraNodeIdListKeyInfo : ExtraKeyInfo
{
    public Expression SrcNodeId { get; }
    public Expression DstNodeId { get; }

    public ExtraNodeIdListKeyInfo(Expression srcNodeId, Expression dstNodeId)
    {
        SrcNodeId = srcNodeId;
        DstNodeId = dstNodeId;
    }

    public override ExtraKeyInfo Copy() => new ExtraNodeIdListKeyInfo(SrcNodeId, DstNodeId);
}

public sealed class LogicalSemiMasker : LogicalOperator
{
    public SemiMaskKeyType KeyType { get; }
    public SemiMaskTargetType TargetType { get; }
    public Expression Key { get; }
    public IReadOnlyList<ulong> NodeTableIds { get; }
    public ExtraKeyInfo? ExtraKeyInfo { get; private set; }
    public List<LogicalOperator> TargetOperators { get; }

    public LogicalSemiMasker(
        SemiMaskKeyType keyType,
        SemiMaskTargetType targetType,
        Expression key,
        IReadOnlyList<ulong> nodeTableIds,
        LogicalOperator child)
        : base(LogicalOperatorType.LOGICAL_SEMI_MASKER, child)
    {
        KeyType = keyType;
        TargetType = targetType;
        Key = key;
        NodeTableIds = nodeTableIds;
        TargetOperators = new List<LogicalOperator>();
    }

    public void SetExtraKeyInfo(ExtraKeyInfo extraKeyInfo)
    {
        ExtraKeyInfo = extraKeyInfo;
    }

    public void AddTarget(LogicalOperator op)
    {
        TargetOperators.Add(op);
    }

    public override string GetExpressionsForPrinting() => Key.ToString() ?? string.Empty;
}
