//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (aggregate.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using BogDb.Core.Common;

namespace BogDb.Core.Processor.Operator.Aggregate;

public enum AggregateFunctionType 
{
    COUNT,
    SUM,
    AVG,
    MIN,
    MAX
}

/// <summary>
/// A Physical Operator scanning vectors computing grouping keys and reducing values natively.
/// </summary>
public sealed class Aggregate : PhysicalOperator
{
    private readonly PhysicalOperator _child;
    private readonly List<int> _groupByKeyIndices;
    private readonly List<AggregateFunctionType> _aggregateFunctions;
    
    // Natively this builds a Thread-Safe Hash Table where each entry is an 
    // aggregation state updating via Interlocked atomic methods.
    private Dictionary<long, object> _aggregationStates;

    public Aggregate(
        PhysicalOperator child, 
        List<int> groupByKeyIndices, 
        List<AggregateFunctionType> aggregateFunctions,
        uint id) 
        : base(PhysicalOperatorType.AGGREGATE, id)
    {
        _child = child;
        _groupByKeyIndices = groupByKeyIndices;
        _aggregateFunctions = aggregateFunctions;
        _aggregationStates = new Dictionary<long, object>();
    }

    public override bool GetNextTuple(ExecutionContext context)
    {
        // Drain the entire child pipeline updating grouping states
        while (_child.GetNextTuple(context))
        {
             // Omitted for Phase 9 stub
        }

        // Return the aggregated results as a finalized Vector
        return false; 
    }
}
