//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (filter.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Binder;

namespace BogDb.Core.Processor.Operator.Filter;

/// <summary>
/// Filters chunks emitting tuples fulfilling the parsed predicates.
/// </summary>
public sealed class PhysicalFilter : PhysicalOperator
{
    private readonly Expression _predicate;

    public PhysicalFilter(Expression predicate, PhysicalOperator child, uint id) 
        : base(PhysicalOperatorType.FILTER, child, id)
    {
        _predicate = predicate;
    }

    public override bool GetNextTuple(ExecutionContext context)
    {
        while (Children[0].GetNextTuple(context))
        {
            if (ExpressionExecutionHelper.EvaluatePredicate(_predicate, context))
            {
                return true;
            }
        }

        return false;
    }
}
