//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (data_pos.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BogDb.Core.Processor;

/// <summary>
/// DataPos maps a variable from the LogicalAST down to the exact 
/// ValueVector chunk offset during Physical Execution.
/// </summary>
public readonly struct DataPos : IEquatable<DataPos>
{
    public const uint INVALID_DATA_CHUNK_POS = uint.MaxValue;
    public const uint INVALID_VALUE_VECTOR_POS = uint.MaxValue;

    public readonly uint DataChunkPos;
    public readonly uint ValueVectorPos;

    public DataPos(uint dataChunkPos, uint valueVectorPos)
    {
        DataChunkPos = dataChunkPos;
        ValueVectorPos = valueVectorPos;
    }

    public DataPos()
    {
        DataChunkPos = INVALID_DATA_CHUNK_POS;
        ValueVectorPos = INVALID_VALUE_VECTOR_POS;
    }

    public bool IsValid()
    {
        return DataChunkPos != INVALID_DATA_CHUNK_POS && ValueVectorPos != INVALID_VALUE_VECTOR_POS;
    }

    public bool Equals(DataPos other)
    {
        return DataChunkPos == other.DataChunkPos && ValueVectorPos == other.ValueVectorPos;
    }

    public override bool Equals(object obj)
    {
        return obj is DataPos other && Equals(other);
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(DataChunkPos, ValueVectorPos);
    }
}
