//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (execution_context.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using BogDb.Core.Common.Diagnostics;
using BogDb.Core.Storage.BufferManager;
using BogDb.Core.Storage.MemoryManager;

namespace BogDb.Core.Processor;

/// <summary>
/// Central dependency passed globally throughout the physical graph evaluation.
/// Tracks transaction ID isolation guarantees and resource limits.
/// </summary>
public class ExecutionContext
{
    public Main.BogDatabase? Database { get; }
    public Transaction.Transaction Transaction { get; }
    public BufferManager BufferManager { get; }
    public MemoryManager MemoryManager { get; }
    internal QueryMetricsContext? QueryMetrics { get; set; }
    public object? CurrentNodeId { get; set; }
    public IReadOnlyDictionary<string, object?>? ParameterBindings { get; set; }
    public Dictionary<string, object?>? CurrentScalarBindings { get; set; }
    public Dictionary<string, object>? CurrentNodeProperties { get; set; }
    public object[]? CurrentProjectionRow { get; set; }
    public Dictionary<string, object>? CurrentVariableIds { get; set; }
    public Dictionary<string, Dictionary<string, object>>? CurrentVariableProperties { get; set; }
    /// <summary>Pre-computed aggregate values written by PhysicalAggregate for downstream operators (e.g. ORDER BY) to read.</summary>
    public Dictionary<string, object?>? AggregateValues { get; set; }
    /// <summary>Optional semi-mask cache populated by PhysicalSemiMasker for downstream operators.</summary>
    public Dictionary<ulong, HashSet<object>>? SemiMasks { get; set; }

    public ExecutionContext(Transaction.Transaction transaction, BufferManager bufferManager, Main.BogDatabase? database = null)
    {
        Database = database;
        Transaction = transaction;
        BufferManager = bufferManager;
        // In fully mature systems MemoryManager is tied to the ClientContext, but scoped here implicitly.
        MemoryManager = new MemoryManager(bufferManager);
    }

    // Phase 6 extensions: Cancellation token sources and memory trackers

    public ExecutionState CaptureState()
    {
        return new ExecutionState
        {
            CurrentNodeId = CurrentNodeId,
            ParameterBindings = ParameterBindings == null ? null : new Dictionary<string, object?>(ParameterBindings),
            CurrentNodeProperties = CurrentNodeProperties,
            CurrentScalarBindings = CurrentScalarBindings == null ? null : new Dictionary<string, object?>(CurrentScalarBindings),
            CurrentProjectionRow = CurrentProjectionRow == null ? null : (object[])CurrentProjectionRow.Clone(),
            CurrentVariableIds = CurrentVariableIds == null ? null : new Dictionary<string, object>(CurrentVariableIds),
            CurrentVariableProperties = CurrentVariableProperties == null
                ? null
                : new Dictionary<string, Dictionary<string, object>>(CurrentVariableProperties),
            AggregateValues = AggregateValues == null ? null : new Dictionary<string, object?>(AggregateValues),
            SemiMasks = SemiMasks == null ? null : CloneSemiMasks(SemiMasks)
        };
    }

    public void RestoreState(ExecutionState state)
    {
        CurrentNodeId = state.CurrentNodeId;
        ParameterBindings = state.ParameterBindings == null ? null : new Dictionary<string, object?>(state.ParameterBindings);
        CurrentNodeProperties = state.CurrentNodeProperties;
        CurrentScalarBindings = state.CurrentScalarBindings == null ? null : new Dictionary<string, object?>(state.CurrentScalarBindings);
        CurrentProjectionRow = state.CurrentProjectionRow == null ? null : (object[])state.CurrentProjectionRow.Clone();
        CurrentVariableIds = state.CurrentVariableIds == null ? null : new Dictionary<string, object>(state.CurrentVariableIds);
        CurrentVariableProperties = state.CurrentVariableProperties == null
            ? null
            : new Dictionary<string, Dictionary<string, object>>(state.CurrentVariableProperties);
        AggregateValues = state.AggregateValues == null ? null : new Dictionary<string, object?>(state.AggregateValues);
        SemiMasks = state.SemiMasks == null ? null : CloneSemiMasks(state.SemiMasks);
    }

    private static Dictionary<ulong, HashSet<object>> CloneSemiMasks(
        Dictionary<ulong, HashSet<object>> masks)
    {
        var clone = new Dictionary<ulong, HashSet<object>>();
        foreach (var (key, value) in masks)
        {
            clone[key] = new HashSet<object>(value);
        }
        return clone;
    }
}

public sealed class ExecutionState
{
    public object? CurrentNodeId { get; set; }
    public IReadOnlyDictionary<string, object?>? ParameterBindings { get; set; }
    public Dictionary<string, object>? CurrentNodeProperties { get; set; }
    public Dictionary<string, object?>? CurrentScalarBindings { get; set; }
    public object[]? CurrentProjectionRow { get; set; }
    public Dictionary<string, object>? CurrentVariableIds { get; set; }
    public Dictionary<string, Dictionary<string, object>>? CurrentVariableProperties { get; set; }
    public Dictionary<string, object?>? AggregateValues { get; set; }
    public Dictionary<ulong, HashSet<object>>? SemiMasks { get; set; }

    public static ExecutionState Merge(ExecutionState left, ExecutionState right)
    {
        var mergedIds = left.CurrentVariableIds == null
            ? new Dictionary<string, object>()
            : new Dictionary<string, object>(left.CurrentVariableIds);
        if (right.CurrentVariableIds != null)
        {
            foreach (var pair in right.CurrentVariableIds)
            {
                mergedIds[pair.Key] = pair.Value;
            }
        }

        var mergedProps = left.CurrentVariableProperties == null
            ? new Dictionary<string, Dictionary<string, object>>()
            : new Dictionary<string, Dictionary<string, object>>(left.CurrentVariableProperties);
        if (right.CurrentVariableProperties != null)
        {
            foreach (var pair in right.CurrentVariableProperties)
            {
                mergedProps[pair.Key] = pair.Value;
            }
        }

        var mergedScalarBindings = left.CurrentScalarBindings == null
            ? new Dictionary<string, object?>()
            : new Dictionary<string, object?>(left.CurrentScalarBindings);
        if (right.CurrentScalarBindings != null)
        {
            foreach (var pair in right.CurrentScalarBindings)
            {
                mergedScalarBindings[pair.Key] = pair.Value;
            }
        }

        return new ExecutionState
        {
            CurrentNodeId = right.CurrentNodeId ?? left.CurrentNodeId,
            ParameterBindings = right.ParameterBindings ?? left.ParameterBindings,
            CurrentNodeProperties = right.CurrentNodeProperties ?? left.CurrentNodeProperties,
            CurrentScalarBindings = mergedScalarBindings,
            CurrentProjectionRow = right.CurrentProjectionRow ?? left.CurrentProjectionRow,
            CurrentVariableIds = mergedIds,
            CurrentVariableProperties = mergedProps,
            SemiMasks = MergeSemiMasks(left.SemiMasks, right.SemiMasks)
        };
    }

    private static Dictionary<ulong, HashSet<object>>? MergeSemiMasks(
        Dictionary<ulong, HashSet<object>>? left,
        Dictionary<ulong, HashSet<object>>? right)
    {
        if (left == null && right == null) return null;
        var result = new Dictionary<ulong, HashSet<object>>();
        if (left != null)
        {
            foreach (var (key, values) in left)
                result[key] = new HashSet<object>(values);
        }
        if (right == null) return result;
        foreach (var (key, values) in right)
        {
            if (!result.TryGetValue(key, out var set))
            {
                result[key] = new HashSet<object>(values);
                continue;
            }
            foreach (var value in values) set.Add(value);
        }
        return result;
    }
}
