//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (plan_mapper.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BogDb.Core.Binder;
using BogDb.Core.Planner;
using BogDb.Core.Planner.Operator;
using BogDb.Core.Processor.Operator;
using BogDb.Core.Processor.Operator.Aggregate;
using BogDb.Core.Processor.Operator.Accumulate;
using BogDb.Core.Processor.Operator.Distinct;
using BogDb.Core.Processor.Operator.Filter;
using BogDb.Core.Processor.Operator.Flatten;
using BogDb.Core.Processor.Operator.Limit;
using BogDb.Core.Processor.Operator.Projection;
using BogDb.Core.Processor.Operator.Profile;
using BogDb.Core.Processor.Operator.Scan;
using BogDb.Core.Processor.Operator.Sip;
using BogDb.Core.Processor.Operator.UnionAll;
using BogDb.Core.Processor.Operator.Update;
using CatalogModel = BogDb.Core.Catalog;

namespace BogDb.Core.Processor;

/// <summary>
/// Map logical heuristically constrained AST execution sequences securely into the 
/// native Physical Pipeline memory framework pulling bytes lazily!
/// </summary>
public sealed class PlanMapper
{
    private uint _physicalOperatorIdCounter;
    private readonly Main.BogDatabase _database;

    public PlanMapper(Main.BogDatabase database = null)
    {
        _physicalOperatorIdCounter = 0;
        _database = database;
    }

    public PhysicalPlan MapLogicalPlanToPhysical(LogicalPlan logicalPlan)
    {
        var physicalRoot = MapOperator(logicalPlan.LastOperator);
        return new PhysicalPlan(physicalRoot);
    }

    private PhysicalOperator MapOperator(LogicalOperator logicalOperator)
    {
        switch (logicalOperator.OperatorType)
        {
            case LogicalOperatorType.LOGICAL_SCAN_NODE:
                return MapLogicalScanNodeToPhysical((LogicalScanNodeProperty)logicalOperator);
            case LogicalOperatorType.LOGICAL_FILTER:
                return MapLogicalFilterToPhysical((LogicalFilter)logicalOperator);
            case LogicalOperatorType.LOGICAL_PROJECTION:
                return MapLogicalProjectionToPhysical((LogicalProjection)logicalOperator);
            case LogicalOperatorType.LOGICAL_EXTEND:
                return MapLogicalTraverseRelToPhysical((LogicalTraverseRel)logicalOperator);
            case LogicalOperatorType.LOGICAL_HASH_JOIN:
                return MapLogicalHashJoinToPhysical((LogicalValueJoin)logicalOperator);
            case LogicalOperatorType.LOGICAL_CROSS_PRODUCT:
                return MapLogicalCrossProductToPhysical((LogicalNestedLoopJoin)logicalOperator);
            case LogicalOperatorType.LOGICAL_OPTIONAL_JOIN:
                return MapLogicalOptionalJoinToPhysical((LogicalOptionalJoin)logicalOperator);
            case LogicalOperatorType.LOGICAL_RECURSIVE_EXTEND:
                return MapLogicalRecursiveExtendToPhysical((LogicalRecursiveExtend)logicalOperator);
            case LogicalOperatorType.LOGICAL_COPY_FROM:
                return MapLogicalCopyFromToPhysical((LogicalCopyFrom)logicalOperator);
            case LogicalOperatorType.LOGICAL_COPY_TO:
                return MapLogicalCopyToToPhysical((LogicalCopyTo)logicalOperator);
            case LogicalOperatorType.LOGICAL_ATTACH_DATABASE:
                return MapLogicalAttachDatabaseToPhysical((LogicalAttachDatabase)logicalOperator);
            case LogicalOperatorType.LOGICAL_EXTENSION:
                return MapLogicalExtensionToPhysical((LogicalExtensionStatement)logicalOperator);
            case LogicalOperatorType.LOGICAL_CREATE_MACRO:
                return MapLogicalCreateMacroToPhysical((LogicalCreateMacro)logicalOperator);
            case LogicalOperatorType.LOGICAL_LIMIT:
                return MapLogicalLimitToPhysical((LogicalLimit)logicalOperator);
            case LogicalOperatorType.LOGICAL_SKIP:
                return MapLogicalSkipToPhysical((LogicalSkip)logicalOperator);
            case LogicalOperatorType.LOGICAL_ORDER_BY:
                return MapLogicalOrderByToPhysical((LogicalOrderBy)logicalOperator);
            case LogicalOperatorType.LOGICAL_TOP_K:
                return MapLogicalTopKToPhysical((Planner.Operator.LogicalTopK)logicalOperator);
            case LogicalOperatorType.LOGICAL_INSERT:
                return MapLogicalInsertToPhysical((LogicalInsert)logicalOperator);
            case LogicalOperatorType.TABLE_FUNCTION_CALL:
                return MapLogicalTableFunctionCallToPhysical((LogicalTableFunctionCall)logicalOperator);
            case LogicalOperatorType.LOGICAL_SET_NODE_PROPERTY:
                return MapLogicalSetNodePropertyToPhysical((LogicalSetNodeProperty)logicalOperator);
            case LogicalOperatorType.LOGICAL_SET_REL_PROPERTY:
                // Mapping rel property sets to the exact same logic flow since dummy mappings are naive dictionaries right now
                return MapLogicalSetRelPropertyToPhysical((LogicalSetRelProperty)logicalOperator);
            case LogicalOperatorType.LOGICAL_MERGE_NODE:
                return MapLogicalMergeNodeToPhysical((LogicalMergeNode)logicalOperator);
            case LogicalOperatorType.LOGICAL_MERGE_REL:
                return MapLogicalMergeRelToPhysical((LogicalMergeRel)logicalOperator);
            case LogicalOperatorType.LOGICAL_MERGE_GRAPH:
                return MapLogicalMergeGraphToPhysical((LogicalMergeGraph)logicalOperator);
            case LogicalOperatorType.LOGICAL_DELETE_NODE:
                return MapLogicalDeleteNodeToPhysical((LogicalDeleteNode)logicalOperator);
            case LogicalOperatorType.LOGICAL_DELETE_REL:
                return MapLogicalDeleteRelToPhysical((LogicalDeleteRel)logicalOperator);
            case LogicalOperatorType.LOGICAL_SINGLE_ROW:
                return new BogDb.Core.Processor.Operator.Scan.SingleRowPhysicalOperator(GetNextOperatorID());
            case LogicalOperatorType.LOGICAL_UNWIND:
                return MapLogicalUnwindToPhysical((LogicalUnwind)logicalOperator);
            case LogicalOperatorType.LOGICAL_AGGREGATE:
                return MapLogicalAggregateToPhysical((LogicalAggregate)logicalOperator);
            case LogicalOperatorType.LOGICAL_DISTINCT:
                return MapLogicalDistinctToPhysical(logicalOperator);
            case LogicalOperatorType.LOGICAL_FLATTEN:
                return MapLogicalFlattenToPhysical(logicalOperator);
            case LogicalOperatorType.LOGICAL_UNION_ALL:
                return MapLogicalUnionAllToPhysical(logicalOperator);
            case LogicalOperatorType.LOGICAL_EXPRESSIONS_SCAN:
                return MapLogicalExpressionsScanToPhysical(logicalOperator);
            case LogicalOperatorType.LOGICAL_ACCUMULATE:
                return MapLogicalAccumulateToPhysical((Planner.Operator.LogicalAccumulate)logicalOperator);
            case LogicalOperatorType.LOGICAL_CREATE_NODE:
                return MapLogicalInsertToPhysical((LogicalInsert)logicalOperator);
            case LogicalOperatorType.LOGICAL_CREATE_REL:
                return MapLogicalInsertToPhysical((LogicalInsert)logicalOperator);
            case LogicalOperatorType.LOGICAL_STANDALONE_CALL:
                return MapLogicalStandaloneCallToPhysical((LogicalStandaloneCall)logicalOperator);
            case LogicalOperatorType.LOGICAL_IN_QUERY_CALL:
                return new BogDb.Core.Processor.Operator.Scan.SingleRowPhysicalOperator(GetNextOperatorID());
            case LogicalOperatorType.LOGICAL_INDEX_SCAN_NODE:
                return MapLogicalIndexScanNodeToPhysical((BogDb.Core.Planner.LogicalIndexScanNode)logicalOperator);
            case LogicalOperatorType.LOGICAL_EXTERNAL_INDEX_SCAN_NODE:
                return MapLogicalExternalIndexScanNodeToPhysical((BogDb.Core.Planner.LogicalExternalIndexScanNode)logicalOperator);
            case LogicalOperatorType.LOGICAL_PROFILE:
                return MapLogicalProfileToPhysical(logicalOperator);
            case LogicalOperatorType.LOGICAL_SEMI_MASKER:
                return MapLogicalSemiMaskerToPhysical((Planner.Operator.Sip.LogicalSemiMasker)logicalOperator);
            case LogicalOperatorType.LOGICAL_SCAN_FRONTIER:
                return MapLogicalScanFrontierToPhysical((Planner.Operator.LogicalScanFrontier)logicalOperator);
            case LogicalOperatorType.LOGICAL_INTERSECT:
                return MapUnsupportedLogicalOperatorToPhysical(logicalOperator); // Placeholder — full intersect planning is a planner-parity item
            case LogicalOperatorType.LOGICAL_MARK_JOIN:
                return MapLogicalMarkJoinToPhysical((Planner.Operator.LogicalMarkJoin)logicalOperator);
            case LogicalOperatorType.LOGICAL_CALL_SUBQUERY:
                return MapLogicalCallSubqueryToPhysical((Planner.Operator.LogicalCallSubquery)logicalOperator);
            default:
                return MapUnsupportedLogicalOperatorToPhysical(logicalOperator);
        }
    }

    private PhysicalOperator MapUnsupportedLogicalOperatorToPhysical(LogicalOperator logicalOperator)
    {
        // Keep execution resilient for logical operators that are declared in the enum
        // but not yet fully mapped in the C# physical layer.
        if (!logicalOperator.HasChild())
        {
            return new NoOpPhysicalOperator(GetNextOperatorID());
        }

        if (logicalOperator.GetNumChildren() == 1)
        {
            return MapOperator(logicalOperator.GetChild(0));
        }

        // Multi-child unsupported operators degrade to a no-op sink to avoid
        // producing incorrect cross-operator semantics silently.
        return new NoOpPhysicalOperator(GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalCopyFromToPhysical(LogicalCopyFrom logicalOperator)
    {
        var tableEntry = _database?.Catalog.GetTableEntry(logicalOperator.TableName);
        var isRelTable = tableEntry is BogDb.Core.Catalog.RelGroupCatalogEntry
                         || (_database != null && _database.RelTables.ContainsKey(logicalOperator.TableName));
        if (isRelTable)
        {
            return new BogDb.Core.Processor.Operator.Persistent.CopyRel(
                logicalOperator.TableName,
                logicalOperator.FilePath,
                logicalOperator.ColumnOrder,
                _database,
                GetNextOperatorID());
        }

        var propertyNames = new System.Collections.Generic.List<string>(logicalOperator.ColumnOrder);
        var propertyTypes = ResolveCopyColumnTypes(tableEntry as CatalogModel.TableCatalogEntry, logicalOperator.ColumnOrder);
        var primaryKeyPropertyName = ResolvePrimaryKeyPropertyName(tableEntry as CatalogModel.NodeTableCatalogEntry);

        return new BogDb.Core.Processor.Operator.Persistent.CopyNode(
            logicalOperator.TableName, 
            logicalOperator.FilePath,
            _database, // We will inject database safely at query execution.
            propertyNames,
            propertyTypes,
            primaryKeyPropertyName,
            GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalAttachDatabaseToPhysical(LogicalAttachDatabase logicalOperator)
        => new PhysicalAttachDatabase(_database, logicalOperator.Statement, GetNextOperatorID());

    private PhysicalOperator MapLogicalExtensionToPhysical(LogicalExtensionStatement logicalOperator)
        => new PhysicalExtensionStatement(_database, logicalOperator.Statement, GetNextOperatorID());

    private PhysicalOperator MapLogicalCreateMacroToPhysical(LogicalCreateMacro logicalOperator)
        => new PhysicalCreateMacro(
            _database,
            logicalOperator.Name,
            logicalOperator.Parameters,
            logicalOperator.BodyExpression,
            GetNextOperatorID());

    private PhysicalOperator MapLogicalStandaloneCallToPhysical(LogicalStandaloneCall logicalOperator)
    {
        var option = _database.ExtensionOptions[logicalOperator.OptionName];
        return new PhysicalStandaloneCall(
            _database,
            logicalOperator.OptionName,
            logicalOperator.OptionValue,
            option.Type,
            GetNextOperatorID());
    }

    private static List<Common.LogicalTypeID> ResolveCopyColumnTypes(
        CatalogModel.TableCatalogEntry? tableEntry,
        IReadOnlyList<string> columnOrder)
    {
        if (tableEntry == null)
            return new List<Common.LogicalTypeID>();

        var typesByName = new Dictionary<string, Common.LogicalTypeID>(StringComparer.OrdinalIgnoreCase);
        foreach (var property in tableEntry.GetProperties())
            typesByName[property.ColumnDef.Name] = property.ColumnDef.Type;

        var types = new List<Common.LogicalTypeID>(columnOrder.Count);
        foreach (var column in columnOrder)
        {
            if (typesByName.TryGetValue(column, out var type))
                types.Add(type);
            else
                types.Add(Common.LogicalTypeID.STRING);
        }

        return types;
    }

    private static string ResolvePrimaryKeyPropertyName(CatalogModel.NodeTableCatalogEntry? entry)
    {
        if (entry == null)
            return "id";

        foreach (var property in entry.GetProperties())
        {
            if (entry.GetPropertyID(property.ColumnDef.Name) == entry.PrimaryKeyPropertyID)
                return property.ColumnDef.Name;
        }

        return "id";
    }

    private PhysicalOperator MapLogicalCopyToToPhysical(LogicalCopyTo logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new BogDb.Core.Processor.Operator.Persistent.CopyTo(
            logicalOperator.FilePath,
            logicalOperator.ColumnNames,
            _database,
            child,
            GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalScanNodeToPhysical(LogicalScanNodeProperty logicalOperator)
    {
        return new ScanNodeProperty(
            _database,
            logicalOperator.TableName,
            logicalOperator.Node.VariableName,
            logicalOperator.InlineProperties,
            logicalOperator.InlinePropertyBag,
            logicalOperator.PushedPredicate,
            GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalIndexScanNodeToPhysical(BogDb.Core.Planner.LogicalIndexScanNode logicalOperator)
    {
        return new BogDb.Core.Processor.Operator.Scan.PhysicalIndexScanNode(
            _database,
            logicalOperator.TableName,
            logicalOperator.PropertyName,
            logicalOperator.LookupKey,
            logicalOperator.VariableName,
            GetNextOperatorID(),
            logicalOperator.IsPrefixScan);
    }

    private PhysicalOperator MapLogicalExternalIndexScanNodeToPhysical(BogDb.Core.Planner.LogicalExternalIndexScanNode logicalOperator)
    {
        return new BogDb.Core.Processor.Operator.Scan.PhysicalExternalIndexScanNode(
            _database,
            logicalOperator.Lookup,
            logicalOperator.VariableName,
            GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalFilterToPhysical(LogicalFilter logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new PhysicalFilter(logicalOperator.Predicate, child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalProjectionToPhysical(LogicalProjection logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new PhysicalProjection(logicalOperator.ProjectionItems, child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalTraverseRelToPhysical(LogicalTraverseRel logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new ExpandRel(_database, logicalOperator.QueryRel, child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalRecursiveExtendToPhysical(LogicalRecursiveExtend logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new RecursiveExtend(
            _database,
            logicalOperator.QueryRel,
            logicalOperator.LowerBound,
            logicalOperator.UpperBound,
            logicalOperator.EarlyStopLimit,
            child,
            GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalTableFunctionCallToPhysical(LogicalTableFunctionCall logicalOperator)
    {
        PhysicalOperator? child = null;
        if (logicalOperator.HasChild())
        {
            var logicalChild = logicalOperator.GetChild(0);
            child = logicalChild != null ? MapOperator(logicalChild) : null;
        }
        return new PhysicalTableFunctionCall(
            logicalOperator.FunctionExpression,
            logicalOperator.OutVariables,
            child,
            GetNextOperatorID(),
            _database?.FunctionRegistry,
            _database?.StandaloneTableFunctionRegistry);
    }

    private PhysicalOperator MapLogicalInsertToPhysical(LogicalInsert logicalOperator)
    {
        PhysicalOperator? child = logicalOperator.HasChild() ? MapOperator(logicalOperator.GetChild(0)) : null;
        return new PhysicalInsert(_database, logicalOperator.CreateNodes, logicalOperator.CreateRels, child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalSetNodePropertyToPhysical(LogicalSetNodeProperty logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new PhysicalSetNodeProperty(_database, logicalOperator.SetItems, child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalSetRelPropertyToPhysical(LogicalSetRelProperty logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new PhysicalSetRelProperty(_database, logicalOperator.SetItems, child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalMergeNodeToPhysical(LogicalMergeNode logicalOperator)
    {
        PhysicalOperator? child = logicalOperator.HasChild() ? MapOperator(logicalOperator.GetChild(0)) : null;
        return new PhysicalMergeNode(_database, logicalOperator.MergeNode, logicalOperator.Actions, child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalMergeRelToPhysical(LogicalMergeRel logicalOperator)
    {
        PhysicalOperator? child = logicalOperator.HasChild() ? MapOperator(logicalOperator.GetChild(0)) : null;
        return new PhysicalMergeRel(_database, logicalOperator.MergeRel, logicalOperator.Actions, child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalMergeGraphToPhysical(LogicalMergeGraph logicalOperator)
    {
        PhysicalOperator? child = logicalOperator.HasChild() ? MapOperator(logicalOperator.GetChild(0)) : null;
        return new PhysicalMergeGraph(_database, logicalOperator.MergeGraph, logicalOperator.Actions, child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalDeleteNodeToPhysical(LogicalDeleteNode logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new PhysicalDeleteNode(_database, logicalOperator.DeleteNodes, child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalDeleteRelToPhysical(LogicalDeleteRel logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new PhysicalDeleteRel(_database, logicalOperator.DeleteRels, child, GetNextOperatorID());
    }


    private PhysicalOperator MapLogicalCrossProductToPhysical(LogicalNestedLoopJoin logicalOperator)
    {
        var left = MapOperator(logicalOperator.GetChild(0));
        var right = MapOperator(logicalOperator.GetChild(1));
        return new CrossProduct(left, right, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalOptionalJoinToPhysical(LogicalOptionalJoin logicalOperator)
    {
        var left = MapOperator(logicalOperator.GetChild(0));
        var right = MapOperator(logicalOperator.GetChild(1));
        return new OptionalJoin(left, right, logicalOperator.SharedVariables, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalHashJoinToPhysical(LogicalValueJoin logicalOperator)
    {
        var left = MapOperator(logicalOperator.GetChild(0));
        var right = MapOperator(logicalOperator.GetChild(1));
        return new ValueHashJoin(left, right, logicalOperator.SharedVariables, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalLimitToPhysical(LogicalLimit logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new Operator.Limit.Limit(child, logicalOperator.LimitExpression, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalSkipToPhysical(LogicalSkip logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new Operator.Limit.Skip(child, logicalOperator.SkipExpression, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalOrderByToPhysical(LogicalOrderBy logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new Operator.OrderBy.OrderBy(child, logicalOperator.Expressions, logicalOperator.IsAscending, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalTopKToPhysical(Planner.Operator.LogicalTopK logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new Operator.TopK.PhysicalTopK(
            child,
            logicalOperator.Expressions,
            logicalOperator.IsAscending,
            logicalOperator.LimitExpression,
            GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalUnwindToPhysical(LogicalUnwind logicalOperator)
    {
        PhysicalOperator? child = logicalOperator.HasChild()
            ? MapOperator(logicalOperator.GetChild(0))
            : null;
        return new PhysicalUnwind(
            logicalOperator.CollectionExpression,
            logicalOperator.Alias,
            child,
            GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalAggregateToPhysical(LogicalAggregate logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new PhysicalAggregate(
            logicalOperator.ProjectionItems,
            logicalOperator.KeyItems,
            child,
            GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalDistinctToPhysical(LogicalOperator logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new PhysicalDistinct(child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalFlattenToPhysical(LogicalOperator logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new PhysicalFlatten(child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalUnionAllToPhysical(LogicalOperator logicalOperator)
    {
        var left  = MapOperator(logicalOperator.GetChild(0));
        var right = MapOperator(logicalOperator.GetChild(1));
        return new PhysicalUnionAll(left, right, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalExpressionsScanToPhysical(LogicalOperator logicalOperator)
    {
        return new PhysicalExpressionsScan(
            ((LogicalExpressionsScan)logicalOperator).Expressions,
            GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalAccumulateToPhysical(Planner.Operator.LogicalAccumulate logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new PhysicalAccumulate(logicalOperator.AccumulateType, child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalProfileToPhysical(LogicalOperator logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new PhysicalProfile(child, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalSemiMaskerToPhysical(Planner.Operator.Sip.LogicalSemiMasker logicalOperator)
    {
        var child = MapOperator(logicalOperator.GetChild(0));
        return new PhysicalSemiMasker(
            logicalOperator.KeyType,
            logicalOperator.TargetType,
            logicalOperator.Key,
            logicalOperator.NodeTableIds,
            child,
            logicalOperator.ExtraKeyInfo,
            GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalScanFrontierToPhysical(Planner.Operator.LogicalScanFrontier logicalOperator)
    {
        var frontier = logicalOperator.Frontier ?? new GraphDataScience.GdsFrontier();
        return new BogDb.Core.Processor.Operator.Scan.PhysicalScanFrontier(
            _database,
            logicalOperator.TableNames,
            logicalOperator.VariableName,
            frontier,
            GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalMarkJoinToPhysical(Planner.Operator.LogicalMarkJoin logicalOperator)
    {
        var probe = MapOperator(logicalOperator.GetChild(0));
        var build = MapOperator(logicalOperator.GetChild(1));
        return new MarkJoin(probe, build, logicalOperator.SharedVariables, logicalOperator.MarkVariableName, GetNextOperatorID());
    }

    private PhysicalOperator MapLogicalCallSubqueryToPhysical(Planner.Operator.LogicalCallSubquery logicalOperator)
    {
        // Map the outer child (the pipeline feeding into CALL)
        var outerPhysical = logicalOperator.HasChild()
            ? MapOperator(logicalOperator.GetChild(0))
            : new Operator.Scan.SingleRowPhysicalOperator(GetNextOperatorID());

        // Map the inner plan (used for non-correlated execution)
        PhysicalOperator innerPhysical;
        if (logicalOperator.InnerPlan != null)
        {
            innerPhysical = MapLogicalPlanToPhysical(logicalOperator.InnerPlan).LastOperator;
        }
        else
        {
            innerPhysical = new NoOpPhysicalOperator(GetNextOperatorID());
        }

        return new PhysicalCallSubquery(
            outerPhysical,
            innerPhysical,
            logicalOperator.CorrelatedVariables,
            logicalOperator.IsCorrelated ? logicalOperator.CorrelatedVarInfos : null,
            logicalOperator.OutputColumnNames,
            logicalOperator.IsCorrelated ? logicalOperator.InnerQueryText : null,
            _database,
            GetNextOperatorID());
    }

    private uint GetNextOperatorID() => _physicalOperatorIdCounter++;
}
