//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (transaction.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogDb.Core.Transaction;

using BogDb.Core.Storage;

public enum TransactionType : byte
{
    READ_ONLY,
    WRITE,
    CHECKPOINT,
    DUMMY,
    RECOVERY
}

/// <summary>
/// BogDb.Core Transaction encapsulates MVCC start and commit timestamps 
/// while binding storage logs (WAL) and memory caching.
/// </summary>
public sealed class Transaction 
{
    private readonly HashSet<IVersionedTransactionParticipant> _versionedParticipants = new();

    private sealed class VersionedParticipantUndoPayload : IManagedUndoPayload
    {
        private readonly IVersionedTransactionParticipant _participant;
        private readonly Transaction _tx;

        public VersionedParticipantUndoPayload(
            IVersionedTransactionParticipant participant,
            Transaction tx)
        {
            _participant = participant;
            _tx = tx;
        }

        public void Commit() => _participant.CommitVersionedChanges(_tx, _tx.CommitTS);
        public void Rollback() => _participant.RollbackVersionedChanges(_tx);
    }

    public const ulong DUMMY_TRANSACTION_ID = 0;
    public const ulong DUMMY_START_TIMESTAMP = 0;
    public const ulong START_TRANSACTION_ID = 1UL << 63; // Map to BogDb Bitshifted IDs

    public readonly TransactionType Type;
    public readonly ulong ID;
    public readonly ulong StartTS;
    public ulong CommitTS { get; private set; }
    public long CurrentTS { get; private set; }
    public ulong RecoveryWalOffset { get; private set; }
    public ulong RecoveryGraphLogOffset { get; private set; }

    // Flags
    public bool ForceCheckpoint { get; private set; }

    // MVCC Rollback
    public readonly BogDb.Core.Storage.UndoBuffer UndoBuffer;

    public Transaction(TransactionType transactionType, ulong id, ulong startTS)
    {
        Type = transactionType;
        ID = id;
        StartTS = startTS;
        
        if (ShouldAppendToUndoBuffer())
        {
            UndoBuffer = new BogDb.Core.Storage.UndoBuffer();
        }
    }

    public Transaction(TransactionType transactionType)
    {
        Type = transactionType;
        ID = DUMMY_TRANSACTION_ID;
        StartTS = DUMMY_START_TIMESTAMP;
        
        if (ShouldAppendToUndoBuffer())
        {
            UndoBuffer = new BogDb.Core.Storage.UndoBuffer();
        }
    }

    public bool IsReadOnly() => Type == TransactionType.READ_ONLY;
    public bool IsWriteTransaction() => Type == TransactionType.WRITE;
    public bool IsDummy() => Type == TransactionType.DUMMY;
    public bool IsRecovery() => Type == TransactionType.RECOVERY;

    public bool ShouldAppendToUndoBuffer()
    {
        // Only write transactions and recovery transactions should append to the undo buffer.
        return IsWriteTransaction() || IsRecovery();
    }

    public void TrackVersionedParticipant(IVersionedTransactionParticipant participant)
    {
        if (!ShouldAppendToUndoBuffer())
            return;

        if (!_versionedParticipants.Add(participant))
            return;

        UndoBuffer.RegisterManagedOperation(
            UndoRecordType.UPDATE_INFO,
            new VersionedParticipantUndoPayload(participant, this));
    }

    public void TrackVersionedAction(
        UndoRecordType recordType,
        Action commit,
        Action rollback)
    {
        if (!ShouldAppendToUndoBuffer())
            return;

        UndoBuffer.RegisterManagedOperation(recordType, commit, rollback);
    }

    public void TrackVersionedAction<TPayload>(
        UndoRecordType recordType,
        TPayload payload,
        Action<TPayload> commit,
        Action<TPayload> rollback)
    {
        if (!ShouldAppendToUndoBuffer())
            return;

        UndoBuffer.RegisterManagedOperation(recordType, payload, commit, rollback);
    }

    public void TrackVersionedAction<TPayload>(
        UndoRecordType recordType,
        TPayload payload)
        where TPayload : IManagedUndoPayload
    {
        if (!ShouldAppendToUndoBuffer())
            return;

        UndoBuffer.RegisterManagedOperation(recordType, payload);
    }

    public void TrackVersionedRowAction(
        UndoRecordType recordType,
        IRawUndoReplayTarget target,
        int rowIndex,
        ReadOnlySpan<byte> payload = default)
    {
        if (!ShouldAppendToUndoBuffer())
            return;

        UndoBuffer.RegisterVersionedRowOperation(recordType, target, this, rowIndex, payload);
    }

    public void Commit(ulong commitTS)
    {
        CommitTS = commitTS;
    }

    internal void CaptureRecoveryOffsets(ulong walOffset, ulong graphLogOffset)
    {
        RecoveryWalOffset = walOffset;
        RecoveryGraphLogOffset = graphLogOffset;
    }

    internal void CommitVersionedChanges()
    {
        UndoBuffer?.CommitRawOperations(CommitTS);
        UndoBuffer?.CommitManagedOperations();
        UndoBuffer?.Dispose();
        _versionedParticipants.Clear();
    }

    public void Rollback()
    {
    }

    internal void RollbackVersionedChanges()
    {
        UndoBuffer?.RollbackRawOperations();
        UndoBuffer?.RollbackManagedOperations();
        UndoBuffer?.Dispose();
        _versionedParticipants.Clear();
    }

    public static readonly Transaction DUMMY_TRANSACTION = new Transaction(TransactionType.DUMMY);
    public static readonly Transaction DUMMY_CHECKPOINT_TRANSACTION = new Transaction(TransactionType.CHECKPOINT);
}
