//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (catalog_set.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using BogDb.Core.Transaction;

namespace BogDb.Core.Catalog;

/// <summary>
/// A CatalogSet represents a registry of specific CatalogEntry types (e.g., Tables, Macros).
/// Mapped from BogDb's std::shared_mutex C++ design to .NET ReaderWriterLockSlim 
/// to manage safe MVCC concurrent Schema alterations.
/// </summary>
public sealed class CatalogSet : IDisposable
{
    // To ensure uniqueness of internal OIDs, start internal catalogs at 2^63
    public const ulong INTERNAL_CATALOG_SET_START_OID = 1UL << 63;

    private readonly ReaderWriterLockSlim _lock;
    private readonly bool _isInternal;
    private ulong _nextOID;

    // Use ordinal ignore case mapping matching BogDb's case_insensitive_map_t
    private readonly Dictionary<string, CatalogEntry> _entries;

    public CatalogSet(bool isInternal = false)
    {
        _lock = new ReaderWriterLockSlim(LockRecursionPolicy.NoRecursion);
        _isInternal = isInternal;
        _nextOID = _isInternal ? INTERNAL_CATALOG_SET_START_OID : 0;
        _entries = new Dictionary<string, CatalogEntry>(StringComparer.OrdinalIgnoreCase);
    }

    public ulong GetNextOID()
    {
        _lock.EnterWriteLock();
        try
        {
            return _nextOID++;
        }
        finally
        {
            _lock.ExitWriteLock();
        }
    }

    public bool ContainsEntry(Transaction.Transaction? transaction, string name)
    {
        _lock.EnterReadLock();
        try
        {
            if (!_entries.TryGetValue(name, out var entry))
                return false;

            var visibleEntry = GetCommittedEntryNoLock(entry);
            return visibleEntry != null && !visibleEntry.IsDeleted;
        }
        finally
        {
            _lock.ExitReadLock();
        }
    }

    public CatalogEntry? GetEntry(Transaction.Transaction? transaction, string name)
    {
        _lock.EnterReadLock();
        try
        {
            if (!_entries.TryGetValue(name, out var entry))
                return null;

            var visibleEntry = GetCommittedEntryNoLock(entry);
            if (visibleEntry == null || visibleEntry.IsDeleted)
                return null;
                
            return visibleEntry;
        }
        finally
        {
            _lock.ExitReadLock();
        }
    }

    public IEnumerable<CatalogEntry> GetEntries()
    {
        _lock.EnterReadLock();
        try
        {
            var results = new List<CatalogEntry>();
            foreach (var kvp in _entries)
            {
                var visible = GetCommittedEntryNoLock(kvp.Value);
                if (visible != null && !visible.IsDeleted)
                {
                    results.Add(visible);
                }
            }
            return results;
        }
        finally
        {
            _lock.ExitReadLock();
        }
    }

    public ulong CreateEntry(Transaction.Transaction transaction, CatalogEntry entry)
    {
        _lock.EnterWriteLock();
        try
        {
            if (_entries.TryGetValue(entry.Name, out var existing))
            {
                var visible = GetCommittedEntryNoLock(existing);
                if (visible != null && !visible.IsDeleted)
                {
                    throw new InvalidOperationException($"Catalog entry {entry.Name} already exists.");
                }
            }

            ulong oid = _nextOID++;
            entry.SetOID(oid);
            entry.SetTimestamp(transaction.ID); 
            
            // In a full MVCC implementation, we would prepend this to the version chain.
            // For now, we update the master pointer to the new entry.
            _entries[entry.Name] = entry;
            
            return oid;
        }
        finally
        {
            _lock.ExitWriteLock();
        }
    }

    public void DropEntry(Transaction.Transaction transaction, string name)
    {
        _lock.EnterWriteLock();
        try
        {
            if (_entries.TryGetValue(name, out var entry))
            {
                // Soft delete by mapping the transaction timestamp
                entry.SetDeleted(true);
                entry.SetTimestamp(transaction.ID);
            }
            else
            {
                throw new KeyNotFoundException($"Catalog entry {name} does not exist.");
            }
        }
        finally
        {
            _lock.ExitWriteLock();
        }
    }

    public void RenameEntry(Transaction.Transaction transaction, string name, string newName)
    {
        _lock.EnterWriteLock();
        try
        {
            if (!_entries.TryGetValue(name, out var entry))
                throw new KeyNotFoundException($"Catalog entry {name} does not exist.");

            if (_entries.TryGetValue(newName, out var existing))
            {
                var visible = GetCommittedEntryNoLock(existing);
                if (visible != null && !visible.IsDeleted)
                    throw new InvalidOperationException($"Catalog entry {newName} already exists.");
            }

            _entries.Remove(name);
            entry.Rename(newName);
            _entries[newName] = entry;
        }
        finally
        {
            _lock.ExitWriteLock();
        }
    }

    /// <summary>
    /// Evaluates BogDb MVCC rules: return the most recent committed version.
    /// In a fully realized system, this walks the `Prev` pointer chain.
    /// </summary>
    private CatalogEntry? GetCommittedEntryNoLock(CatalogEntry entry)
    {
        var current = entry;
        while (current != null)
        {
            // For Phase 3, we simply return the node assuming single-thread commits.
            // Full MVCC visibility checks transaction IDs vs StartTS.
            return current;
        }
        return null;
    }

    public void Serialize(BinaryWriter writer)
    {
        _lock.EnterReadLock();
        try
        {
            writer.Write(_nextOID);
            
            // First count the valid entries
            int validCount = 0;
            foreach (var kvp in _entries)
            {
                var visible = GetCommittedEntryNoLock(kvp.Value);
                if (visible != null && !visible.IsDeleted)
                {
                    validCount++;
                }
            }
            
            writer.Write(validCount);
            
            foreach (var kvp in _entries)
            {
                // Filter out deleted nodes from serialization 
                var visible = GetCommittedEntryNoLock(kvp.Value);
                if (visible != null && !visible.IsDeleted)
                {
                    visible.Serialize(writer);
                }
            }
        }
        finally
        {
            _lock.ExitReadLock();
        }
    }

    public void Deserialize(BinaryReader reader)
    {
        _lock.EnterWriteLock();
        try
        {
            _entries.Clear();
            _nextOID = reader.ReadUInt64();
            int count = reader.ReadInt32();
            for (int i = 0; i < count; i++)
            {
                var entry = CatalogEntry.Deserialize(reader);
                _entries[entry.Name] = entry;
            }
        }
        finally
        {
            _lock.ExitWriteLock();
        }
    }

    public void Dispose()
    {
        _lock.Dispose();
    }
}
