//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (catalog.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.IO;
using BogDb.Core.Common;
using BogDb.Core.Transaction;

namespace BogDb.Core.Catalog;

/// <summary>
/// The Master Catalog tracks the entire database schema divided into specialized CatalogSets.
/// Enables querying for Tables, Macros, Functions, and Sequences securely across transactions.
/// </summary>
public sealed class Catalog : IDisposable
{
    private readonly CatalogSet _tables;
    private readonly CatalogSet _sequences;
    private readonly CatalogSet _functions;
    private readonly CatalogSet _types;
    private readonly CatalogSet _indexes;
    private readonly CatalogSet _macros;
    
    // Internal mappings for system tables holding schema data
    private readonly CatalogSet _internalTables;
    private readonly CatalogSet _internalSequences;
    private readonly CatalogSet _internalFunctions;

    // Incremented whenever a change is made to the catalog. Reset to 0 at the end of each checkpoint.
    private ulong _version;

    public Catalog()
    {
        _tables = new CatalogSet(isInternal: false);
        _sequences = new CatalogSet(isInternal: false);
        _functions = new CatalogSet(isInternal: false);
        _types = new CatalogSet(isInternal: false);
        _indexes = new CatalogSet(isInternal: false);
        _macros = new CatalogSet(isInternal: false);

        _internalTables = new CatalogSet(isInternal: true);
        _internalSequences = new CatalogSet(isInternal: true);
        _internalFunctions = new CatalogSet(isInternal: true);

        _version = 0;
    }

    public ulong Version => _version;
    public void IncrementVersion() => _version++;
    public void ResetVersion() => _version = 0;
    public bool ChangedSinceLastCheckpoint() => _version != 0;

    //-------------------------------------------------------------------------
    // Tables
    //-------------------------------------------------------------------------

    public bool ContainsTable(Transaction.Transaction? transaction, string tableName, bool useInternal = true)
    {
        return _tables.ContainsEntry(transaction, tableName) || 
               (useInternal && _internalTables.ContainsEntry(transaction, tableName));
    }

    public TableCatalogEntry? GetTableCatalogEntry(Transaction.Transaction? transaction, string tableName, bool useInternal = true)
    {
        var entry = _tables.GetEntry(transaction, tableName) as TableCatalogEntry;
        if (entry == null && useInternal)
        {
            entry = _internalTables.GetEntry(transaction, tableName) as TableCatalogEntry;
        }
        return entry;
    }

    /// <summary>
    /// Convenience overload for use in schema resolution contexts (e.g., Binder) 
    /// where no active Transaction context is available.
    /// </summary>
    public TableCatalogEntry? GetTableEntry(string tableName)
        => GetTableCatalogEntry(null, tableName);

    public TableCatalogEntry? GetTableCatalogEntryByOID(ulong tableId, bool useInternal = true)
    {
        foreach (var entry in _tables.GetEntries())
        {
            if (entry is TableCatalogEntry tableEntry && tableEntry.TableID == tableId)
                return tableEntry;
        }

        if (!useInternal)
            return null;

        foreach (var entry in _internalTables.GetEntries())
        {
            if (entry is TableCatalogEntry tableEntry && tableEntry.TableID == tableId)
                return tableEntry;
        }

        return null;
    }

    public IEnumerable<TableCatalogEntry> GetNodeTableEntries()
    {
        foreach (var entry in _tables.GetEntries())
        {
            if (entry is NodeTableCatalogEntry nodeEntry)
                yield return nodeEntry;
        }
    }

    public IEnumerable<TableCatalogEntry> GetRelTableEntries()
    {
        foreach (var entry in _tables.GetEntries())
        {
            if (entry is RelGroupCatalogEntry relEntry)
                yield return relEntry;
        }
    }

    public bool ContainsMacro(Transaction.Transaction? transaction, string macroName)
        => _macros.ContainsEntry(transaction, macroName);

    public ScalarMacroCatalogEntry? GetScalarMacroCatalogEntry(Transaction.Transaction? transaction, string macroName)
        => _macros.GetEntry(transaction, macroName) as ScalarMacroCatalogEntry;

    public ulong CreateScalarMacroEntry(Transaction.Transaction transaction, ScalarMacroCatalogEntry entry)
    {
        var oid = _macros.CreateEntry(transaction, entry);
        IncrementVersion();
        return oid;
    }

    public IEnumerable<ScalarMacroCatalogEntry> GetMacroEntries()
    {
        foreach (var entry in _macros.GetEntries())
        {
            if (entry is ScalarMacroCatalogEntry macroEntry)
                yield return macroEntry;
        }
    }

    public IEnumerable<CatalogEntry> GetSequenceEntries()
        => _sequences.GetEntries();

    public bool ContainsIndexEntry(string tableName, string propertyName)
        => FindIndexEntry(null, tableName, propertyName) is not null;

    public void CreateIndexEntry(
        string tableName,
        string propertyName,
        string indexTypeName = "HASH",
        LogicalTypeID? propertyType = null)
    {
        if (FindIndexEntry(null, tableName, propertyName) is not null)
            return;

        _indexes.CreateEntry(
            new Transaction.Transaction(TransactionType.WRITE),
            new IndexCatalogEntry(tableName, propertyName, indexTypeName, propertyType));
        IncrementVersion();
    }

    public void DropIndexEntry(Transaction.Transaction transaction, string tableName, string propertyName)
    {
        var entry = FindIndexEntry(transaction, tableName, propertyName);
        if (entry is null)
            return;

        _indexes.DropEntry(transaction, entry.Name);
        IncrementVersion();
    }

    public IEnumerable<IndexCatalogEntry> GetIndexEntries()
    {
        foreach (var entry in _indexes.GetEntries())
        {
            if (entry is IndexCatalogEntry indexEntry)
                yield return indexEntry;
        }
    }

    public void DropIndexEntriesForTable(Transaction.Transaction transaction, string tableName)
    {
        var indexEntryNames = new List<string>();
        foreach (var indexEntry in GetIndexEntries())
        {
            if (!string.Equals(indexEntry.TableName, tableName, StringComparison.OrdinalIgnoreCase))
                continue;

            indexEntryNames.Add(indexEntry.Name);
        }

        foreach (var entryName in indexEntryNames)
        {
            if (_indexes.ContainsEntry(transaction, entryName))
                _indexes.DropEntry(transaction, entryName);
        }

        if (indexEntryNames.Count > 0)
            IncrementVersion();
    }

    public ulong CreateTableEntry(Transaction.Transaction transaction, TableCatalogEntry entry, bool isInternal = false)
    {
        var targetSet = isInternal ? _internalTables : _tables;
        ulong oid = targetSet.CreateEntry(transaction, entry);
        IncrementVersion();
        return oid;
    }

    public void DropTableEntry(Transaction.Transaction transaction, string name)
    {
        if (_tables.ContainsEntry(transaction, name))
        {
            _tables.DropEntry(transaction, name);
        }
        else if (_internalTables.ContainsEntry(transaction, name))
        {
            _internalTables.DropEntry(transaction, name);
        }
        else
        {
            throw new KeyNotFoundException($"Table {name} not found.");
        }
        
        IncrementVersion();
    }

    public void RenameTableEntry(Transaction.Transaction transaction, string name, string newName)
    {
        if (_tables.ContainsEntry(transaction, name))
        {
            _tables.RenameEntry(transaction, name, newName);
        }
        else if (_internalTables.ContainsEntry(transaction, name))
        {
            _internalTables.RenameEntry(transaction, name, newName);
        }
        else
        {
            throw new KeyNotFoundException($"Table {name} not found.");
        }

        IncrementVersion();
    }

    public void RenameIndexEntriesForTable(Transaction.Transaction transaction, string tableName, string newTableName)
    {
        var propertyNames = new List<string>();
        foreach (var indexEntry in GetIndexEntries())
        {
            if (!string.Equals(indexEntry.TableName, tableName, StringComparison.OrdinalIgnoreCase))
                continue;
            propertyNames.Add(indexEntry.PropertyName);
        }

        foreach (var propertyName in propertyNames)
            RenameIndexEntry(transaction, tableName, propertyName, newTableName, propertyName);
    }

    public void RenameIndexEntry(
        Transaction.Transaction transaction,
        string tableName,
        string propertyName,
        string newTableName,
        string newPropertyName)
    {
        var entry = FindIndexEntry(transaction, tableName, propertyName);
        if (entry is null)
            return;

        var newEntryName = IndexCatalogEntry.EncodeName(
            newTableName,
            newPropertyName,
            entry.IndexTypeName,
            entry.PropertyType);
        _indexes.RenameEntry(transaction, entry.Name, newEntryName);
        IncrementVersion();
    }

    private IndexCatalogEntry? FindIndexEntry(
        Transaction.Transaction? transaction,
        string tableName,
        string propertyName)
    {
        foreach (var entry in _indexes.GetEntries())
        {
            if (entry is not IndexCatalogEntry indexEntry)
                continue;
            if (!string.Equals(indexEntry.TableName, tableName, StringComparison.OrdinalIgnoreCase))
                continue;
            if (!string.Equals(indexEntry.PropertyName, propertyName, StringComparison.OrdinalIgnoreCase))
                continue;
            return indexEntry;
        }

        return null;
    }

    //-------------------------------------------------------------------------
    // Serialization
    //-------------------------------------------------------------------------

    public void Serialize(BinaryWriter writer)
    {
        writer.Write(_version);
        _tables.Serialize(writer);
        _sequences.Serialize(writer);
        _functions.Serialize(writer);
        _types.Serialize(writer);
        _indexes.Serialize(writer);
        _macros.Serialize(writer);
        
        // Internal datasets are generally generated at runtime, 
        // however BogDb natively serializes them based on internal checkpoints.
        _internalTables.Serialize(writer);
    }

    public static Catalog Deserialize(BinaryReader reader)
    {
        var catalog = new Catalog();
        // Since we instantianted new CatalogSets in the constructor, we can overwrite them:
        catalog._version = reader.ReadUInt64();
        
        // Re-deserialize into the existing CatalogSets
        catalog._tables.Deserialize(reader);
        catalog._sequences.Deserialize(reader);
        catalog._functions.Deserialize(reader);
        catalog._types.Deserialize(reader);
        catalog._indexes.Deserialize(reader);
        catalog._macros.Deserialize(reader);
        
        catalog._internalTables.Deserialize(reader);

        return catalog;
    }

    public void Dispose()
    {
        _tables.Dispose();
        _sequences.Dispose();
        _functions.Dispose();
        _types.Dispose();
        _indexes.Dispose();
        _macros.Dispose();
        _internalTables.Dispose();
        _internalSequences.Dispose();
        _internalFunctions.Dispose();
    }
}
