//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (catalog_entry.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;

namespace BogDb.Core.Catalog;

/// <summary>
/// CatalogEntry is the base class for all metadata entries in BogDB's Catalog.
/// It tracks the OID (Object ID), Timestamp bounds for MVCC handling, 
/// and supports linked-list navigation through earlier versions.
/// </summary>
public abstract class CatalogEntry
{
    public const ulong INVALID_OID = ulong.MaxValue;

    public CatalogEntryType Type { get; protected set; }
    public string Name { get; protected set; }
    public ulong OID { get; protected set; }
    public ulong Timestamp { get; protected set; }
    
    public bool IsDeleted { get; protected set; }
    public bool HasParent { get; protected set; }

    // Version tracking (Linked List spanning back through uncommitted memory logs)
    public CatalogEntry? Prev { get; protected set; }
    public CatalogEntry? Next { get; protected set; }

    protected CatalogEntry(CatalogEntryType type, string name)
    {
        Type = type;
        Name = name;
        OID = INVALID_OID;
        // Map to BogDb's common::INVALID_TRANSACTION
        Timestamp = ulong.MaxValue;
        IsDeleted = false;
        HasParent = false;
    }

    public virtual void Rename(string newName)
    {
        Name = newName;
    }

    public void SetOID(ulong oid)
    {
        OID = oid;
    }

    public void SetTimestamp(ulong timestamp)
    {
        Timestamp = timestamp;
    }

    public void SetDeleted(bool deleted)
    {
        IsDeleted = deleted;
    }

    public void SetHasParent(bool hasParent)
    {
        HasParent = hasParent;
    }

    public void SetPrev(CatalogEntry? prev)
    {
        Prev = prev;
        if (Prev != null)
        {
            Prev.Next = this;
        }
    }

    // Abstract methods handling disk persistence 
    // Uses BinaryWriter/BinaryReader passing through to WAL logs natively.
    public abstract void Serialize(BinaryWriter writer);

    /// <summary>
    /// Base Serialization logic reads the Type prefix to invoke the specific subclass constructor.
    /// </summary>
    public static CatalogEntry Deserialize(BinaryReader reader)
    {
        var type = (CatalogEntryType)reader.ReadByte();
        
        switch (type)
        {
            case CatalogEntryType.NODE_TABLE_ENTRY:
                return NodeTableCatalogEntry.Deserialize(reader);
            case CatalogEntryType.REL_GROUP_ENTRY:
                return RelGroupCatalogEntry.Deserialize(reader);
            case CatalogEntryType.FOREIGN_TABLE_ENTRY:
                return ForeignTableCatalogEntry.Deserialize(reader);
            case CatalogEntryType.SCALAR_MACRO_ENTRY:
                return ScalarMacroCatalogEntry.Deserialize(reader);
            case CatalogEntryType.AGGREGATE_FUNCTION_ENTRY:
            case CatalogEntryType.SCALAR_FUNCTION_ENTRY:
            case CatalogEntryType.REWRITE_FUNCTION_ENTRY:
            case CatalogEntryType.TABLE_FUNCTION_ENTRY:
            case CatalogEntryType.COPY_FUNCTION_ENTRY:
            case CatalogEntryType.STANDALONE_TABLE_FUNCTION_ENTRY:
            case CatalogEntryType.SEQUENCE_ENTRY:
            case CatalogEntryType.TYPE_ENTRY:
            case CatalogEntryType.DUMMY_ENTRY:
                return GenericCatalogEntry.Deserialize(type, reader);
            case CatalogEntryType.INDEX_ENTRY:
                return IndexCatalogEntry.Deserialize(reader);
            // BogDb natively supports hundreds of Table and Function types.
            // We route the specific execution context to the subclass constructors.
            default:
                throw new InvalidDataException($"Unknown catalog entry type byte value: {(byte)type} ({type}).");
        }
    }
}
