//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (catalog_entry_type.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogDb.Core.Catalog;

public enum CatalogEntryType : byte
{
    // Table entries
    NODE_TABLE_ENTRY = 0,
    REL_GROUP_ENTRY = 2,
    FOREIGN_TABLE_ENTRY = 4,

    // Macro entries
    SCALAR_MACRO_ENTRY = 10,

    // Function entries
    AGGREGATE_FUNCTION_ENTRY = 20,
    SCALAR_FUNCTION_ENTRY = 21,
    REWRITE_FUNCTION_ENTRY = 22,
    TABLE_FUNCTION_ENTRY = 23,
    COPY_FUNCTION_ENTRY = 25,
    STANDALONE_TABLE_FUNCTION_ENTRY = 26,

    // Sequence entries
    SEQUENCE_ENTRY = 40,

    // UDT entries
    TYPE_ENTRY = 41,

    // Index entries
    INDEX_ENTRY = 42,

    // Dummy entry
    DUMMY_ENTRY = 100
}
