//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (node_table_catalog_entry.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Common;

namespace BogDb.Core.Catalog;

public sealed class NodeTableCatalogEntry : TableCatalogEntry
{
    public uint PrimaryKeyPropertyID { get; private set; }

    public NodeTableCatalogEntry(string name, uint primaryKeyPropertyID) 
        : base(CatalogEntryType.NODE_TABLE_ENTRY, name)
    {
        PrimaryKeyPropertyID = primaryKeyPropertyID;
    }

    public override TableType GetTableType()
    {
        return TableType.NODE;
    }

    public override TableCatalogEntry Copy()
    {
        var copy = new NodeTableCatalogEntry(Name, PrimaryKeyPropertyID);
        copy.SetOID(OID);
        copy.SetTimestamp(Timestamp);
        copy.SetDeleted(IsDeleted);
        copy.SetHasParent(HasParent);
        copy.SetComment(_comment);
        foreach (var property in GetProperties())
        {
            copy.AddProperty(new PropertyDefinition(
                new ColumnDefinition(property.ColumnDef.Name, property.ColumnDef.Type, property.ColumnDef.DeclaredType),
                property.DefaultExpressionName));
        }
        return copy;
    }

    public override void Serialize(System.IO.BinaryWriter writer)
    {
        base.Serialize(writer);
        writer.Write(PrimaryKeyPropertyID);
    }

    public new static NodeTableCatalogEntry Deserialize(System.IO.BinaryReader reader)
    {
        // 1. Base Class Fields (written in TableCatalogEntry.Serialize after the Type byte)
        string name = reader.ReadString();
        ulong oid = reader.ReadUInt64();
        ulong timestamp = reader.ReadUInt64();
        bool isDeleted = reader.ReadBoolean();
        bool hasParent = reader.ReadBoolean();
        string comment = reader.ReadString();
        int numProperties = reader.ReadInt32();

        var entry = new NodeTableCatalogEntry(name, 0);
        entry.SetOID(oid);
        entry.SetTimestamp(timestamp);
        entry.SetDeleted(isDeleted);
        entry.SetHasParent(hasParent);
        entry.SetComment(comment);
        DeserializeProperties(reader, entry, numProperties);
        
        // 2. NodeTable specifics
        entry.PrimaryKeyPropertyID = reader.ReadUInt32();
        
        return entry;
    }
}
