//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (property_definition_collection.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace BogDb.Core.Catalog;

/// <summary>
/// Collection tracking multiple column PropertyDefinitions for a Catalog Table.
/// </summary>
public class PropertyDefinitionCollection
{
    private uint _nextColumnID;
    private uint _nextPropertyID;
    
    private readonly Dictionary<uint, PropertyDefinition> _definitions;
    private readonly Dictionary<uint, uint> _columnIDs; // Mapping PropertyID -> ColumnID
    private readonly Dictionary<string, uint> _nameToPropertyIDMap; // Case insensitive map

    public PropertyDefinitionCollection(uint nextColumnID = 0)
    {
        _nextColumnID = nextColumnID;
        _nextPropertyID = 0;
        
        _definitions = new Dictionary<uint, PropertyDefinition>();
        _columnIDs = new Dictionary<uint, uint>();
        _nameToPropertyIDMap = new Dictionary<string, uint>(StringComparer.OrdinalIgnoreCase);
    }

    public int Size => _definitions.Count;

    public bool Contains(string name) => _nameToPropertyIDMap.ContainsKey(name);

    public PropertyDefinition GetDefinition(string name)
    {
        if (_nameToPropertyIDMap.TryGetValue(name, out var propertyID))
        {
            return _definitions[propertyID];
        }
        throw new KeyNotFoundException($"Property {name} not found");
    }
    
    public PropertyDefinition GetDefinition(uint propertyID)
    {
        return _definitions[propertyID];
    }

    public uint GetColumnID(string name)
    {
        return _columnIDs[_nameToPropertyIDMap[name]];
    }

    public uint GetPropertyID(string name)
    {
        return _nameToPropertyIDMap[name];
    }

    public IEnumerable<PropertyDefinition> GetAllDefinitions()
        => _definitions.Values;

    public void Add(PropertyDefinition definition)
    {
        _definitions[_nextPropertyID] = definition;
        _columnIDs[_nextPropertyID] = _nextColumnID;
        _nameToPropertyIDMap[definition.Name] = _nextPropertyID;
        
        _nextColumnID++;
        _nextPropertyID++;
    }

    public void Rename(string name, string newName)
    {
        var propertyID = _nameToPropertyIDMap[name];
        _nameToPropertyIDMap.Remove(name);
        
        _definitions[propertyID].Rename(newName);
        _nameToPropertyIDMap[newName] = propertyID;
    }

    public void Drop(string name)
    {
        var propertyID = _nameToPropertyIDMap[name];
        _nameToPropertyIDMap.Remove(name);
        _definitions.Remove(propertyID);
        // We preserve column IDs and property IDs to prevent compaction races 
        // Note: C++ uses vacuumColumnIDs to crunch them back later
    }
}
