//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (property_definition.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Common;

namespace BogDb.Core.Catalog;

/// <summary>
/// A Column Definition represents a table column layout pairing a String Name 
/// with a LogicalType representation.
/// </summary>
public class ColumnDefinition
{
    public string Name { get; set; }
    
    // Using LogicalTypeID as the unmanaged bridge representations instead of the full LogicalType wrapper class for primitive schema parsing 
    public LogicalTypeID Type { get; set; }
    public string DeclaredType { get; set; }
    public DeclaredTypeDescriptor TypeDescriptor => DeclaredTypeDescriptor.Parse(DeclaredType);
    public LogicalTypeID LeafType => TypeDescriptor.LeafType;
    public int ListDepth => TypeDescriptor.ListDepth;

    public ColumnDefinition(string name, LogicalTypeID type, string? declaredType = null)
    {
        Name = name;
        Type = type;
        DeclaredType = string.IsNullOrWhiteSpace(declaredType) ? type.ToString() : declaredType.Trim();
    }
}

/// <summary>
/// A Property Definition encompasses a Column format coupled with expression defaults.
/// </summary>
public class PropertyDefinition
{
    public ColumnDefinition ColumnDef { get; set; }
    
    // Omitting ParsedExpression for Phase 3 since the Parser is not implemented.
    public string DefaultExpressionName { get; set; }

    public PropertyDefinition(ColumnDefinition columnDef, string defaultExpressionName = "")
    {
        ColumnDef = columnDef;
        DefaultExpressionName = defaultExpressionName;
    }

    public string Name => ColumnDef.Name;
    public LogicalTypeID Type => ColumnDef.Type;
    public string DeclaredType => ColumnDef.DeclaredType;
    public DeclaredTypeDescriptor TypeDescriptor => ColumnDef.TypeDescriptor;
    public LogicalTypeID LeafType => ColumnDef.LeafType;
    public int ListDepth => ColumnDef.ListDepth;

    public void Rename(string newName)
    {
        ColumnDef.Name = newName;
    }
}
