//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (rel_group_catalog_entry.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using BogDb.Core.Common;

namespace BogDb.Core.Catalog;

public readonly record struct RelConnection(string SrcTableName, string DstTableName);

public sealed class RelGroupCatalogEntry : TableCatalogEntry
{
    private readonly List<ulong> _relTableIDs;
    private readonly List<RelConnection> _connections;

    public string SrcTableName { get; private set; }
    public string DstTableName { get; private set; }

    public RelGroupCatalogEntry(string name, string srcTableName = "", string dstTableName = "")
        : base(CatalogEntryType.REL_GROUP_ENTRY, name)
    {
        _relTableIDs = new List<ulong>();
        _connections = new List<RelConnection>();
        SrcTableName = string.Empty;
        DstTableName = string.Empty;
        AddConnection(srcTableName, dstTableName);
    }

    public override TableType GetTableType()
    {
        return TableType.UNKNOWN;
    }

    public IReadOnlyList<ulong> GetRelTableIDs() => _relTableIDs;
    public IReadOnlyList<RelConnection> GetConnections() => _connections;

    public void AddRelTableID(ulong tableID)
    {
        _relTableIDs.Add(tableID);
    }

    public bool ContainsConnection(string srcTableName, string dstTableName)
    {
        var connection = NormalizeConnection(srcTableName, dstTableName);
        return connection is not null && _connections.Contains(connection.Value);
    }

    public bool AddConnection(string srcTableName, string dstTableName)
    {
        var connection = NormalizeConnection(srcTableName, dstTableName);
        if (connection is null || _connections.Contains(connection.Value))
            return false;

        _connections.Add(connection.Value);
        SyncPrimaryConnection();
        return true;
    }

    public bool DropConnection(string srcTableName, string dstTableName)
    {
        var connection = NormalizeConnection(srcTableName, dstTableName);
        if (connection is null)
            return false;

        var removed = _connections.Remove(connection.Value);
        if (removed)
            SyncPrimaryConnection();
        return removed;
    }

    public bool ReferencesNodeTable(string tableName)
    {
        foreach (var connection in _connections)
        {
            if (string.Equals(connection.SrcTableName, tableName, StringComparison.OrdinalIgnoreCase) ||
                string.Equals(connection.DstTableName, tableName, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    public void RenameEndpointTable(string oldTableName, string newTableName)
    {
        for (var i = 0; i < _connections.Count; i++)
        {
            var connection = _connections[i];
            var src = string.Equals(connection.SrcTableName, oldTableName, StringComparison.OrdinalIgnoreCase)
                ? newTableName
                : connection.SrcTableName;
            var dst = string.Equals(connection.DstTableName, oldTableName, StringComparison.OrdinalIgnoreCase)
                ? newTableName
                : connection.DstTableName;
            _connections[i] = new RelConnection(src, dst);
        }

        DeduplicateConnections();
        SyncPrimaryConnection();
    }

    public override TableCatalogEntry Copy()
    {
        var copy = new RelGroupCatalogEntry(Name);
        copy.SetOID(OID);
        copy.SetTimestamp(Timestamp);
        copy.SetDeleted(IsDeleted);
        copy.SetHasParent(HasParent);
        copy.SetComment(_comment);
        foreach (var property in GetProperties())
        {
            copy.AddProperty(new PropertyDefinition(
                new ColumnDefinition(property.ColumnDef.Name, property.ColumnDef.Type, property.ColumnDef.DeclaredType),
                property.DefaultExpressionName));
        }
        foreach (var connection in _connections)
        {
            copy.AddConnection(connection.SrcTableName, connection.DstTableName);
        }
        foreach (var id in _relTableIDs)
        {
            copy.AddRelTableID(id);
        }
        return copy;
    }

    public override void Serialize(System.IO.BinaryWriter writer)
    {
        base.Serialize(writer);
        writer.Write(SrcTableName);
        writer.Write(DstTableName);
        if (_connections.Count == 1 &&
            string.Equals(_connections[0].SrcTableName, SrcTableName, StringComparison.Ordinal) &&
            string.Equals(_connections[0].DstTableName, DstTableName, StringComparison.Ordinal))
        {
            writer.Write(_relTableIDs.Count);
        }
        else
        {
            writer.Write(-1);
            writer.Write(_connections.Count);
            foreach (var connection in _connections)
            {
                writer.Write(connection.SrcTableName);
                writer.Write(connection.DstTableName);
            }
            writer.Write(_relTableIDs.Count);
        }
        foreach (var id in _relTableIDs)
        {
            writer.Write(id);
        }
    }

    public new static RelGroupCatalogEntry Deserialize(System.IO.BinaryReader reader)
    {
        string name = reader.ReadString();
        ulong oid = reader.ReadUInt64();
        ulong timestamp = reader.ReadUInt64();
        bool isDeleted = reader.ReadBoolean();
        bool hasParent = reader.ReadBoolean();
        string comment = reader.ReadString();
        int numProperties = reader.ReadInt32();

        var entry = new RelGroupCatalogEntry(name);
        entry.SetOID(oid);
        entry.SetTimestamp(timestamp);
        entry.SetDeleted(isDeleted);
        entry.SetHasParent(hasParent);
        entry.SetComment(comment);
        DeserializeProperties(reader, entry, numProperties);

        entry.SrcTableName = reader.ReadString();
        entry.DstTableName = reader.ReadString();

        int marker = reader.ReadInt32();
        int relTableCount;
        if (marker < 0)
        {
            int connectionCount = reader.ReadInt32();
            entry._connections.Clear();
            for (int i = 0; i < connectionCount; i++)
            {
                entry.AddConnection(reader.ReadString(), reader.ReadString());
            }
            relTableCount = reader.ReadInt32();
        }
        else
        {
            entry._connections.Clear();
            entry.AddConnection(entry.SrcTableName, entry.DstTableName);
            relTableCount = marker;
        }

        for (int i = 0; i < relTableCount; i++)
        {
            entry.AddRelTableID(reader.ReadUInt64());
        }

        return entry;
    }

    private static RelConnection? NormalizeConnection(string srcTableName, string dstTableName)
    {
        var normalizedSrc = srcTableName?.Trim() ?? string.Empty;
        var normalizedDst = dstTableName?.Trim() ?? string.Empty;
        if (string.IsNullOrEmpty(normalizedSrc) || string.IsNullOrEmpty(normalizedDst))
            return null;

        return new RelConnection(normalizedSrc, normalizedDst);
    }

    private void DeduplicateConnections()
    {
        var seen = new HashSet<RelConnection>();
        for (int i = _connections.Count - 1; i >= 0; i--)
        {
            if (seen.Add(_connections[i]))
                continue;
            _connections.RemoveAt(i);
        }
    }

    private void SyncPrimaryConnection()
    {
        if (_connections.Count == 0)
        {
            SrcTableName = string.Empty;
            DstTableName = string.Empty;
            return;
        }

        SrcTableName = _connections[0].SrcTableName;
        DstTableName = _connections[0].DstTableName;
    }
}
