//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (table_catalog_entry.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;
using BogDb.Core.Common;

namespace BogDb.Core.Catalog;

/// <summary>
/// A TableCatalogEntry extends the base catalog metadata and handles
/// Schema Properties (Columns) spanning a single table's ID limits.
/// </summary>
public abstract class TableCatalogEntry : CatalogEntry
{
    protected string _comment;
    protected readonly PropertyDefinitionCollection _propertyCollection;

    protected TableCatalogEntry(CatalogEntryType catalogType, string name) 
        : base(catalogType, name)
    {
        _comment = string.Empty;
        _propertyCollection = new PropertyDefinitionCollection();
    }

    public ulong TableID => OID;

    public abstract TableType GetTableType();

    public string GetComment() => _comment;
    public void SetComment(string comment) => _comment = comment;

    public int GetNumProperties() => _propertyCollection.Size;
    public bool ContainsProperty(string propertyName) => _propertyCollection.Contains(propertyName);
    public uint GetPropertyID(string propertyName) => _propertyCollection.GetPropertyID(propertyName);
    
    public PropertyDefinition GetProperty(string propertyName) => _propertyCollection.GetDefinition(propertyName);
    
    public uint GetColumnID(string propertyName) => _propertyCollection.GetColumnID(propertyName);

    public void AddProperty(PropertyDefinition propertyDefinition)
    {
        _propertyCollection.Add(propertyDefinition);
    }

    public IEnumerable<PropertyDefinition> GetProperties()
        => _propertyCollection.GetAllDefinitions();

    public void DropProperty(string propertyName)
    {
        _propertyCollection.Drop(propertyName);
    }

    public virtual void RenameProperty(string propertyName, string newName)
    {
        _propertyCollection.Rename(propertyName, newName);
    }

    public override void Serialize(BinaryWriter writer)
    {
        // 1. Serialize Base object
        writer.Write((byte)Type);
        writer.Write(Name);
        writer.Write(OID);
        writer.Write(Timestamp);
        writer.Write(IsDeleted);
        writer.Write(HasParent);

        // 2. Serialize specialized table params
        writer.Write(_comment);
        writer.Write(_propertyCollection.Size);
        foreach (var property in _propertyCollection.GetAllDefinitions())
        {
            writer.Write(property.ColumnDef.Name);
            writer.Write((byte)property.ColumnDef.Type);
            writer.Write(property.ColumnDef.DeclaredType);
            writer.Write(property.DefaultExpressionName ?? string.Empty);
        }
    }

    public abstract TableCatalogEntry Copy();

    protected static void DeserializeProperties(BinaryReader reader, TableCatalogEntry entry, int numProperties)
    {
        for (var i = 0; i < numProperties; i++)
        {
            var propertyName = reader.ReadString();
            var type = (LogicalTypeID)reader.ReadByte();
            var declaredType = reader.ReadString();
            var defaultExpressionName = reader.ReadString();
            entry.AddProperty(new PropertyDefinition(
                new ColumnDefinition(propertyName, type, declaredType),
                defaultExpressionName));
        }
    }
}
