//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (scan_node_property.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using BogDb.Core.Binder;
using BogDb.Core.Common;

namespace BogDb.Core.Processor.Operator.Scan;

/// <summary>
/// Physical implementation hitting actual Graph Storage buffers extracting Vector chunks.
/// </summary>
public sealed class ScanNodeProperty : PhysicalOperator
{
    private readonly Main.BogDatabase _database;
    private readonly string _tableName;
    private readonly string _variableName;
    private readonly IReadOnlyList<(string Key, Expression Value)> _inlineProperties;
    private readonly Expression? _inlinePropertyBag;
    private readonly Expression? _pushedPredicate;
    private IEnumerator<KeyValuePair<object, Dictionary<string, object>>>? _iterator;
    private bool _tableIdResolved;
    private ulong _tableId;

    public ScanNodeProperty(
        Main.BogDatabase database,
        string tableName,
        string variableName,
        IReadOnlyList<(string Key, Expression Value)> inlineProperties,
        Expression? inlinePropertyBag,
        Expression? pushedPredicate,
        uint id) 
        : base(PhysicalOperatorType.SCAN_NODE_PROPERTY, id)
    {
        _database = database;
        _tableName = tableName;
        _variableName = variableName;
        _inlineProperties = inlineProperties;
        _inlinePropertyBag = inlinePropertyBag;
        _pushedPredicate = pushedPredicate;
    }

    public ScanNodeProperty(
        Main.BogDatabase database,
        string tableName,
        string variableName,
        IReadOnlyList<(string Key, Expression Value)> inlineProperties,
        Expression? inlinePropertyBag,
        uint id)
        : this(database, tableName, variableName, inlineProperties, inlinePropertyBag, null, id)
    {
    }

    public ScanNodeProperty(
        Main.BogDatabase database,
        string tableName,
        string variableName,
        IReadOnlyList<(string Key, Expression Value)> inlineProperties,
        uint id)
        : this(database, tableName, variableName, inlineProperties, null, null, id)
    {
    }

    public ScanNodeProperty(
        Main.BogDatabase database,
        string tableName,
        string variableName,
        uint id)
        : this(database, tableName, variableName, System.Array.Empty<(string Key, Expression Value)>(), null, null, id)
    {
    }

    /// <summary>
    /// Pulls graph properties.
    /// Under authentic Phase 6 BogDb Storage integration, this will yield False when 
    /// table chunks exhaust limits. We are stubbing a single chunk pull for test verifications.
    /// </summary>
    public override bool GetNextTuple(ExecutionContext context)
    {
        if (_iterator == null)
        {
            if (_database.NodeTables.TryGetValue(_tableName, out var table))
            {
                // Lazy streaming: use enumerator directly instead of materializing all rows
                _iterator = table.EnumerateRows(context.Transaction).GetEnumerator();
            }
            else
            {
                _iterator = _database.GraphStore.EnumerateNodes(_tableName).GetEnumerator();
            }
        }
        while (true)
        {
            if (!_iterator.MoveNext())
            {
                return false;
            }

            var current = _iterator.Current;
            var currentProperties = _database.NormalizeNodePropertiesForRead(_tableName, current.Value);
            if (IsFilteredBySemiMask(context, current.Key))
            {
                continue;
            }
            if (!MatchesInlineProperties(current.Key, currentProperties, context))
            {
                continue;
            }

            context.CurrentNodeId = current.Key;
            context.CurrentNodeProperties = currentProperties;
            if (context.CurrentNodeProperties != null &&
                !context.CurrentNodeProperties.ContainsKey("id"))
            {
                context.CurrentNodeProperties["id"] = current.Key;
            }
            context.CurrentVariableIds = new Dictionary<string, object> { [_variableName] = current.Key };
            context.CurrentVariableProperties = new Dictionary<string, Dictionary<string, object>>
            {
                [_variableName] = currentProperties
            };
            context.CurrentProjectionRow = null;

            // Apply pushed-down predicate (from FilterPushDownRule optimizer).
            if (_pushedPredicate != null)
            {
                var predicateResult = ExpressionExecutionHelper.Evaluate(_pushedPredicate, context);
                if (predicateResult is not true)
                    continue;
            }

            return true;
        }
    }

    private bool IsFilteredBySemiMask(ExecutionContext context, object key)
    {
        if (context.SemiMasks == null)
            return false;

        if (!_tableIdResolved)
        {
            _tableIdResolved = true;
            var entry = _database.Catalog.GetTableEntry(_tableName);
            _tableId = entry?.TableID ?? 0;
        }

        if (_tableId == 0)
            return false;

        return context.SemiMasks.TryGetValue(_tableId, out var set) && !set.Contains(key);
    }

    private bool MatchesInlineProperties(object nodeId, Dictionary<string, object> properties, ExecutionContext context)
    {
        if (_inlineProperties.Count == 0)
        {
            if (_inlinePropertyBag == null)
                return true;

            var propertyBag = EvaluatePropertyBag(context);
            if (propertyBag == null)
                return false;

            foreach (var (key, expected) in propertyBag)
            {
                object? actual = key.Equals("id", System.StringComparison.OrdinalIgnoreCase)
                    ? nodeId
                    : properties.TryGetValue(key, out var value) ? value : null;
                if (!StructuralValueComparer.AreEqual(actual, expected))
                    return false;
            }

            return true;
        }

        foreach (var (key, expression) in _inlineProperties)
        {
            var expected = TypeCoercionHelper.Normalize(
                ExpressionExecutionHelper.Evaluate(expression, context));

            object? actual;
            if (key.Equals("id", System.StringComparison.OrdinalIgnoreCase))
            {
                actual = nodeId;
            }
            else if (!properties.TryGetValue(key, out actual))
            {
                return false;
            }

            if (!StructuralValueComparer.AreEqual(actual, expected))
                return false;
        }

        return true;
    }

    private Dictionary<string, object?>? EvaluatePropertyBag(ExecutionContext context)
    {
        if (_inlinePropertyBag == null)
            return null;

        var raw = ExpressionExecutionHelper.Evaluate(_inlinePropertyBag, context);
        return TryConvertPropertyBag(raw);
    }

    private static Dictionary<string, object?>? TryConvertPropertyBag(object? raw)
    {
        if (raw is Dictionary<string, object> dict)
            return dict.ToDictionary(kvp => kvp.Key, kvp => (object?)kvp.Value, System.StringComparer.OrdinalIgnoreCase);
        return null;
    }
}
