//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (csv_reader.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using BogDb.Core.Common;

namespace BogDb.Core.Processor.Operator.Persistent.Reader.CSV;

/// <summary>
/// A CSV sequential stream reader.
///
/// Provides two reading modes:
///   • ReadTuples() — original columnar API, preserved for backward compat.
///   • ReadAllRows() — new multi-column row-at-a-time API for full property ingestion.
///
/// ReadAllRows() yields each non-empty data row (skipping header) as a string-cell array.
/// The caller is responsible for type-parsing each cell.
/// </summary>
public sealed class CSVReader : IDisposable
{
    private readonly StreamReader _streamReader;

    /// <summary>
    /// Whether the first data row has been seen (used by ReadTuples for legacy compat).
    /// </summary>
    private bool _headerSkipped = false;

    // Keep legacy low-level fields for ReadTuples() backward compat
    private readonly Stream _stream;
    private readonly byte[] _buffer;
    private int _bufferLength;
    private int _bufferPosition;

    private const int BUFFER_SIZE = 4096 * 64;
    private const byte COMMA = (byte)',';
    private const byte NEWLINE = (byte)'\n';
    private const byte RETURN = (byte)'\r';

    public CSVReader(string filePath)
    {
        _stream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read, BUFFER_SIZE, FileOptions.SequentialScan);
        _buffer = new byte[BUFFER_SIZE];
        // StreamReader wraps the same underlying stream for ReadAllRows()
        _streamReader = new StreamReader(
            new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read),
            System.Text.Encoding.UTF8,
            detectEncodingFromByteOrderMarks: true,
            bufferSize: 4096,
            leaveOpen: false);
    }

    public CSVReader(string source, bool treatAsContent)
    {
        if (!treatAsContent)
            throw new ArgumentException("Use the file path constructor for file-backed CSV sources.", nameof(treatAsContent));

        var bytes = Encoding.UTF8.GetBytes(source);
        _stream = new MemoryStream(bytes, writable: false);
        _buffer = new byte[BUFFER_SIZE];
        _streamReader = new StreamReader(
            new MemoryStream(bytes, writable: false),
            Encoding.UTF8,
            detectEncodingFromByteOrderMarks: true,
            bufferSize: 4096,
            leaveOpen: false);
    }

    // ── Multi-column row API ──────────────────────────────────────────────────

    /// <summary>
    /// Streams every data row from the CSV as a string-cell array.
    /// • The first line is ALWAYS treated as a header and skipped.
    /// • Empty / whitespace-only lines are skipped.
    /// • Cells are trimmed of leading/trailing whitespace.
    ///
    /// The caller parcels each cell into the correct CLR type via the column schema.
    /// </summary>
    public IEnumerable<string?[]> ReadAllRows(int columnCount)
    {
        // Skip header row
        _streamReader.ReadLine();

        string? line;
        while ((line = _streamReader.ReadLine()) != null)
        {
            if (string.IsNullOrWhiteSpace(line)) continue;

            var rawParts = line.Split(',');
            var cells = new string?[columnCount];
            for (int c = 0; c < columnCount; c++)
            {
                cells[c] = c < rawParts.Length ? rawParts[c].Trim() : null;
            }
            yield return cells;
        }
    }

    // ── Legacy single-column API (backward compat) ────────────────────────────

    /// <summary>
    /// Populates the target vector completely from a single column of the CSV.
    /// In native BogDb, chunks consist of blocks up to 2048 elements.
    /// </summary>
    /// <param name="targetVector">The typed destination vector</param>
    /// <param name="columnIndex">The index of the column to extract</param>
    /// <returns>Number of tuples pushed into the vector</returns>
    public ulong ReadTuples(ValueVector targetVector, int columnIndex)
    {
        ulong tuplesRead = 0;

        while (tuplesRead < (ulong)targetVector.Capacity && FillBufferIfEmpty())
        {
            // Advance to correct column
            for (int i = 0; i < columnIndex; i++)
            {
                if (!AdvanceToNextDelimiter(COMMA))
                    return tuplesRead; // EOF before column found
            }

            // Extract sequence length bounded by next COMMA or newline
            var startPos = _bufferPosition;
            var endPos = startPos;
            while (_bufferPosition < _bufferLength)
            {
                var currentByte = _buffer[_bufferPosition];
                if (currentByte == COMMA || currentByte == NEWLINE || currentByte == RETURN)
                {
                    endPos = _bufferPosition;
                    break;
                }
                _bufferPosition++;
            }

            // Fallback for EOF boundary
            if (endPos == startPos) endPos = _bufferPosition;

            var span = new ReadOnlySpan<byte>(_buffer, startPos, endPos - startPos);

            // Phase 8 Cast (Hardcoded int64 parsing for validation simulation)
            if (targetVector.DataType == LogicalTypeID.INT64)
            {
                if (System.Buffers.Text.Utf8Parser.TryParse(span, out long value, out _))
                {
                    targetVector.SetValue((uint)tuplesRead, value);
                }
            }

            tuplesRead++;

            // Seek to new line
            AdvanceToNextDelimiter(NEWLINE);
        }

        return tuplesRead;
    }

    private bool AdvanceToNextDelimiter(byte delimiter)
    {
        while (FillBufferIfEmpty())
        {
            while (_bufferPosition < _bufferLength)
            {
                if (_buffer[_bufferPosition++] == delimiter)
                    return true;
            }
        }
        return false;
    }

    private bool FillBufferIfEmpty()
    {
        if (_bufferPosition >= _bufferLength)
        {
            _bufferPosition = 0;
            _bufferLength = _stream.Read(_buffer, 0, _buffer.Length);
        }
        return _bufferLength > 0;
    }

    public void Dispose()
    {
        _streamReader.Dispose();
        _stream.Dispose();
    }
}
