//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (logical_plan.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Planner.Operator;

namespace BogDb.Core.Planner;

/// <summary>
/// LogicalPlan encapsulates the execution AST spanning LogicalOperators.
/// Tracks query cost metrics allowing BogDb to select an optimal iteration strategy.
/// </summary>
public sealed class LogicalPlan
{
    public LogicalOperator LastOperator { get; set; }
    
    // Tracks heuristic estimates for execution time
    public double Cost { get; set; }
    
    // Tracks cardinality estimates (how many rows we expect here)
    public ulong Cardinality { get; set; }

    public LogicalPlan()
    {
        Cost = 0;
        Cardinality = 0;
    }

    public LogicalPlan ShallowCopy()
    {
        var plan = new LogicalPlan();
        plan.LastOperator = LastOperator;
        plan.Cost = Cost;
        plan.Cardinality = Cardinality;
        return plan;
    }
}
