//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code
//     by BogDB. Validates Phase 8 bulk insertion parsing logic.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;
using Xunit;
using BogDb.Core.Common;
using BogDb.Core.Processor.Operator.Persistent.Reader.CSV;

namespace BogDb.Tests.Processor;

public class CSVReaderTests
{
    [Fact]
    public void CSVReader_ParsesInt64Column_WithoutHeapAllocations()
    {
        // 1. Arrange 
        var tempFile = Path.GetTempFileName();
        File.WriteAllText(tempFile, "10\n20\n30\n40\n50");
        
        // C++ BogDb uses 2048 Default blocks.
        var vector = new ValueVector(LogicalTypeID.INT64, 2048);

        // 2. Act
        using var reader = new CSVReader(tempFile);
        var tuplesRead = reader.ReadTuples(vector, 0);

        // 3. Assert
        Assert.Equal(5UL, tuplesRead);
        Assert.Equal(10L, vector.GetValue<long>(0));
        Assert.Equal(20L, vector.GetValue<long>(1));
        Assert.Equal(30L, vector.GetValue<long>(2));
        Assert.Equal(40L, vector.GetValue<long>(3));
        Assert.Equal(50L, vector.GetValue<long>(4));
        
        // 4. Cleanup
        reader.Dispose();
        File.Delete(tempFile);
    }
}
