//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code
//     by BogDB. Validates Phase 6 physical SIMD constraints.
// </auto-generated>
//------------------------------------------------------------------------------

using Xunit;
using BogDb.Core.ExpressionEvaluator;
using BogDb.Core.Common;

namespace BogDb.Tests.Processor;

public class VectorMathTests
{
    [Fact]
    public void FunctionEvaluator_AddsVectorsProperly()
    {
        // Assemble: Create Vector Morsels with 3 elements each
        var leftVector = new ValueVector(LogicalTypeID.INT64, 3);
        var rightVector = new ValueVector(LogicalTypeID.INT64, 3);
        var resultVector = new ValueVector(LogicalTypeID.INT64, 3);

        // Fill data natively
        leftVector.SetValue<long>(0, 10); leftVector.SetValue<long>(1, 20); leftVector.SetValue<long>(2, 30);
        rightVector.SetValue<long>(0, 5); rightVector.SetValue<long>(1, 15); rightVector.SetValue<long>(2, 25);

        // Mock Literal children simply returning true (Math runs directly off ResultVector buffers)
        var mockLeft = new LiteralEvaluator(true); // Bypass
        mockLeft.GetType().GetProperty("ResultVector").SetValue(mockLeft, leftVector, null);

        var mockRight = new LiteralEvaluator(true); // Bypass
        mockRight.GetType().GetProperty("ResultVector").SetValue(mockRight, rightVector, null);

        // Map Vector Function `+`
        var addEvaluator = new FunctionEvaluator(FunctionEvaluator.AddInt64, mockLeft, mockRight, resultVector);

        // Act
        addEvaluator.Evaluate();

        // Assert
        Assert.Equal(15, resultVector.GetValue<long>(0));
        Assert.Equal(35, resultVector.GetValue<long>(1));
        Assert.Equal(55, resultVector.GetValue<long>(2));
        
        leftVector.Dispose();
        rightVector.Dispose();
        resultVector.Dispose();
    }
}
