//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (insert_node.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using BogDb.Core.Binder;
using BogDb.Core.Catalog;

namespace BogDb.Core.Processor.Operator.Update;

/// <summary>
/// Physical operator responsible for inserting nodes and relationships 
/// into the LocalStorage buffer pool (NodeTableData/RelTableData).
/// </summary>
public sealed class PhysicalInsert : PhysicalOperator
{
    private readonly Main.BogDatabase _database;
    private readonly List<QueryNode> _nodes;
    private readonly List<QueryRel> _rels;
    private bool _hasExecuted = false;

    public PhysicalInsert(
        Main.BogDatabase database,
        List<QueryNode> nodes,
        List<QueryRel> rels,
        PhysicalOperator? child,
        uint id) 
        : base(PhysicalOperatorType.INSERT_NODE, id) // Combined insert operator type
    {
        _database = database;
        _nodes = nodes;
        _rels = rels;
        if (child != null)
        {
            Children.Add(child);
        }
    }

    public override bool GetNextTuple(ExecutionContext context)
    {
        if (_hasExecuted) return false;

        // Try to pull from the Match block (or execute if no dependencies)
        bool shouldExecute = Children.Count > 0 ? Children[0].GetNextTuple(context) : true;

        if (shouldExecute)
        {
            // No match found -> execute the inserts
            foreach (var node in _nodes)
            {
                if (!string.IsNullOrEmpty(node.VariableName) && 
                    context.CurrentVariableIds != null && 
                    context.CurrentVariableIds.ContainsKey(node.VariableName))
                {
                    // Variable is already bound by the upstream MATCH pipeline! Skip creating a new node.
                    continue;
                }

                var tableName = node.TableNames.Count > 0 ? node.TableNames[0] : "";
                var properties = new Dictionary<string, object>();
                object? idValue = null;

                if (node.InlinePropertyBag != null)
                {
                    foreach (var (key, value) in EvaluatePropertyBag(node.InlinePropertyBag, context))
                    {
                        if (value is not null)
                            properties[key] = value;
                        if (key.Equals("id", StringComparison.OrdinalIgnoreCase))
                            idValue = value;
                    }
                }

                // Real extraction: check inline bound values
                foreach (var inlineProp in node.InlineProperties)
                {
                    var value = Common.TypeCoercionHelper.Normalize(
                        ExpressionExecutionHelper.Evaluate(inlineProp.Value, context));
                    if (value is not null)
                        properties[inlineProp.Key] = value;
                    if (inlineProp.Key.Equals("id", StringComparison.OrdinalIgnoreCase))
                    {
                        idValue = value;
                    }
                }

                if (idValue == null)
                {
                    idValue = Guid.NewGuid().ToString();
                }

                var tableEntry = _database.Catalog.GetTableCatalogEntry(context.Transaction, tableName, useInternal: false);
                properties = PropertyValueCoercion.CoerceProperties(tableEntry, properties);

                if (_database.IsInMemory)
                {
                    if (!_database.NodeTables.ContainsKey(tableName))
                    {
                        _database.NodeTables[tableName] = new Main.NodeTableData();
                    }
                    var table = _database.NodeTables[tableName];
                    table.Upsert(context.Transaction, idValue, properties);
                }

                _database.GraphLog.AppendNode(tableName, idValue, properties);

                // Populate any registered property indexes via the canonical db method
                if (_database.IsInMemory && _database.NodeTables.TryGetValue(tableName, out var idxTable))
                    _database.UpdateNodeIndexes(tableName, idValue, properties, idxTable);

                // Bind variable to context so downstream operators see it
                if (!string.IsNullOrEmpty(node.VariableName))
                {
                    context.CurrentVariableIds ??= new Dictionary<string, object>();
                    context.CurrentVariableProperties ??= new Dictionary<string, Dictionary<string, object>>();
                    context.CurrentVariableIds[node.VariableName] = idValue;
                    context.CurrentVariableProperties[node.VariableName] = properties;
                }
            }

            foreach (var rel in _rels)
            {
                var tableName = rel.TableNames.Count > 0 ? rel.TableNames[0] : "";
                var properties = new Dictionary<string, object>();

                if (rel.InlinePropertyBag != null)
                {
                    foreach (var (key, value) in EvaluatePropertyBag(rel.InlinePropertyBag, context))
                    {
                        if (value is not null)
                            properties[key] = value;
                    }
                }

                 // Note: we'd normally extract src/dst IDs from the bound rel. 
                 // For now, generating a surrogate relationship ID.
                object fromId = Guid.NewGuid().ToString();
                object toId = Guid.NewGuid().ToString();

                // Because UpsertRelationship does MATCH (a) MATCH (b) MERGE (a)-[r:KNOWS]->(b)
                // We should pull IDs from context.
                if (rel.SrcNode != null && !string.IsNullOrEmpty(rel.SrcNode.VariableName) && context.CurrentVariableIds != null)
                {
                    if (context.CurrentVariableIds.TryGetValue(rel.SrcNode.VariableName, out var val)) fromId = val;
                }
                if (rel.DstNode != null && !string.IsNullOrEmpty(rel.DstNode.VariableName) && context.CurrentVariableIds != null)
                {
                    if (context.CurrentVariableIds.TryGetValue(rel.DstNode.VariableName, out var val)) toId = val;
                }

                var relId = new Main.EdgeKey(fromId, toId);
                
                // Track inline properties
                foreach (var inlineProp in rel.InlineProperties)
                {
                    var value = Common.TypeCoercionHelper.Normalize(
                        ExpressionExecutionHelper.Evaluate(inlineProp.Value, context));
                    if (value is not null)
                        properties[inlineProp.Key] = value;
                }
                
                var tableEntry = _database.Catalog.GetTableCatalogEntry(context.Transaction, tableName, useInternal: false);
                properties = PropertyValueCoercion.CoerceProperties(tableEntry, properties);

                if (_database.IsInMemory)
                {
                    if (!_database.RelTables.ContainsKey(tableName))
                    {
                        _database.RelTables[tableName] = new Main.RelTableData();
                    }
                    var table = _database.RelTables[tableName];
                    table.Upsert(context.Transaction, relId, properties);
                }

                _database.GraphLog.AppendRel(tableName, fromId, toId, properties);

                // Bind relationship variable to context so downstream operators see it
                if (!string.IsNullOrEmpty(rel.VariableName))
                {
                    context.CurrentVariableIds ??= new Dictionary<string, object>();
                    context.CurrentVariableProperties ??= new Dictionary<string, Dictionary<string, object>>();
                    context.CurrentVariableIds[rel.VariableName] = relId;
                    context.CurrentVariableProperties[rel.VariableName] = properties;
                }
            }
        }

        _hasExecuted = true;
        return true;
    }

    private static Dictionary<string, object?> EvaluatePropertyBag(Expression propertyBag, ExecutionContext context)
    {
        var raw = ExpressionExecutionHelper.Evaluate(propertyBag, context);
        return raw switch
        {
            Dictionary<string, object> dict => dict.ToDictionary(kvp => kvp.Key, kvp => (object?)kvp.Value, StringComparer.OrdinalIgnoreCase),
            _ => throw new InvalidOperationException("Property bag expressions must evaluate to a dictionary.")
        };
    }
}
