//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (buffer_manager.cpp)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading;
using System.Collections.Concurrent;
using System;

namespace BogDb.Core.Storage.BufferManager;

/// <summary>
/// The Buffer Manager (BM) provides centralized management over memory limits, 
/// Disk pinning / unpinning, and Memory mapped Region coordination.
/// 
/// Uses lock-free queues and Interlocked eviction logic ported from BogDb.
/// </summary>
public class BufferManager : IDisposable
{
    private long _bufferPoolSize;
    private long _usedMemory;
    
    // Concurrency-safe collections
    private readonly EvictionQueue _evictionQueue;
    private readonly ConcurrentDictionary<uint, FileHandle> _fileHandles;
    private readonly ConcurrentDictionary<(uint fileIdx, uint pageIdx), byte[]> _frames;
    private readonly Transaction.WAL? _wal;
    
    public long MemoryLimit => Interlocked.Read(ref _bufferPoolSize);
    public long UsedMemory => Interlocked.Read(ref _usedMemory);

    public BufferManager(long bufferPoolSize, long maxDbSize, Transaction.WAL? wal = null)
    {
        if (bufferPoolSize < (long)FileHandle.BOGDB_PAGE_SIZE)
            throw new ArgumentOutOfRangeException(nameof(bufferPoolSize), $"Buffer pool size must be at least {FileHandle.BOGDB_PAGE_SIZE} bytes");

        _bufferPoolSize = bufferPoolSize;
        _usedMemory = 0;
        _wal = wal;
        
        // EvictionQueue sizing based on page blocks
        _evictionQueue = new EvictionQueue(bufferPoolSize / (long)FileHandle.BOGDB_PAGE_SIZE);
        _fileHandles = new ConcurrentDictionary<uint, FileHandle>();
        _frames = new ConcurrentDictionary<(uint fileIdx, uint pageIdx), byte[]>();
    }

    public FileHandle GetFileHandle(string filePath, byte flags, uint fileIndex)
    {
        var handle = new FileHandle(filePath, flags, this, fileIndex, _wal);
        _fileHandles[fileIndex] = handle;
        return handle;
    }

    public void Unpin(FileHandle fileHandle, uint pageIdx)
    {
        var pageState = fileHandle.GetPageState(pageIdx);
        pageState.Unlock(); // Page transits into UNLOCKED state and increments Version clock

        // Since it's no longer pinned, we must push it into the EvictionQueue
        _evictionQueue.Insert(fileHandle.FileIndex, pageIdx);
    }

    public unsafe byte* GetFrame(FileHandle fileHandle, uint pageIdx)
    {
        var key = (fileHandle.FileIndex, pageIdx);
        if (!_frames.TryGetValue(key, out var frame))
        {
            frame = GC.AllocateArray<byte>((int)fileHandle.GetPageSize(), pinned: true);
            _frames.TryAdd(key, frame);
        }
        
        fixed (byte* p = frame)
        {
            return p;
        }
    }

    private unsafe void CachePageIntoFrame(FileHandle fileHandle, uint pageIdx, PageReadPolicy readPolicy)
    {
        while (pageIdx >= fileHandle.NumPages)
        {
            fileHandle.AddNewPage();
        }

        fileHandle.GetPageState(pageIdx).ClearDirty();
        if (readPolicy == PageReadPolicy.READ_PAGE)
        {
            fileHandle.ReadPageFromDisk(GetFrame(fileHandle, pageIdx), pageIdx);
        }
    }

    private bool Reserve(ulong sizeToReserve)
    {
        Interlocked.Add(ref _usedMemory, (long)sizeToReserve);
        ulong totalClaimedMemory = 0;
        
        while (sizeToReserve > totalClaimedMemory && UsedMemory > MemoryLimit - (long)totalClaimedMemory)
        {
            ulong memoryClaimed = EvictPages();
            if (memoryClaimed == 0)
            {
                FreeUsedMemory((long)(sizeToReserve + totalClaimedMemory));
                return false;
            }
            totalClaimedMemory += memoryClaimed;
        }
        
        if (totalClaimedMemory > 0)
        {
            FreeUsedMemory((long)totalClaimedMemory);
        }
        return true;
    }

    private bool ClaimAFrame(FileHandle fileHandle, uint pageIdx, PageReadPolicy readPolicy)
    {
        ulong pageSizeToClaim = fileHandle.GetPageSize();
        if (!Reserve(pageSizeToClaim))
            return false;
            
        CachePageIntoFrame(fileHandle, pageIdx, readPolicy);
        return true;
    }

    public unsafe byte* Pin(FileHandle fileHandle, uint pageIdx, PageReadPolicy readPolicy)
    {
        var pageState = fileHandle.GetPageState(pageIdx);
        
        while (true)
        {
            ulong currStateAndVersion = pageState.GetStateAndVersion();
            ulong state = PageState.GetState(currStateAndVersion);

            switch (state)
            {
                case PageState.EVICTED:
                    if (pageState.TryLock(currStateAndVersion))
                    {
                        if (!ClaimAFrame(fileHandle, pageIdx, readPolicy))
                        {
                            pageState.ResetToEvicted();
                            throw new Exception("Unable to allocate memory! The buffer pool is full and no memory could be freed!");
                        }
                        if (!_evictionQueue.Insert(fileHandle.FileIndex, pageIdx))
                        {
                            throw new Exception("Eviction queue is full! This should be impossible.");
                        }
                        return GetFrame(fileHandle, pageIdx);
                    }
                    break;
                case PageState.UNLOCKED:
                case PageState.MARKED:
                    if (pageState.TryLock(currStateAndVersion))
                    {
                        return GetFrame(fileHandle, pageIdx);
                    }
                    break;
                case PageState.LOCKED:
                    continue;
                default:
                    throw new InvalidOperationException("Unreachable");
            }
        }
    }

    /// <summary>
    /// Evicts up to EvictionQueue.BATCH_SIZE pages by scanning the circular buffer.
    /// Returns the space reclaimed in bytes.
    /// </summary>
    public ulong EvictPages()
    {
        ulong claimedMemory = 0;
        int evictablePages = 0;
        var candidates = new EvictionCandidate[EvictionQueue.BATCH_SIZE];
        var batchIndices = new int[EvictionQueue.BATCH_SIZE];

        var startCursor = _evictionQueue.EvictionCursor;
        var failureLimit = _evictionQueue.Capacity * 2L;
        
        while (evictablePages == 0 && _evictionQueue.EvictionCursor - startCursor < failureLimit)
        {
            var nextBatch = _evictionQueue.Next();
            
            // Reconstruct the index bounds we just pulled so we can clear them individually later
            // We know EvictionCursor jumped by BATCH_SIZE so we trace back
            long startReadIndex = _evictionQueue.EvictionCursor - EvictionQueue.BATCH_SIZE;

            for (int i = 0; i < nextBatch.Length; i++)
            {
                var candidate = nextBatch[i];
                if (candidate == EvictionCandidate.EMPTY)
                    continue;

                if (!_fileHandles.TryGetValue(candidate.FileIdx, out var handle))
                    continue;

                var pageState = handle.GetPageState(candidate.PageIdx);
                ulong stateAndVersion = pageState.GetStateAndVersion();

                if (!EvictionCandidate.IsEvictable(stateAndVersion))
                {
                    // If it was just UNLOCKED but touched recently, demote to MARKED (second chance algorithm)
                    if (EvictionCandidate.IsSecondChanceEvictable(stateAndVersion))
                    {
                        pageState.TryMark(stateAndVersion);
                    }
                    continue;
                }

                candidates[evictablePages] = candidate;
                batchIndices[evictablePages] = (int)((startReadIndex + i) % _evictionQueue.Capacity);
                evictablePages++;
            }
        }

        for (int i = 0; i < evictablePages; i++)
        {
            claimedMemory += TryEvictPage(candidates[i], batchIndices[i]);
        }
        
        return claimedMemory;
    }

    private ulong TryEvictPage(EvictionCandidate candidate, int originalQueueIndex)
    {
        if (candidate.PageIdx == uint.MaxValue || !_fileHandles.TryGetValue(candidate.FileIdx, out var fileHandle))
            return 0;

        var pageState = fileHandle.GetPageState(candidate.PageIdx);
        ulong currStateAndVersion = pageState.GetStateAndVersion();

        // 1. Double check the page is STILL MARKED (Evictable) and Lock it exclusively for purging.
        if (!EvictionCandidate.IsEvictable(currStateAndVersion) || !pageState.TryLock(currStateAndVersion))
        {
            return 0;
        }

        if (fileHandle.IsInMemoryMode())
        {
            pageState.UnlockUnchanged();
            return 0;
        }

        // 2. We are exclusively LOCKED. Safe to Flush and Evict.
        fileHandle.FlushPageIfDirtyWithoutLock(candidate.PageIdx);
        ulong numBytesFreed = fileHandle.GetPageSize();

        // 3. Mark evicted and pull it out of the circular bounds.
        pageState.ResetToEvicted();
        _evictionQueue.ClearFromIndex(originalQueueIndex);
        _frames.TryRemove((candidate.FileIdx, candidate.PageIdx), out _);

        // 4. Give the memory back to the global atomic tracker
        FreeUsedMemory((long)numBytesFreed);
        return numBytesFreed;
    }

    /// <summary>
    /// Marks a page as dirty so it will be flushed on checkpoint.
    /// The page must be pinned (LOCKED) by the caller.
    /// </summary>
    public void MarkDirty(FileHandle fileHandle, uint pageIdx)
    {
        var pageState = fileHandle.GetPageState(pageIdx);
        pageState.SetDirty();
    }

    /// <summary>
    /// Flushes a single dirty page to disk and clears its dirty flag.
    /// </summary>
    public void FlushPage(FileHandle fileHandle, uint pageIdx)
    {
        if (fileHandle.IsInMemoryMode()) return;

        var pageState = fileHandle.GetPageState(pageIdx);
        if (pageState.IsDirty())
        {
            fileHandle.FlushPageIfDirtyWithoutLock(pageIdx);
        }
    }

    public void FreeUsedMemory(long sizeBytes)
    {
        Interlocked.Add(ref _usedMemory, -sizeBytes);
    }

    public void FlushAllDirtyPages()
    {
        foreach (var handle in _fileHandles.Values)
        {
            if (handle.IsInMemoryMode()) continue;

            for (uint pageIdx = 0; pageIdx < handle.NumPages; pageIdx++)
            {
                var pageState = handle.GetPageState(pageIdx);

                if (pageState.IsDirty())
                {
                    try
                    {
                        handle.FlushPageIfDirtyWithoutLock(pageIdx);
                    }
                    catch (ObjectDisposedException)
                    {
                        // The FileHandle's memory-mapped view may already be disposed
                        // (e.g. when the caller disposes fileHandle before BufferManager).
                        // Skip gracefully — data is already gone.
                    }
                }
            }
        }
    }


    public void Dispose()
    {
        FlushAllDirtyPages();
        
        foreach (var handle in _fileHandles.Values)
        {
            handle.Dispose();
        }
        _fileHandles.Clear();
    }
}
