//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (buffer_manager.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading;

namespace BogDb.Core.Storage.BufferManager;

/// <summary>
/// This class keeps state info for pages that can potentially be evicted.
/// Translated from BogDb's EvictionCandidate struct.
/// Uses Interlocked primitives to safely execute concurrent comparisons.
/// We pack the FileIdx and PageIdx into a single ulong for easy atomic swaps.
/// </summary>
public struct EvictionCandidate : IEquatable<EvictionCandidate>
{
    // High 32-bits = FileIdx, Low 32-bits = PageIdx
    private long _packedData;

    public uint FileIdx => (uint)(Interlocked.Read(ref _packedData) >> 32);
    public uint PageIdx => (uint)(Interlocked.Read(ref _packedData) & 0xFFFFFFFF);

    public static readonly EvictionCandidate EMPTY = new EvictionCandidate(uint.MaxValue, uint.MaxValue);

    public EvictionCandidate(uint fileIdx, uint pageIdx)
    {
        _packedData = ((long)fileIdx << 32) | pageIdx;
    }

    private EvictionCandidate(long packedData)
    {
        _packedData = packedData;
    }

    public static bool IsEvictable(ulong currPageStateAndVersion)
    {
        return PageState.GetState(currPageStateAndVersion) == PageState.MARKED;
    }

    public static bool IsSecondChanceEvictable(ulong currPageStateAndVersion)
    {
        return PageState.GetState(currPageStateAndVersion) == PageState.UNLOCKED;
    }

    public bool Equals(EvictionCandidate other)
    {
        return Interlocked.Read(ref _packedData) == Interlocked.Read(ref other._packedData);
    }

    public override bool Equals(object? obj)
    {
        return obj is EvictionCandidate other && Equals(other);
    }

    public override int GetHashCode()
    {
        return Interlocked.Read(ref _packedData).GetHashCode();
    }

    public static bool operator ==(EvictionCandidate left, EvictionCandidate right) => left.Equals(right);
    public static bool operator !=(EvictionCandidate left, EvictionCandidate right) => !left.Equals(right);

    /// <summary>
    /// Returns false if the candidate was not empty, or if another thread set the value first.
    /// Maps to BogDb's `EvictionCandidate::set`.
    /// </summary>
    public bool TrySet(EvictionCandidate newCandidate)
    {
        long emptyPacked = EMPTY._packedData;
        long newPacked = Interlocked.Read(ref newCandidate._packedData);
        
        return Interlocked.CompareExchange(ref _packedData, newPacked, emptyPacked) == emptyPacked;
    }

    /// <summary>
    /// Atomically clears the candidate back to EMPTY. Returns true if successful.
    /// </summary>
    public bool TryUnset()
    {
        long emptyPacked = EMPTY._packedData;
        long currentPacked = Interlocked.Read(ref _packedData);
        if (currentPacked == emptyPacked) return false;
        
        return Interlocked.CompareExchange(ref _packedData, emptyPacked, currentPacked) == currentPacked;
    }

    /// <summary>
    /// Atomically clears the candidate back to EMPTY.
    /// </summary>
    public void Clear()
    {
        Interlocked.Exchange(ref _packedData, EMPTY._packedData);
    }
}
