//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (buffer_manager.cpp)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading;

namespace BogDb.Core.Storage.BufferManager;

/// <summary>
/// A circular buffer queue storing eviction candidates.
/// Supports concurrent lock-free inserts and batch-reads for the BufferManager.
/// </summary>
public class EvictionQueue
{
    public const int BATCH_SIZE = 64;

    private long _insertCursor;
    private long _evictionCursor;
    private long _size;
    
    public readonly long Capacity;
    
    // We utilize an array of EvictionCandidate structs. 
    // They internally handle their own atomic operations via packed ulongs.
    private readonly EvictionCandidate[] _data;

    public long Size => Interlocked.Read(ref _size);
    public long EvictionCursor => Interlocked.Read(ref _evictionCursor);

    public EvictionQueue(long capacity)
    {
        // Capacity needs to be a multiple of the batch size
        Capacity = capacity + (BATCH_SIZE - capacity % BATCH_SIZE);
        _data = new EvictionCandidate[Capacity];
        
        // Initialize as empty
        for (int i = 0; i < Capacity; i++)
        {
            _data[i] = EvictionCandidate.EMPTY;
        }

        _insertCursor = 0;
        _evictionCursor = 0;
        _size = 0;
    }

    /// <summary>
    /// Attempts to lock-free insert a candidate into the circular buffer.
    /// Returns true if successful, false if the queue is full.
    /// </summary>
    public bool Insert(uint fileIndex, uint pageIndex)
    {
        var candidate = new EvictionCandidate(fileIndex, pageIndex);
        
        while (Interlocked.Read(ref _size) < Capacity)
        {
            // Atomically grab an insertion slot. Interlocked.Increment returns the incremented value.
            // So we subtract 1 to get the slot index for this specific insert.
            long cursor = Interlocked.Increment(ref _insertCursor) - 1;
            int idx = (int)(cursor % Capacity);

            // Attempt to write to empty slot
            if (_data[idx].TrySet(candidate))
            {
                Interlocked.Increment(ref _size);
                return true;
            }
        }
        
        return false;
    }

    /// <summary>
    /// Produces the next non-empty batch of candidate slots to be tried for eviction.
    /// Note that it is still possible (though unlikely) for another thread to evict candidates in this span.
    /// The PageState must be locked downstream to prevent data races.
    /// </summary>
    public Span<EvictionCandidate> Next()
    {
        long newCursor = Interlocked.Add(ref _evictionCursor, BATCH_SIZE);
        long startCursor = newCursor - BATCH_SIZE;
        int idx = (int)(startCursor % Capacity);
        
        return new Span<EvictionCandidate>(_data, idx, BATCH_SIZE);
    }

    /// <summary>
    /// Atomically clears the candidate back to EMPTY from the buffer pool.
    /// To prevent struct copy issues from Spans, we require passing the direct index inside the queue.
    /// </summary>
    public void ClearFromIndex(int index)
    {
        if (_data[index].TryUnset())
        {
            Interlocked.Decrement(ref _size);
            return;
        }

        throw new InvalidOperationException($"Unreachable: Attempted to clear an already cleared or modified eviction candidate at index {index}");
    }
}
