//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (page_state.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.Threading;

namespace BogDb.Core.Storage.BufferManager;

/// <summary>
/// Keeps the state information of a page in a file.
/// Encapsulates the State (UNLOCKED, LOCKED, MARKED, EVICTED), Version, and Dirty bit 
/// into a single 64-bit atomic integer to ensure thread-safe lock-free transitions.
/// </summary>
public class PageState
{
    private const ulong DIRTY_MASK = 0x0080000000000000;
    private const ulong STATE_MASK = 0xFF00000000000000;
    private const ulong VERSION_MASK = 0x00FFFFFFFFFFFFFF;
    private const int NUM_BITS_TO_SHIFT_FOR_STATE = 56;

    public const ulong UNLOCKED = 0;
    public const ulong LOCKED = 1;
    public const ulong MARKED = 2;
    public const ulong EVICTED = 3;

    // Highest 1 bit is dirty bit, and the rest are page state and version bits.
    // In the rest bits, the lowest 1 byte is state, and the rest are version.
    private long _stateAndVersion;
    
    public PageState()
    {
        _stateAndVersion = (long)(EVICTED << NUM_BITS_TO_SHIFT_FOR_STATE);
    }

    public ulong GetState() => GetState((ulong)Interlocked.Read(ref _stateAndVersion));
    
    public static ulong GetState(ulong stateAndVersion)
    {
        return (stateAndVersion & STATE_MASK) >> NUM_BITS_TO_SHIFT_FOR_STATE;
    }

    public static ulong GetVersion(ulong stateAndVersion)
    {
        return stateAndVersion & VERSION_MASK;
    }

    private static ulong UpdateStateWithSameVersion(ulong oldStateAndVersion, ulong newState)
    {
        return ((oldStateAndVersion << 8) >> 8) | (newState << NUM_BITS_TO_SHIFT_FOR_STATE);
    }

    private static ulong UpdateStateAndIncrementVersion(ulong oldStateAndVersion, ulong newState)
    {
        return (((oldStateAndVersion << 8) >> 8) + 1) | (newState << NUM_BITS_TO_SHIFT_FOR_STATE);
    }

    public void SpinLock(ulong oldStateAndVersion)
    {
        while (true)
        {
            if (TryLock(oldStateAndVersion))
            {
                return;
            }
            Thread.Yield();
        }
    }

    public bool TryLock(ulong oldStateAndVersion)
    {
        ulong newValue = UpdateStateWithSameVersion(oldStateAndVersion, LOCKED);
        return Interlocked.CompareExchange(ref _stateAndVersion, (long)newValue, (long)oldStateAndVersion) == (long)oldStateAndVersion;
    }

    public void Unlock()
    {
        ulong currentValue = (ulong)Interlocked.Read(ref _stateAndVersion);
        Debug.Assert(GetState(currentValue) == LOCKED);
        ulong newValue = UpdateStateAndIncrementVersion(currentValue, UNLOCKED);
        Interlocked.Exchange(ref _stateAndVersion, (long)newValue);
    }

    public void UnlockUnchanged()
    {
        ulong currentValue = (ulong)Interlocked.Read(ref _stateAndVersion);
        Debug.Assert(GetState(currentValue) == LOCKED);
        ulong newValue = UpdateStateWithSameVersion(currentValue, UNLOCKED);
        Interlocked.Exchange(ref _stateAndVersion, (long)newValue);
    }

    public bool TryClearMark(ulong oldStateAndVersion)
    {
        Debug.Assert(GetState(oldStateAndVersion) == MARKED);
        ulong newValue = UpdateStateWithSameVersion(oldStateAndVersion, UNLOCKED);
        return Interlocked.CompareExchange(ref _stateAndVersion, (long)newValue, (long)oldStateAndVersion) == (long)oldStateAndVersion;
    }

    public bool TryMark(ulong oldStateAndVersion)
    {
        ulong newValue = UpdateStateWithSameVersion(oldStateAndVersion, MARKED);
        return Interlocked.CompareExchange(ref _stateAndVersion, (long)newValue, (long)oldStateAndVersion) == (long)oldStateAndVersion;
    }

    public void SetDirty()
    {
        ulong currentValue = (ulong)Interlocked.Read(ref _stateAndVersion);
        Debug.Assert(GetState(currentValue) == LOCKED);
        
        // Bitwise OR in a thread-safe manner isn't strictly necessary if LOCKED prevents other modifiers,
        // but we use Interlocked for full memory barrier safety.
        long initialValue, computedValue;
        do
        {
            initialValue = Interlocked.Read(ref _stateAndVersion);
            computedValue = initialValue | (long)DIRTY_MASK;
        } 
        while (Interlocked.CompareExchange(ref _stateAndVersion, computedValue, initialValue) != initialValue);
    }

    public void ClearDirty()
    {
        ulong currentValue = (ulong)Interlocked.Read(ref _stateAndVersion);
        Debug.Assert(GetState(currentValue) == LOCKED);

        long initialValue, computedValue;
        do
        {
            initialValue = Interlocked.Read(ref _stateAndVersion);
            computedValue = initialValue & ~(long)DIRTY_MASK;
        } 
        while (Interlocked.CompareExchange(ref _stateAndVersion, computedValue, initialValue) != initialValue);
    }

    public void ClearDirtyWithoutLock()
    {
        // Direct modification without interlocked loop, matching C++ semantics for single-threaded flushing
        long initialValue = Interlocked.Read(ref _stateAndVersion);
        long computedValue = initialValue & ~(long)DIRTY_MASK;
        Interlocked.Exchange(ref _stateAndVersion, computedValue);
    }

    public bool IsDirty()
    {
        return ((ulong)Interlocked.Read(ref _stateAndVersion) & DIRTY_MASK) != 0;
    }

    public ulong GetStateAndVersion()
    {
        return (ulong)Interlocked.Read(ref _stateAndVersion);
    }

    public void ResetToEvicted()
    {
        Interlocked.Exchange(ref _stateAndVersion, (long)(EVICTED << NUM_BITS_TO_SHIFT_FOR_STATE));
    }
}
