//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (copy_node.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using BogDb.Core.Common;
using BogDb.Core.Processor.Operator.Persistent.Reader.CSV;
using BogDb.Core.Processor.Operator.Persistent.Reader.Parquet;

namespace BogDb.Core.Processor.Operator.Persistent;

/// <summary>
/// Terminal Physical Operator for COPY Label FROM 'file.csv'.
///
/// Reads ALL property columns from the CSV using CSVReader.ReadAllRows(),
/// parses each cell into the correct CLR type from the table schema, and
/// stores the complete property row in NodeTableData for downstream MATCH.
///
/// Type support: INT64, INT32, STRING, DOUBLE, FLOAT, BOOL.
/// Unknown types fall back to the raw string value.
/// </summary>
public sealed class CopyNode : PhysicalOperator
{
    private readonly string _tableName;
    private readonly string _filePath;
    private readonly Main.BogDatabase _database;

    private readonly List<string> _propertyNames;
    private readonly List<LogicalTypeID> _propertyTypes;
    private readonly string _primaryKeyPropertyName;
    private bool _executed;

    public CopyNode(
        string tableName,
        string filePath,
        Main.BogDatabase database,
        List<string> propertyNames,
        List<LogicalTypeID> propertyTypes,
        uint id)
        : this(tableName, filePath, database, propertyNames, propertyTypes, "id", id)
    {
    }

    public CopyNode(
        string tableName,
        string filePath,
        Main.BogDatabase database,
        List<string> propertyNames,
        List<LogicalTypeID> propertyTypes,
        string primaryKeyPropertyName,
        uint id)
        : base(PhysicalOperatorType.COPY_NODE, id)
    {
        _tableName = tableName;
        _filePath = filePath;
        _database = database;
        _propertyNames = propertyNames;
        _propertyTypes = propertyTypes;
        _primaryKeyPropertyName = primaryKeyPropertyName;
    }

    public override bool GetNextTuple(ExecutionContext context)
    {
        if (_executed)
            return false;

        ExecuteCopy(context);
        _executed = true;
        return false;
    }

    private void ExecuteCopy(ExecutionContext context)
    {
        if (!_database.NodeTables.TryGetValue(_tableName, out var table))
        {
            table = new Main.NodeTableData();
            _database.NodeTables[_tableName] = table;
        }

        int colCount = _propertyNames.Count;
        var primaryKeyIndex = _propertyNames.FindIndex(name =>
            string.Equals(name, _primaryKeyPropertyName, StringComparison.OrdinalIgnoreCase));
        if (primaryKeyIndex < 0)
            throw new InvalidOperationException($"COPY source for '{_tableName}' is missing primary key column '{_primaryKeyPropertyName}'.");

        IEnumerable<string[]> rows;
        IDisposable? readerDisposable = null;
        try
        {
            if (IsParquetFile(_filePath))
            {
                var parquetReader = ParquetFileReader.Open(ResolveFilePath(_database, _filePath));
                readerDisposable = parquetReader;
                rows = parquetReader.ReadAllRows(colCount);
            }
            else
            {
                var csvReader = CsvFileAccess.OpenReader(_database, _filePath);
                readerDisposable = csvReader;
                rows = csvReader.ReadAllRows(colCount);
            }

            foreach (var cells in rows)
            {
                var idRaw = primaryKeyIndex < cells.Length ? cells[primaryKeyIndex] : null;
                if (string.IsNullOrEmpty(idRaw)) continue;

                object id = ParseCell(idRaw, _propertyTypes[primaryKeyIndex]);

                var props = new Dictionary<string, object>();
                for (int c = 0; c < colCount; c++)
                {
                    var cell = c < cells.Length ? cells[c] : null;
                    var type = c < _propertyTypes.Count ? _propertyTypes[c] : LogicalTypeID.STRING;
                    props[_propertyNames[c]] = cell != null ? ParseCell(cell, type) : string.Empty;
                }

                if (context.Transaction.IsWriteTransaction())
                    table.Upsert(context.Transaction, id, props);
                else
                    table.Upsert(id, props);
            }
        }
        finally
        {
            readerDisposable?.Dispose();
        }
    }

    // ── Type-safe cell parsing ────────────────────────────────────────────────

    public static object ParseCell(string raw, LogicalTypeID type)
    {
        var trimmed = raw.Trim();
        return type switch
        {
            LogicalTypeID.INT64 when long.TryParse(trimmed, out var l64) => l64,
            LogicalTypeID.INT32 when int.TryParse(trimmed, out var i32) => i32,
            LogicalTypeID.DOUBLE when double.TryParse(trimmed,
                System.Globalization.NumberStyles.Float,
                System.Globalization.CultureInfo.InvariantCulture, out var d) => d,
            LogicalTypeID.FLOAT when float.TryParse(trimmed,
                System.Globalization.NumberStyles.Float,
                System.Globalization.CultureInfo.InvariantCulture, out var f) => f,
            LogicalTypeID.BOOL when bool.TryParse(trimmed, out var b) => b,
            LogicalTypeID.STRING => trimmed,
            // Fallback: return string for any unrecognised type or failed parse
            _ => trimmed
        };
    }

    internal static bool IsParquetFile(string filePath)
        => filePath.EndsWith(".parquet", StringComparison.OrdinalIgnoreCase) ||
           filePath.EndsWith(".pq", StringComparison.OrdinalIgnoreCase);

    internal static string ResolveFilePath(Main.BogDatabase database, string filePath)
    {
        // If the path is relative and the database has a DatabasePath, resolve against it
        if (!Path.IsPathRooted(filePath) &&
            !string.Equals(database.DatabasePath, ":memory:", StringComparison.OrdinalIgnoreCase))
        {
            var resolved = Path.Combine(database.DatabasePath, filePath);
            if (File.Exists(resolved))
                return resolved;
        }
        return filePath;
    }
}
