//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (copy_rel.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using BogDb.Core.Common;
using BogDb.Core.Processor.Operator.Persistent.Reader.CSV;
using BogDb.Core.Processor.Operator.Persistent.Reader.Parquet;

namespace BogDb.Core.Processor.Operator.Persistent;

/// <summary>
/// A terminal Physical Operator responsible for batch inserting relationship indices.
/// </summary>
public sealed class CopyRel : PhysicalOperator
{
    private readonly string _tableName;
    private readonly string _filePath;
    private readonly IReadOnlyList<string> _columnOrder;
    private readonly Main.BogDatabase _database;
    private bool _executed;

    public CopyRel(
        string tableName, 
        string filePath, 
        IReadOnlyList<string> columnOrder,
        Main.BogDatabase database,
        uint id) 
        : base(PhysicalOperatorType.COPY_REL, id)
    {
        _tableName = tableName;
        _filePath = filePath;
        _columnOrder = columnOrder;
        _database = database;
    }

    public override bool GetNextTuple(ExecutionContext context)
    {
        if (_executed)
            return false;

        ExecuteCopy(context);
        _executed = true;
        return false; 
    }

    private void ExecuteCopy(ExecutionContext context)
    {
        if (!_database.RelTables.TryGetValue(_tableName, out var table))
        {
            table = new Main.RelTableData();
            _database.RelTables[_tableName] = table;
        }

        if (_database.Catalog.GetTableEntry(_tableName) is not BogDb.Core.Catalog.RelGroupCatalogEntry relEntry)
            throw new InvalidOperationException($"Relationship table '{_tableName}' does not exist.");

        var fromColumnIndex = FindColumnIndex("from_id");
        var toColumnIndex = FindColumnIndex("to_id");
        if (fromColumnIndex < 0 || toColumnIndex < 0)
            throw new InvalidOperationException($"COPY source for '{_tableName}' must contain from_id and to_id columns.");

        var (fromTableName, toTableName) = ResolveEndpointTables(relEntry);
        var fromIdType = ResolvePrimaryKeyType(fromTableName);
        var toIdType = ResolvePrimaryKeyType(toTableName);
        var propertyTypes = ResolvePropertyTypes(relEntry);

        IEnumerable<string[]> rows;
        IDisposable? readerDisposable = null;
        try
        {
            if (CopyNode.IsParquetFile(_filePath))
            {
                var parquetReader = ParquetFileReader.Open(CopyNode.ResolveFilePath(_database, _filePath));
                readerDisposable = parquetReader;
                rows = parquetReader.ReadAllRows(_columnOrder.Count);
            }
            else
            {
                var csvReader = CsvFileAccess.OpenReader(_database, _filePath);
                readerDisposable = csvReader;
                rows = csvReader.ReadAllRows(_columnOrder.Count);
            }

            foreach (var cells in rows)
            {
                var fromRaw = fromColumnIndex < cells.Length ? cells[fromColumnIndex] : null;
                var toRaw = toColumnIndex < cells.Length ? cells[toColumnIndex] : null;
                if (string.IsNullOrWhiteSpace(fromRaw) || string.IsNullOrWhiteSpace(toRaw))
                    continue;

                var fromId = CopyNode.ParseCell(fromRaw!, fromIdType);
                var toId = CopyNode.ParseCell(toRaw!, toIdType);
                EnsureNodeExists(context, fromTableName, fromId);
                EnsureNodeExists(context, toTableName, toId);

                var props = new Dictionary<string, object>();
                for (int i = 0; i < _columnOrder.Count; i++)
                {
                    var columnName = _columnOrder[i];
                    if (string.Equals(columnName, "from_id", System.StringComparison.OrdinalIgnoreCase) ||
                        string.Equals(columnName, "to_id", System.StringComparison.OrdinalIgnoreCase))
                    {
                        continue;
                    }

                    var cell = i < cells.Length ? cells[i] : null;
                    var type = propertyTypes.TryGetValue(columnName, out var resolvedType)
                        ? resolvedType
                        : LogicalTypeID.STRING;
                    props[columnName] = cell != null ? CopyNode.ParseCell(cell, type) : string.Empty;
                }

                var edgeKey = new Main.EdgeKey(fromId, toId);
                if (context.Transaction.IsWriteTransaction())
                    table.Insert(context.Transaction, edgeKey, props);
                else
                    table.Insert(edgeKey, props);
            }
        }
        finally
        {
            readerDisposable?.Dispose();
        }
    }

    private int FindColumnIndex(string columnName)
    {
        for (var i = 0; i < _columnOrder.Count; i++)
        {
            if (string.Equals(_columnOrder[i], columnName, System.StringComparison.OrdinalIgnoreCase))
                return i;
        }

        return -1;
    }

    private static (string FromTableName, string ToTableName) ResolveEndpointTables(
        BogDb.Core.Catalog.RelGroupCatalogEntry relEntry)
    {
        if (relEntry.GetConnections().Count > 0)
        {
            var connection = relEntry.GetConnections()[0];
            return (connection.SrcTableName, connection.DstTableName);
        }

        return (relEntry.SrcTableName, relEntry.DstTableName);
    }

    private LogicalTypeID ResolvePrimaryKeyType(string tableName)
    {
        if (_database.Catalog.GetTableEntry(tableName) is not BogDb.Core.Catalog.NodeTableCatalogEntry nodeEntry)
            return LogicalTypeID.STRING;

        foreach (var property in nodeEntry.GetProperties())
        {
            if (nodeEntry.GetPropertyID(property.ColumnDef.Name) == nodeEntry.PrimaryKeyPropertyID)
                return property.ColumnDef.Type;
        }

        return LogicalTypeID.STRING;
    }

    private static Dictionary<string, LogicalTypeID> ResolvePropertyTypes(
        BogDb.Core.Catalog.RelGroupCatalogEntry relEntry)
    {
        var propertyTypes = new Dictionary<string, LogicalTypeID>(System.StringComparer.OrdinalIgnoreCase);
        foreach (var property in relEntry.GetProperties())
            propertyTypes[property.ColumnDef.Name] = property.ColumnDef.Type;
        return propertyTypes;
    }

    private void EnsureNodeExists(ExecutionContext context, string tableName, object nodeId)
    {
        if (!_database.NodeTables.TryGetValue(tableName, out var nodeTable))
            throw new InvalidOperationException($"Endpoint table '{tableName}' does not exist.");

        var exists = context.Transaction.IsWriteTransaction()
            ? nodeTable.TryGetProperties(context.Transaction, nodeId, out _)
            : nodeTable.TryGetProperties(nodeId, out _);

        if (!exists)
            throw new InvalidOperationException($"COPY relationship row references missing node '{nodeId}' in table '{tableName}'.");
    }
}
