//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (filter_push_down_rule.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Planner;
using BogDb.Core.Planner.Operator;

namespace BogDb.Core.Optimizer;

/// <summary>
/// Implements Algebraic Filter Push-Down.
/// Iterates a LogicalPlan shifting LogicalFilter nodes down to the lowest safe boundary.
/// (e.g. executing WHERE clauses before PROJECTION schemas).
/// </summary>
public sealed class FilterPushDownRule : LogicalRule
{
    public override bool Rewrite(LogicalPlan plan)
    {
        bool changed = false;
        if (plan.LastOperator != null)
        {
            changed = PushDownRecursive(plan.LastOperator, null, plan);
        }
        return changed;
    }

    private bool PushDownRecursive(LogicalOperator current, LogicalOperator parent, LogicalPlan plan)
    {
        bool changed = false;

        // Depth-first traversal
        for (int i = 0; i < current.GetNumChildren(); i++)
        {
            changed |= PushDownRecursive(current.GetChild(i), current, plan);
        }

        // Optimization 1: if current is PROJECTION, and child is FILTER, swap them.
        if (current.OperatorType == LogicalOperatorType.LOGICAL_PROJECTION && current.GetNumChildren() == 1)
        {
            var child = current.GetChild(0);
            if (child.OperatorType == LogicalOperatorType.LOGICAL_FILTER)
            {
                var filter = (LogicalFilter)child;
                
                // Swap the pointers
                var filterChild = filter.GetChild(0);
                
                // PROJECTION points to SCAN
                current.Children[0] = filterChild;
                
                // FILTER points to PROJECTION
                filter.SetChild(current);

                // Update parent to point to FILTER instead of PROJECTION
                if (parent != null)
                {
                    for (int i = 0; i < parent.Children.Count; i++)
                    {
                        if (parent.Children[i] == current)
                        {
                            parent.Children[i] = filter;
                            break;
                        }
                    }
                }
                else if (plan.LastOperator == current)
                {
                    plan.LastOperator = filter;
                }
                
                changed = true;
            }
        }

        // Optimization 2: if current is FILTER and child is SCAN_NODE, push predicate into scan.
        if (current.OperatorType == LogicalOperatorType.LOGICAL_FILTER && current.GetNumChildren() == 1)
        {
            var child = current.GetChild(0);
            if (child.OperatorType == LogicalOperatorType.LOGICAL_SCAN_NODE)
            {
                var filter = (LogicalFilter)current;
                var scan = (LogicalScanNodeProperty)child;

                // Merge pushed predicates: if the scan already has one, AND them together.
                scan.PushedPredicate = scan.PushedPredicate == null
                    ? filter.Predicate
                    : new Binder.BoundBooleanExpression(
                        Common.ExpressionType.AND,
                        scan.PushedPredicate,
                        filter.Predicate);

                // Remove the filter node by replacing it with its child.
                if (parent != null)
                {
                    for (int i = 0; i < parent.Children.Count; i++)
                    {
                        if (parent.Children[i] == current)
                        {
                            parent.Children[i] = child;
                            break;
                        }
                    }
                }
                else if (plan.LastOperator == current)
                {
                    plan.LastOperator = child;
                }

                changed = true;
            }
        }

        return changed;
    }
}
