//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (logical_rule.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogDb.Core.Optimizer;

/// <summary>
/// Abstract AST rewrite rule representing a single transformation logic applied
/// to a LogicalPlan to reduce its execution cost context.
/// </summary>
public abstract class LogicalRule
{
    // The optimizer executes rewrites over rules repeatedly until this flag returns false.
    public abstract bool Rewrite(Planner.LogicalPlan plan);
}
