//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (bogdb_row.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Common;
using System.Collections;

namespace BogDb.Core.Main.QueryResult;


/// <summary>
/// A dynamically typed wrapper abstracting the underlying ValueVector spans
/// across an aggregated ResultCollector buffer into standard .NET tuples for presentation.
/// </summary>
public sealed class BogRow
{
    private readonly object[] _values;
    private readonly string[]? _columnNames;
    private readonly Dictionary<string, int>? _columnIndexLookup;

    public BogRow(object[] values)
    {
        _values = values;
        _columnNames = null;
        _columnIndexLookup = null;
    }

    /// <summary>Internal constructor used by <see cref="QueryResult"/> when column names are known.</summary>
    internal BogRow(object[] values, string[] columnNames)
    {
        _values = values;
        _columnNames = columnNames;
        _columnIndexLookup = new Dictionary<string, int>(columnNames.Length, StringComparer.OrdinalIgnoreCase);
        for (var i = 0; i < columnNames.Length; i++)
        {
            if (!_columnIndexLookup.ContainsKey(columnNames[i]))
                _columnIndexLookup[columnNames[i]] = i;
        }
    }

    public int Count => _values.Length;

    public object GetValue(int index) => _values[index];

    public object GetValue(string columnName) => _values[GetColumnIndex(columnName)];

    public BogValue GetBogValue(int index) => BogValue.FromObject(_values[index]);

    public BogValue GetBogValue(string columnName) => GetBogValue(GetColumnIndex(columnName));

    public T? Get<T>(int index) => GetBogValue(index).As<T>();

    public T? Get<T>(string columnName) => Get<T>(GetColumnIndex(columnName));

    /// <summary>Returns the value at <paramref name="index"/> as <see cref="long"/>, coercing if necessary.</summary>
    public long GetInt64(int index) => TypeCoercionHelper.ToInt64(_values[index]);

    /// <summary>Returns the value at <paramref name="columnName"/> as <see cref="long"/>, coercing if necessary.</summary>
    public long GetInt64(string columnName) => GetInt64(GetColumnIndex(columnName));

    /// <summary>Returns the value at <paramref name="index"/> as <see cref="string"/>, coercing if necessary.</summary>
    public string? GetString(int index) => TypeCoercionHelper.ToBogDbString(_values[index]);

    /// <summary>Returns the value at <paramref name="columnName"/> as <see cref="string"/>, coercing if necessary.</summary>
    public string? GetString(string columnName) => GetString(GetColumnIndex(columnName));

    /// <summary>Returns the value at <paramref name="index"/> as <see cref="bool"/>, coercing if necessary.</summary>
    public bool GetBoolean(int index) => TypeCoercionHelper.ToBool(_values[index]);

    /// <summary>Returns the value at <paramref name="columnName"/> as <see cref="bool"/>, coercing if necessary.</summary>
    public bool GetBoolean(string columnName) => GetBoolean(GetColumnIndex(columnName));

    /// <summary>Returns the value at <paramref name="index"/> as <see cref="double"/>, coercing if necessary.</summary>
    public double GetDouble(int index) => TypeCoercionHelper.ToDouble(_values[index]);

    /// <summary>Returns the value at <paramref name="columnName"/> as <see cref="double"/>, coercing if necessary.</summary>
    public double GetDouble(string columnName) => GetDouble(GetColumnIndex(columnName));

    public bool TryGetValue(string columnName, out object? value)
    {
        if (TryGetColumnIndex(columnName, out var index))
        {
            value = _values[index];
            return true;
        }

        value = null;
        return false;
    }

    public bool TryGetBogValue(string columnName, out BogValue value)
    {
        if (TryGetColumnIndex(columnName, out var index))
        {
            value = GetBogValue(index);
            return true;
        }

        value = default;
        return false;
    }

    public bool TryGet<T>(string columnName, out T? value)
    {
        if (TryGetColumnIndex(columnName, out var index))
        {
            value = Get<T>(index);
            return true;
        }

        value = default;
        return false;
    }

    public bool TryGetColumnIndex(string columnName, out int index)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(columnName);

        if (_columnIndexLookup != null && _columnIndexLookup.TryGetValue(columnName, out index))
            return true;

        index = -1;
        return false;
    }

    public int GetColumnIndex(string columnName)
    {
        if (TryGetColumnIndex(columnName, out var index))
            return index;

        throw new KeyNotFoundException($"Column '{columnName}' was not found in this row.");
    }

    public bool ContainsColumn(string columnName) => TryGetColumnIndex(columnName, out _);


    public override string ToString()
    {
        return string.Join(" | ", _values.Select(v => TypeCoercionHelper.ToBogDbString(v) ?? string.Empty));
    }

    /// <summary>
    /// For Phase 8 Drivers: Parses the flat inner projection representations
    /// into a generic client-readable dictionary bridging back to user land.
    /// Note: Assumes the ResultCollector injected alternating headers and values.
    /// </summary>
    public System.Collections.Generic.Dictionary<string, object> GetAsDictionary()
    {
        var dict = new System.Collections.Generic.Dictionary<string, object>();

        // If this row was constructed with column names, use them directly.
        if (_columnNames != null && _columnNames.Length > 0)
        {
            for (int i = 0; i < _values.Length; i++)
            {
                var key = i < _columnNames.Length ? _columnNames[i] : $"col_{i}";
                dict[key] = NormalizeDictionaryValue(_values[i]) ?? string.Empty;
            }
            return dict;
        }

        // Legacy path: single wrapped dictionary (FromTableFunctionRows).
        if (_values.Length == 1 && _values[0] is System.Collections.Generic.Dictionary<string, object> inner)
            return inner.ToDictionary(kv => kv.Key, kv => NormalizeDictionaryValue(kv.Value) ?? string.Empty);

        // Final fallback: positional col_N keys.
        for (int i = 0; i < _values.Length; i++)
            dict[$"col_{i}"] = NormalizeDictionaryValue(_values[i]) ?? string.Empty;
        return dict;
    }

    private static object? NormalizeDictionaryValue(object? value)
    {
        if (value is null || value is DBNull)
            return null;

        if (value is BogDbInterval interval)
            return TypeCoercionHelper.ToBogDbString(interval);

        if (value is IEnumerable<KeyValuePair<object?, object?>> kvPairs)
        {
            var dict = new System.Collections.Generic.Dictionary<string, object?>();
            foreach (var pair in kvPairs)
                dict[TypeCoercionHelper.ToBogDbString(pair.Key) ?? string.Empty] = NormalizeDictionaryValue(pair.Value);
            return dict;
        }

        if (value is IEnumerable<KeyValuePair<string, object?>> stringPairs)
        {
            var dict = new System.Collections.Generic.Dictionary<string, object?>();
            foreach (var pair in stringPairs)
                dict[pair.Key] = NormalizeDictionaryValue(pair.Value);
            return dict;
        }

        if (value is System.Collections.IDictionary objDict)
        {
            var dict = new System.Collections.Generic.Dictionary<string, object?>();
            foreach (DictionaryEntry entry in objDict)
                dict[TypeCoercionHelper.ToBogDbString(entry.Key) ?? string.Empty] = NormalizeDictionaryValue(entry.Value);
            return dict;
        }

        if (value is IEnumerable seq && value is not string && value is not byte[])
        {
            var list = new System.Collections.Generic.List<object?>();
            foreach (var item in seq)
                list.Add(NormalizeDictionaryValue(item));
            return list;
        }

        return TypeCoercionHelper.Normalize(value);
    }
}
