//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code
//     by BogDB. Validates Phase 5 Optimization Rewrites.
// </auto-generated>
//------------------------------------------------------------------------------

using Xunit;
using BogDb.Core.Optimizer;
using BogDb.Core.Planner;
using BogDb.Core.Planner.Operator;
using BogDb.Core.Binder;
using BogDb.Core.Common;

namespace BogDb.Tests.Optimizer;

public class OptimizerTests
{
    private class MockExpression : Expression
    {
        public MockExpression(ExpressionType type, LogicalTypeID logicalType) : base(type, logicalType) {}
    }

    [Fact]
    public void FilterPushDownRule_PushesFilterBelowProjection()
    {
        // Assemble Top-Heavy unoptimized tree
        // [Root] Filter -> Projection -> ScanNode
        var scan = new LogicalScanNodeProperty(new NodeExpression("n"));
        var projection = new LogicalProjection((List<Expression>)null, scan);
        
        // Mock a boolean expression 
        var predicate = new MockExpression(ExpressionType.EQUALS, LogicalTypeID.BOOL);
        
        var filter = new LogicalFilter(predicate, projection);

        var plan = new LogicalPlan();
        plan.LastOperator = filter;

        var optimizer = new BogDb.Core.Optimizer.Optimizer(null!);

        // Act
        optimizer.Optimize(plan);

        // Assert: Filter -> Projection -> Scan is unchanged since Filter is not
        // directly above Scan (Projection is in between). Filter stays at root.
        Assert.Equal(LogicalOperatorType.LOGICAL_FILTER, plan.LastOperator.OperatorType);

        // Second test: Projection -> Filter -> Scan
        // The FilterPushDown absorbs the Filter into the Scan's PushedPredicate,
        // leaving Projection -> Scan(pushed).
        var newScan = new LogicalScanNodeProperty(new NodeExpression("n"));
        var newFilter = new LogicalFilter(predicate, newScan);
        var newProjection = new LogicalProjection((List<Expression>)null, newFilter);

        var newPlan = new LogicalPlan();
        newPlan.LastOperator = newProjection;

        optimizer.Optimize(newPlan);

        // After optimize: Filter is absorbed into Scan's PushedPredicate.
        // Root is Projection -> Scan(predicate).
        Assert.Equal(LogicalOperatorType.LOGICAL_PROJECTION, newPlan.LastOperator.OperatorType);
        var projChild = newPlan.LastOperator.GetChild(0);
        Assert.Equal(LogicalOperatorType.LOGICAL_SCAN_NODE, projChild.OperatorType);
        var scanWithPredicate = (LogicalScanNodeProperty)projChild;
        Assert.NotNull(scanWithPredicate.PushedPredicate);
    }
}
