//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (extension_manager.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Concurrent;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;

namespace BogDb.Core.Extension;

/// <summary>
/// Native C++ BogDb utilizes `dlopen` tracing. BogDB .NET 10 uses extremely safe 
/// AssemblyLoadContext borders dynamically caching extensions globally bypassing GC heap collisions!
/// </summary>
public sealed class ExtensionManager : IDisposable
{
    private readonly Main.BogDatabase _database;
    
    // We isolate loaded paths dynamically generating separate ALC instances
    // to strictly prevent Global Native namespace collisions!
    private readonly ConcurrentDictionary<string, ExtensionLoadContext> _loadedContexts;
    private readonly ConcurrentDictionary<string, IExtension> _activeExtensions;
    private readonly ConcurrentDictionary<string, string> _aliases;
    private readonly ConcurrentDictionary<string, ExtensionLoadTarget> _loadTargets;

    public ExtensionManager(Main.BogDatabase database)
    {
        _database = database;
        _loadedContexts = new ConcurrentDictionary<string, ExtensionLoadContext>(StringComparer.OrdinalIgnoreCase);
        _activeExtensions = new ConcurrentDictionary<string, IExtension>(StringComparer.OrdinalIgnoreCase);
        _aliases = new ConcurrentDictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        _loadTargets = new ConcurrentDictionary<string, ExtensionLoadTarget>(StringComparer.OrdinalIgnoreCase);
    }

    public bool IsLoaded(string extensionName)
        => TryResolveCanonicalName(extensionName, out _) ||
           _activeExtensions.ContainsKey(extensionName) ||
           _loadedContexts.ContainsKey(extensionName);

    public IReadOnlyCollection<string> LoadedExtensionNames => _activeExtensions.Keys.ToArray();

    /// <summary>
    /// Evaluates extension targets bridging typical ALC caching boundaries resolving standard `.dll` names iteratively natively.
    /// </summary>
    public void LoadExtension(string extensionName)
    {
        // Capitalize extension properly matching local project namespaces. e.g httpfs -> HttpFS
        // Actually, just resolve by the standard generic name BogDb.Extensions.{name}.dll
        var standardName = $"BogDb.Extensions.{extensionName}";
        
        var probingPaths = new[]
        {
            Path.Combine(AppContext.BaseDirectory, $"{standardName}.dll"),
            Path.Combine(Environment.CurrentDirectory, $"{standardName}.dll"),
            Path.Combine(Environment.CurrentDirectory, "bin", "Debug", "net9.0", $"{standardName}.dll")
        };

        var resolvedPath = probingPaths.FirstOrDefault(File.Exists);

        if (resolvedPath == null)
            throw new FileNotFoundException($"Unable to resolve extension native boundaries: {extensionName}. Ensure the plugin exists in the search path.");

        LoadExtension(resolvedPath, extensionName);
    }

    /// <summary>
    /// Loads a dynamically compiled .dll from disk executing inside safe boundaries.
    /// </summary>
    public void LoadExtension(string extensionPath, string extensionName)
    {
        if (!File.Exists(extensionPath))
            throw new FileNotFoundException($"BogDb Extension missing strictly at bounds: {extensionPath}");

        var extensionContext = new ExtensionLoadContext(extensionPath);
        var loadedAssembly = extensionContext.LoadFromAssemblyPath(extensionPath);

        // Native discovery pattern finding implemented Interfaces dynamically
        var extensionType = loadedAssembly.GetTypes()
            .FirstOrDefault(t => typeof(IExtension).IsAssignableFrom(t) && !t.IsInterface && !t.IsAbstract);

        if (extensionType == null)
            throw new InvalidOperationException($"Extension {extensionName} does not implement BogDb.Core.Extension.IExtension natively.");

        var instance = (IExtension)Activator.CreateInstance(extensionType)!;
        var canonicalName = instance.Name;
        if (_activeExtensions.ContainsKey(canonicalName))
        {
            RegisterAlias(extensionName, canonicalName);
            extensionContext.Unload();
            return;
        }

        try
        {
            using (_database.EnterExtensionRegistrationScope(canonicalName))
                instance.Load(_database);
        }
        catch
        {
            _database.RemoveExtensionRegistrations(canonicalName);
            extensionContext.Unload();
            throw;
        }

        _activeExtensions[canonicalName] = instance;
        _loadedContexts[canonicalName] = extensionContext;
        RegisterAlias(extensionName, canonicalName);
        RegisterAlias(canonicalName, canonicalName);
        _loadTargets[canonicalName] = ExtensionLoadTarget.FromPath(extensionPath, extensionName);
    }

    public void ReloadExtension(string extensionName)
    {
        if (!TryResolveCanonicalName(extensionName, out var canonicalName) ||
            !_loadTargets.TryGetValue(canonicalName, out var target))
        {
            LoadExtension(extensionName);
            return;
        }

        UnloadExtension(extensionName);
        if (target.Path != null)
            LoadExtension(target.Path, target.Alias);
        else
            LoadExtension(target.Alias);
    }

    public void UnloadExtension(string extensionName)
    {
        if (!TryResolveCanonicalName(extensionName, out var canonicalName))
            return;

        if (_activeExtensions.TryRemove(canonicalName, out var extension))
        {
            extension.Unload(_database);
            if (extension is IDisposable disposable)
                disposable.Dispose();
        }

        _database.RemoveExtensionRegistrations(canonicalName);

        if (_loadedContexts.TryRemove(canonicalName, out var context))
            context.Unload();

        _loadTargets.TryRemove(canonicalName, out _);
        foreach (var alias in _aliases.Where(kvp =>
                     string.Equals(kvp.Value, canonicalName, StringComparison.OrdinalIgnoreCase)).ToArray())
        {
            _aliases.TryRemove(alias.Key, out _);
        }
    }

    public void Dispose()
    {
        foreach (var context in _loadedContexts.Values)
        {
            context.Unload();
        }
        _loadedContexts.Clear();
        _activeExtensions.Clear();
        _aliases.Clear();
        _loadTargets.Clear();
    }

    private void RegisterAlias(string alias, string canonicalName)
    {
        if (string.IsNullOrWhiteSpace(alias))
            return;
        _aliases[alias] = canonicalName;
    }

    private bool TryResolveCanonicalName(string name, out string canonicalName)
    {
        if (_activeExtensions.ContainsKey(name))
        {
            canonicalName = name;
            return true;
        }

        if (_aliases.TryGetValue(name, out canonicalName!))
            return true;

        canonicalName = string.Empty;
        return false;
    }

    private sealed record ExtensionLoadTarget(string Alias, string? Path)
    {
        public static ExtensionLoadTarget FromPath(string path, string alias) => new(alias, path);
    }
}

/// <summary>
/// The safe sandboxed isolation layer mapping external C# plugin definitions natively.
/// </summary>
internal class ExtensionLoadContext : AssemblyLoadContext
{
    private readonly AssemblyDependencyResolver _resolver;

    public ExtensionLoadContext(string pluginPath) : base(isCollectible: true)
    {
        _resolver = new AssemblyDependencyResolver(pluginPath);
    }

    protected override Assembly Load(AssemblyName assemblyName)
    {
        // Force sharing the identical engine binary for type interfaces
        if (assemblyName.Name == "BogDb.Core")
        {
            return null; // Push fallback natively
        }

        var assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
        if (assemblyPath != null)
        {
            return LoadFromAssemblyPath(assemblyPath);
        }
        return null; // Fallback to core engine limits
    }
}
