//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (extension.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogDb.Core.Extension;

/// <summary>
/// The fundamental Native Plugin interface extending the memory bounds of BogDB.
/// By implementing this within an external C# DLL Library natively, users can map 
/// proprietary file layouts or distributed REST endpoints tightly into Native BogDb Graph nodes!
/// </summary>
public interface IExtension
{
    /// <summary>
    /// The canonical manifest identifier of this extension (e.g., 'httpfs', 'postgres').
    /// </summary>
    string Name { get; }

    /// <summary>
    /// Fired when BogDb natively boots the AssemblyLoadContext mapping the byte limits into Scope.
    /// External DLLs should register their custom Scanner physical rules inside the provided Catalog.
    /// </summary>
    /// <param name="database">The primary database boundaries.</param>
    void Load(Main.BogDatabase database);

    /// <summary>
    /// Optional cleanup hook invoked during unload/reload before database-owned
    /// registrations are removed.
    /// </summary>
    void Unload(Main.BogDatabase database)
    {
    }
}
