//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (cross_product.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace BogDb.Core.Processor.Operator;

/// <summary>
/// A terminal Physical Operator responsible for computing the cartesian product
/// between two execution streams. Commonly used when no join conditions exist.
/// </summary>
public sealed class CrossProduct : PhysicalOperator
{
    private readonly PhysicalOperator _probeChild;
    private readonly PhysicalOperator _buildChild;
    private List<ExecutionState>? _buildStates;
    private BogDb.Core.Storage.MemoryManager.MemoryBlock? _crossBlock;
    private BogDb.Core.Storage.MemoryManager.Spiller? _spiller;
    private long _spilledPartitionId = -1;
    private ExecutionState? _currentProbeState;
    private int _buildIndex;

    public CrossProduct(
        PhysicalOperator probeChild, 
        PhysicalOperator buildChild, 
        uint id) 
        : base(PhysicalOperatorType.CROSS_PRODUCT, id)
    {
        _probeChild = probeChild;
        _buildChild = buildChild;
    }

    public void BuildMaterializedVectors(ExecutionContext context)
    {
        _buildStates = new List<ExecutionState>();
        _spiller = new Storage.MemoryManager.Spiller(context.MemoryManager);

        try
        {
            _crossBlock = context.MemoryManager.AllocateBlock(10 * 1024 * 1024, true); 
        }
        catch (System.OutOfMemoryException)
        {
            _crossBlock = context.MemoryManager.AllocateBlock(2 * 1024 * 1024, true);
            _spilledPartitionId = _spiller.SpillBlock(_crossBlock);
        }

        while (_buildChild.GetNextTuple(context))
        {
            _buildStates.Add(context.CaptureState());
        }
    }

    public override bool GetNextTuple(ExecutionContext context)
    {
        if (_buildStates == null)
        {
            BuildMaterializedVectors(context);
        }

        while (true)
        {
            if (_currentProbeState == null)
            {
                if (!_probeChild.GetNextTuple(context))
                {
                    return false;
                }

                _currentProbeState = context.CaptureState();
                _buildIndex = 0;
            }

            while (_buildStates != null && _buildIndex < _buildStates.Count)
            {
                var buildState = _buildStates[_buildIndex++];
                if (!AreCompatible(_currentProbeState, buildState))
                {
                    continue;
                }

                var merged = ExecutionState.Merge(_currentProbeState, buildState);
                context.RestoreState(merged);
                context.CurrentProjectionRow = null;
                return true;
            }

            _currentProbeState = null;
        }
    }

    private static bool AreCompatible(ExecutionState left, ExecutionState right)
    {
        if (left.CurrentVariableIds == null || right.CurrentVariableIds == null)
        {
            return true;
        }

        foreach (var pair in left.CurrentVariableIds)
        {
            if (right.CurrentVariableIds.TryGetValue(pair.Key, out var rightValue) &&
                !Equals(pair.Value, rightValue))
            {
                return false;
            }
        }

        return true;
    }
}
