//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (physical_operator.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace BogDb.Core.Processor.Operator;

/// <summary>
/// PhysicalOperator iterates the query processing graph dynamically pulling
/// `ValueVector` chunks incrementally.
/// </summary>
public abstract class PhysicalOperator
{
    public PhysicalOperatorType OperatorType { get; }
    public uint ID { get; }
    
    public List<PhysicalOperator> Children { get; }

    protected PhysicalOperator(PhysicalOperatorType operatorType, uint id)
    {
        OperatorType = operatorType;
        ID = id;
        Children = new List<PhysicalOperator>();
    }

    protected PhysicalOperator(PhysicalOperatorType operatorType, PhysicalOperator child, uint id)
        : this(operatorType, id)
    {
        Children.Add(child);
    }

    /// <summary>
    /// Evaluates the subgraph returning true if valid output bytes exist.
    /// Acts as Volcano-iterator pushing up tuple scopes safely.
    /// </summary>
    public abstract bool GetNextTuple(ExecutionContext context);

    public PhysicalOperator GetChild(int index) => Children[index];

    public virtual bool IsSource() => Children.Count == 0;
    public virtual bool IsSink() => false;
}
