//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (types.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogDb.Core.Common;

/// <summary>
/// Mirrors the constexpr definitions and global limits defined in types.h for BogDb.
/// All IDs and limits match their respective C++ integer max limits.
/// </summary>
public static class BogDbConstants
{
    public const ulong INVALID_SEL = ulong.MaxValue;
    public const uint INVALID_PAGE_IDX = uint.MaxValue;
    public const uint INVALID_FILE_IDX = uint.MaxValue;
    public const uint INVALID_COLUMN_ID = uint.MaxValue;
    public const uint ROW_IDX_COLUMN_ID = INVALID_COLUMN_ID - 1;
    public const uint INVALID_IDX = uint.MaxValue;
    public const ulong INVALID_BLOCK_IDX = ulong.MaxValue;
    public const ushort INVALID_STRUCT_FIELD_IDX = ushort.MaxValue;
    public const ulong INVALID_ROW_IDX = ulong.MaxValue;
    public const uint UNDEFINED_CAST_COST = uint.MaxValue;
    public const ulong INVALID_NODE_GROUP_IDX = ulong.MaxValue;
    public const ulong INVALID_PARTITION_IDX = ulong.MaxValue;
    public const ulong INVALID_LENGTH = ulong.MaxValue;
    public const ulong INVALID_OID = ulong.MaxValue;
    public const ulong INVALID_TRANSACTION = ulong.MaxValue;
    public const ulong INVALID_TABLE_ID = INVALID_OID;
    public const ulong INVALID_OFFSET = ulong.MaxValue;
    public const ulong INVALID_LIMIT = ulong.MaxValue;
}
