//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (expression_type.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BogDb.Core.Common;

public static class ExpressionTypeUtil
{
    public static bool IsUnary(ExpressionType type)
    {
        return type == ExpressionType.NOT || type == ExpressionType.IS_NULL || type == ExpressionType.IS_NOT_NULL;
    }

    public static bool IsBinary(ExpressionType type)
    {
        return IsComparison(type) || type == ExpressionType.AND || type == ExpressionType.OR || type == ExpressionType.XOR;
    }

    public static bool IsBoolean(ExpressionType type)
    {
        return type == ExpressionType.AND || type == ExpressionType.OR || type == ExpressionType.XOR || type == ExpressionType.NOT;
    }

    public static bool IsComparison(ExpressionType type)
    {
        return type == ExpressionType.EQUALS || type == ExpressionType.NOT_EQUALS ||
               type == ExpressionType.GREATER_THAN || type == ExpressionType.GREATER_THAN_EQUALS ||
               type == ExpressionType.LESS_THAN || type == ExpressionType.LESS_THAN_EQUALS;
    }

    public static bool IsNullOperator(ExpressionType type)
    {
        return type == ExpressionType.IS_NULL || type == ExpressionType.IS_NOT_NULL;
    }

    public static ExpressionType ReverseComparisonDirection(ExpressionType type)
    {
        switch (type)
        {
            case ExpressionType.GREATER_THAN:
                return ExpressionType.LESS_THAN;
            case ExpressionType.GREATER_THAN_EQUALS:
                return ExpressionType.LESS_THAN_EQUALS;
            case ExpressionType.LESS_THAN:
                return ExpressionType.GREATER_THAN;
            case ExpressionType.LESS_THAN_EQUALS:
                return ExpressionType.GREATER_THAN_EQUALS;
            default:
                throw new ArgumentException($"Cannot reverse direction for non-directional comparison type: {type}");
        }
    }
}
