//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (ku_string.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.InteropServices;

namespace BogDb.Core.Common;

/// <summary>
/// Represents a BogDb string, which can either be stored inline (if <= 12 bytes)
/// or externally via an overflow pointer (if > 12 bytes).
/// Maps exactly to ku_string_t in C++.
/// Total Size: 16 Bytes.
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 16)]
public unsafe struct KuString
{
    public const ulong PREFIX_LENGTH = 4;
    public const ulong INLINED_SUFFIX_LENGTH = 8;
    public const ulong SHORT_STR_LENGTH = PREFIX_LENGTH + INLINED_SUFFIX_LENGTH; // 12 bytes

    // Bytes 0-3: Length of the string (uint32)
    [FieldOffset(0)]
    public uint Length;

    // Bytes 4-7: Prefix (first 4 characters of the string)
    [FieldOffset(4)]
    public fixed byte Prefix[4];

    // Bytes 8-15: The union part (Inline Data OR Overflow Pointer)
    [FieldOffset(8)]
    public fixed byte Data[8];

    [FieldOffset(8)]
    public ulong OverflowPtr;

    public static bool IsShortString(uint len)
    {
        return len <= SHORT_STR_LENGTH;
    }

    public void SetOverflowPtr(ulong ptr)
    {
        OverflowPtr = ptr;
    }

    /// <summary>
    /// Gets a read-only span representing the prefix of the string.
    /// </summary>
    public ReadOnlySpan<byte> GetPrefix()
    {
        fixed (byte* p = Prefix)
        {
            return new ReadOnlySpan<byte>(p, (int)Math.Min(Length, PREFIX_LENGTH));
        }
    }

    /// <summary>
    /// Constructs a C# string from the underlying string data safely.
    /// Note: Accessing Overflow strings requires the pointer to actually point
    /// to valid memory (usually managed by the buffer manager/overflow buffers).
    /// </summary>
    public string GetAsString()
    {
        if (Length == 0) return string.Empty;

        if (IsShortString(Length))
        {
            // The string is entirely contained within this struct (Prefix + Data)
            byte[] buffer = new byte[Length];
            fixed (byte* pPrefix = Prefix)
            fixed (byte* pData = Data)
            {
                uint prefixLen = Math.Min(Length, (uint)4);
                for (int i = 0; i < prefixLen; i++)
                {
                    buffer[i] = pPrefix[i];
                }
                
                if (Length > 4)
                {
                    for (int i = 0; i < Length - 4; i++)
                    {
                        buffer[i + 4] = pData[i];
                    }
                }
            }
            return System.Text.Encoding.UTF8.GetString(buffer);
        }
        else
        {
            // Read from the overflow buffer.
            if (OverflowPtr == 0) return string.Empty;
            
            byte* overflowBuffer = (byte*)OverflowPtr;
            return System.Text.Encoding.UTF8.GetString(overflowBuffer, (int)Length);
        }
    }
}
