//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (types.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.InteropServices;

namespace BogDb.Core.Common;

/// <summary>
/// System representation for a List entry within BogDb columnar data.
/// Maps strictly to list_entry_t in C++.
/// Total Size: 12 Bytes (ulong offset + uint size).
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly struct ListEntry
{
    public readonly ulong Offset;
    public readonly uint Size;

    public ListEntry(ulong offset, uint size)
    {
        Offset = offset;
        Size = size;
    }
}
