//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (types.h / type_utils.cpp)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogDb.Core.Common;

/// <summary>
/// Mirrors the LogicalTypeUtils from BogDb C++.
/// Contains static methods for querying the semantic properties of BogDb's type system.
/// </summary>
public static class LogicalTypeUtils
{
    public static bool IsDate(LogicalTypeID dataType)
    {
        return dataType == LogicalTypeID.DATE;
    }

    public static bool IsTimestamp(LogicalTypeID dataType)
    {
        return dataType == LogicalTypeID.TIMESTAMP ||
               dataType == LogicalTypeID.TIMESTAMP_SEC ||
               dataType == LogicalTypeID.TIMESTAMP_MS ||
               dataType == LogicalTypeID.TIMESTAMP_NS ||
               dataType == LogicalTypeID.TIMESTAMP_TZ;
    }

    public static bool IsUnsigned(LogicalTypeID dataType)
    {
        return dataType == LogicalTypeID.UINT64 ||
               dataType == LogicalTypeID.UINT32 ||
               dataType == LogicalTypeID.UINT16 ||
               dataType == LogicalTypeID.UINT8 ||
               dataType == LogicalTypeID.UINT128;
    }

    public static bool IsIntegral(LogicalTypeID dataType)
    {
        return dataType == LogicalTypeID.INT64 ||
               dataType == LogicalTypeID.INT32 ||
               dataType == LogicalTypeID.INT16 ||
               dataType == LogicalTypeID.INT8 ||
               dataType == LogicalTypeID.INT128 ||
               IsUnsigned(dataType);
    }

    public static bool IsFloatingPoint(LogicalTypeID dataType)
    {
        return dataType == LogicalTypeID.DOUBLE ||
               dataType == LogicalTypeID.FLOAT;
    }

    public static bool IsNumerical(LogicalTypeID dataType)
    {
        return IsIntegral(dataType) || IsFloatingPoint(dataType) || dataType == LogicalTypeID.DECIMAL;
    }

    public static bool IsNested(LogicalTypeID dataType)
    {
        return dataType == LogicalTypeID.LIST ||
               dataType == LogicalTypeID.ARRAY ||
               dataType == LogicalTypeID.STRUCT ||
               dataType == LogicalTypeID.MAP ||
               dataType == LogicalTypeID.UNION;
    }

    public static PhysicalTypeID GetPhysicalType(LogicalTypeID logicalTypeID)
    {
        switch (logicalTypeID)
        {
            case LogicalTypeID.ANY: return PhysicalTypeID.ANY;
            case LogicalTypeID.BOOL: return PhysicalTypeID.BOOL;
            case LogicalTypeID.INT64: return PhysicalTypeID.INT64;
            case LogicalTypeID.INT32: return PhysicalTypeID.INT32;
            case LogicalTypeID.INT16: return PhysicalTypeID.INT16;
            case LogicalTypeID.INT8: return PhysicalTypeID.INT8;
            case LogicalTypeID.UINT64: return PhysicalTypeID.UINT64;
            case LogicalTypeID.UINT32: return PhysicalTypeID.UINT32;
            case LogicalTypeID.UINT16: return PhysicalTypeID.UINT16;
            case LogicalTypeID.UINT8: return PhysicalTypeID.UINT8;
            case LogicalTypeID.INT128: return PhysicalTypeID.INT128;
            case LogicalTypeID.UINT128: return PhysicalTypeID.UINT128;
            case LogicalTypeID.DOUBLE: return PhysicalTypeID.DOUBLE;
            case LogicalTypeID.FLOAT: return PhysicalTypeID.FLOAT;
            case LogicalTypeID.DATE: return PhysicalTypeID.INT32;
            case LogicalTypeID.TIMESTAMP: return PhysicalTypeID.INT64;
            case LogicalTypeID.TIMESTAMP_SEC: return PhysicalTypeID.INT64;
            case LogicalTypeID.TIMESTAMP_MS: return PhysicalTypeID.INT64;
            case LogicalTypeID.TIMESTAMP_NS: return PhysicalTypeID.INT64;
            case LogicalTypeID.TIMESTAMP_TZ: return PhysicalTypeID.INT64;
            case LogicalTypeID.INTERVAL: return PhysicalTypeID.INTERVAL;
            case LogicalTypeID.INTERNAL_ID: return PhysicalTypeID.INTERNAL_ID;
            case LogicalTypeID.STRING: return PhysicalTypeID.STRING;
            case LogicalTypeID.BLOB: return PhysicalTypeID.STRING;
            case LogicalTypeID.LIST: return PhysicalTypeID.LIST;
            case LogicalTypeID.ARRAY: return PhysicalTypeID.ARRAY;
            case LogicalTypeID.STRUCT: return PhysicalTypeID.STRUCT;
            case LogicalTypeID.NODE: return PhysicalTypeID.STRUCT;
            case LogicalTypeID.REL: return PhysicalTypeID.STRUCT;
            case LogicalTypeID.RECURSIVE_REL: return PhysicalTypeID.STRUCT;
            case LogicalTypeID.MAP: return PhysicalTypeID.LIST;
            case LogicalTypeID.UNION: return PhysicalTypeID.STRUCT;
            case LogicalTypeID.POINTER: return PhysicalTypeID.POINTER;
            case LogicalTypeID.SERIAL: return PhysicalTypeID.INT64;
            case LogicalTypeID.UUID: return PhysicalTypeID.INT128;
            case LogicalTypeID.DECIMAL:
                // BogDb maps decimal based on precision, but defaulting to DOUBLE logic for now until ExtraTypeInfo is implemented.
                // Not supported entirely accurately here yet.
                return PhysicalTypeID.DOUBLE;
            default:
                throw new NotSupportedException($"Unknown logical type to physical type mapping: {logicalTypeID}");
        }
    }

    public static uint GetFixedTypeSize(PhysicalTypeID physicalType)
    {
        switch (physicalType)
        {
            case PhysicalTypeID.ANY:
                return 16;
            case PhysicalTypeID.BOOL:
                return 1;
            case PhysicalTypeID.INT64:
            case PhysicalTypeID.UINT64:
            case PhysicalTypeID.DOUBLE:
            case PhysicalTypeID.INTERVAL:
                return 8;
            case PhysicalTypeID.INT32:
            case PhysicalTypeID.UINT32:
            case PhysicalTypeID.FLOAT:
                return 4;
            case PhysicalTypeID.INT16:
            case PhysicalTypeID.UINT16:
                return 2;
            case PhysicalTypeID.INT8:
            case PhysicalTypeID.UINT8:
                return 1;
            case PhysicalTypeID.INT128:
            case PhysicalTypeID.UINT128:
                return 16;
            case PhysicalTypeID.INTERNAL_ID:
                return 16;
            case PhysicalTypeID.STRING:
                return 16; // mapped to ku_string_t size
            case PhysicalTypeID.LIST:
                return 12; // mapped to list_entry_t size
            case PhysicalTypeID.ARRAY:
                return 12; // list_entry_t-compatible in current C# storage path
            case PhysicalTypeID.STRUCT:
            case PhysicalTypeID.POINTER:
                return 8; // pointer/reference-sized slot for nested payload indirection
            default:
                throw new NotSupportedException($"Cannot get fixed size for physical type ID: {physicalType}");
        }
    }
}
