//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (statement_type.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogDb.Core.Common;

/// <summary>
/// Bit-perfect enum categorizing the exact statement types returned by the Cypher Lexer.
/// </summary>
public enum StatementType : byte
{
    QUERY = 0,
    CREATE_TABLE = 1,
    DROP = 2,
    ALTER = 3,
    COPY_TO = 19,
    COPY_FROM = 20,
    STANDALONE_CALL = 21,
    STANDALONE_CALL_FUNCTION = 22,
    EXPLAIN = 23,
    CREATE_MACRO = 24,
    TRANSACTION = 30,
    EXTENSION = 31,
    EXPORT_DATABASE = 32,
    IMPORT_DATABASE = 33,
    ATTACH_DATABASE = 34,
    DETACH_DATABASE = 35,
    USE_DATABASE = 36,
    CREATE_SEQUENCE = 37,
    COMMENT_ON = 38,
    CREATE_TYPE = 39,
    EXTENSION_CLAUSE = 40
}
