//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (value_vector.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.InteropServices;
using System.Collections.Generic;

namespace BogDb.Core.Common;

/// <summary>
/// A Vector represents values of the same data type.
/// The core columnar execution unit in BogDb. 
/// In .NET 10, instead of unique_ptr array handling, we utilize generic byte arrays 
/// and MemoryMarshal to provide ref-access to elements without allocations.
/// </summary>
public sealed class ValueVector : IDisposable
{
    private readonly LogicalTypeID _dataType;
    private readonly uint _numBytesPerValue;
    private readonly NullMask _nullMask;
    
    // We allocate a pinned generic managed byte array to avoid garbage collector 
    // movement if passed to native code or accessed via pointers.
    private readonly byte[] _valueBuffer;
    private Dictionary<uint, object?>? _auxValues;
    public readonly int Capacity;
    
    // Dynamic array allocator for strings (> 12 bytes) and lists.
    public InMemOverflowBuffer? OverflowBuffer { get; set; }

    private readonly DataChunkState _state = new DataChunkState();
    public DataChunkState State => _state;

    public LogicalTypeID DataType => _dataType;
    public NullMask NullMask => _nullMask;

    public ValueVector(LogicalTypeID dataType, int capacity = 2048)
    {
        _dataType = dataType;
        Capacity = capacity;
        _numBytesPerValue = LogicalTypeUtils.GetFixedTypeSize(LogicalTypeUtils.GetPhysicalType(dataType));
        
        _nullMask = new NullMask((ulong)capacity);
        _valueBuffer = GC.AllocateUninitializedArray<byte>((int)(capacity * _numBytesPerValue), pinned: true);
        _auxValues = null;
    }

    /// <summary>
    /// Returns a direct ref to the unmanaged struct inside the byte buffer.
    /// This entirely avoids managed heap allocations per value.
    /// </summary>
    public ref T GetValue<T>(uint pos) where T : unmanaged
    {
        if (pos >= Capacity)
            throw new ArgumentOutOfRangeException(nameof(pos));

        Span<byte> span = _valueBuffer.AsSpan((int)(pos * _numBytesPerValue), (int)_numBytesPerValue);
        return ref MemoryMarshal.Cast<byte, T>(span)[0];
    }

    public void SetValue<T>(uint pos, T value) where T : unmanaged
    {
        if (pos >= Capacity)
            throw new ArgumentOutOfRangeException(nameof(pos));

        Span<byte> span = _valueBuffer.AsSpan((int)(pos * _numBytesPerValue), (int)_numBytesPerValue);
        MemoryMarshal.Cast<byte, T>(span)[0] = value;
    }

    public ReadOnlySpan<byte> GetAsReadOnlySpan()
    {
        return _valueBuffer.AsSpan(0, Capacity * (int)_numBytesPerValue);
    }

    /// <summary>
    /// Safely copies unmanaged memory into the ValueVector's pinned byte array.
    /// Used for fast columnar buffer chunk copies from disk IO.
    /// </summary>
    public unsafe void CopyFrom(byte* srcPtr, uint posInOutputVector, uint numValues)
    {
        if (posInOutputVector + numValues > Capacity)
            throw new ArgumentOutOfRangeException(nameof(numValues));
            
        fixed (byte* dstPtr = _valueBuffer)
        {
            byte* startDst = dstPtr + (posInOutputVector * _numBytesPerValue);
            Buffer.MemoryCopy(srcPtr, startDst, (Capacity - posInOutputVector) * _numBytesPerValue, numValues * _numBytesPerValue);
        }
    }

    public void SetNull(uint pos, bool isNull)
    {
        _nullMask.SetNull(pos, isNull);
        if (isNull)
            _auxValues?.Remove(pos);
    }

    public bool IsNull(uint pos)
    {
        return _nullMask.IsNull(pos);
    }

    public void SetAllNonNull()
    {
        _nullMask.SetAllNonNull();
    }

    public void SetAllNull()
    {
        _nullMask.SetAllNull();
        _auxValues?.Clear();
    }

    /// <summary>
    /// Stores an auxiliary managed payload for nested/complex logical types.
    /// </summary>
    public void SetAuxValue(uint pos, object? value)
    {
        if (pos >= Capacity)
            throw new ArgumentOutOfRangeException(nameof(pos));

        _auxValues ??= new Dictionary<uint, object?>();
        _auxValues[pos] = value;
    }

    public object? GetAuxValue(uint pos)
    {
        if (pos >= Capacity)
            throw new ArgumentOutOfRangeException(nameof(pos));

        if (_auxValues is null || !_auxValues.TryGetValue(pos, out var value))
            throw new KeyNotFoundException($"No auxiliary value exists at position {pos}.");

        return value;
    }

    public void Dispose()
    {
        // For IDisposable pattern semantics if relying on off-heap memory later.
        // ArrayPool might be utilized later.
        OverflowBuffer?.Dispose();
    }
}
