//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (file_handle.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO.MemoryMappedFiles;

namespace BogDb.Core.Storage;

public enum PageReadPolicy
{
    READ_PAGE,
    DONT_READ_PAGE
}

/// <summary>
/// FileHandle holds basic state information of a file and provides utility
/// methods to read/write pages from/to the file via Memory Mapped views.
/// Provides lock-free PageState tracking mirroring BogDb's `file_handle.cpp`.
/// </summary>
public sealed class FileHandle : IDisposable
{
    public const ulong BOGDB_PAGE_SIZE = 4096;
    public const ulong TEMP_PAGE_SIZE = 262144; // 256KB for large temp files

    private readonly byte _flags;
    private MemoryMappedFile _mappedFile;
    private MemoryMappedViewAccessor _accessor;
    private readonly BufferManager.BufferManager _bm;
    private readonly string _filePath;
    private FileStream _fileStream;
    private readonly Transaction.WAL? _wal;
    private uint _mappedCapacityPages;
    
    // Page states matching the file size mapped — grows dynamically via EnsurePageStateCapacity
    private BufferManager.PageState[] _pageStates;

    public readonly uint FileIndex;
    public uint NumPages { get; private set; }
    
    private const byte IS_LARGE_PAGED_MASK = 0b00000001;
    private const byte IS_NEW_IN_MEMORY_TMP_FILE_MASK = 0b00000010;

    public FileHandle(string path, byte flags, BufferManager.BufferManager bm, uint fileIndex, Transaction.WAL? wal = null, uint initialPageCapacity = 1000)
    {
        _flags = flags;
        _bm = bm;
        _filePath = path;
        FileIndex = fileIndex;
        NumPages = 0;
        _wal = wal;

        _pageStates = new BufferManager.PageState[initialPageCapacity];
        for (int i = 0; i < initialPageCapacity; i++)
        {
            _pageStates[i] = new BufferManager.PageState();
        }

        // Memory mapped files are used for zero-allocation PAGE_SIZE reads and writes
        if (!IsInMemoryMode())
        {
            // Open existing file or throw
            _fileStream = new FileStream(path, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.ReadWrite);
            
            // If file is empty, let's just initialize it with minimum length so mmap doesn't fail
            if (_fileStream.Length == 0)
            {
                _fileStream.SetLength(1); 
            }
            
            // NOTE: MemoryMappedFile in Windows requires non-zero sizing.
            _mappedFile = MemoryMappedFile.CreateFromFile(_fileStream, null, 0, MemoryMappedFileAccess.ReadWrite, HandleInheritability.None, false);
            _accessor = _mappedFile.CreateViewAccessor(0, 0, MemoryMappedFileAccess.ReadWrite);
            
            NumPages = (uint)(_fileStream.Length / (long)GetPageSize());
            if (NumPages > initialPageCapacity)
            {
                EnsurePageStateCapacity(NumPages);
            }
            _mappedCapacityPages = NumPages;
        }
        else
        {
            // In-memory tmp backend file 
            _mappedCapacityPages = Math.Max(initialPageCapacity, 1u);
            _mappedFile = MemoryMappedFile.CreateNew(null, (long)(_mappedCapacityPages * GetPageSize()));
            _accessor = _mappedFile.CreateViewAccessor(0, 0, MemoryMappedFileAccess.ReadWrite);
        }
    }

    public bool IsLargePaged() => (_flags & IS_LARGE_PAGED_MASK) != 0;
    public bool IsNewTmpFile() => (_flags & IS_NEW_IN_MEMORY_TMP_FILE_MASK) != 0;
    public bool IsInMemoryMode() => !IsLargePaged() && IsNewTmpFile();

    public ulong GetPageSize() => IsLargePaged() ? TEMP_PAGE_SIZE : BOGDB_PAGE_SIZE;

    public BufferManager.PageState GetPageState(uint pageIdx)
    {
        if (pageIdx >= _pageStates.Length)
        {
            EnsurePageStateCapacity(pageIdx + 1);
        }
            
        return _pageStates[pageIdx];
    }

    /// <summary>
    /// Expands the underlying OS File tracking mapping to accommodate new Pages natively.
    /// </summary>
    public void AddNewPage()
    {
        if (IsInMemoryMode())
        {
            NumPages++;
            if (NumPages > _mappedCapacityPages)
            {
                var newCapacityPages = Math.Max(NumPages, _mappedCapacityPages == 0 ? 1u : _mappedCapacityPages * 2);
                RemapInMemory(newCapacityPages);
            }
            return;
        }

        // We must tear down the Mapped view completely to resize the underlying Stream on Windows
        // due to aggressive unmanaged file locks.
        _accessor?.Dispose();
        _mappedFile?.Dispose();
        _fileStream?.Dispose();

        NumPages++;
        EnsurePageStateCapacity(NumPages);
        long newByteLength = (long)(NumPages * GetPageSize());

        // Reopen the stream cleanly and resize
        _fileStream = new FileStream(_filePath, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.ReadWrite);
        _fileStream.SetLength(newByteLength);
        _mappedCapacityPages = NumPages;

        // Map the new bounds
        _mappedFile = MemoryMappedFile.CreateFromFile(_fileStream, null, 0, MemoryMappedFileAccess.ReadWrite, HandleInheritability.None, false);
        _accessor = _mappedFile.CreateViewAccessor(0, 0, MemoryMappedFileAccess.ReadWrite);
    }

    /// <summary>
    /// Grows the _pageStates array to accommodate at least <paramref name="requiredCapacity"/> entries.
    /// Uses doubling strategy to amortize allocation cost.
    /// </summary>
    private void EnsurePageStateCapacity(uint requiredCapacity)
    {
        if (requiredCapacity <= (uint)_pageStates.Length)
            return;

        var newCapacity = Math.Max(requiredCapacity, (uint)_pageStates.Length * 2);
        var newStates = new BufferManager.PageState[newCapacity];
        Array.Copy(_pageStates, newStates, _pageStates.Length);
        for (uint i = (uint)_pageStates.Length; i < newCapacity; i++)
        {
            newStates[i] = new BufferManager.PageState();
        }
        _pageStates = newStates;
    }


    private unsafe void RemapInMemory(uint newCapacityPages)
    {
        var pageSize = GetPageSize();
        var bytesToCopy = NumPages == 0 ? 0UL : (NumPages - 1) * pageSize;
        byte[]? snapshot = null;
        if (bytesToCopy > 0)
        {
            snapshot = GC.AllocateArray<byte>((int)bytesToCopy);
            byte* src = null;
            try
            {
                _accessor.SafeMemoryMappedViewHandle.AcquirePointer(ref src);
                fixed (byte* dst = snapshot)
                {
                    Buffer.MemoryCopy(src, dst, bytesToCopy, bytesToCopy);
                }
            }
            finally
            {
                if (src != null)
                    _accessor.SafeMemoryMappedViewHandle.ReleasePointer();
            }
        }

        _accessor.Dispose();
        _mappedFile.Dispose();

        _mappedCapacityPages = Math.Max(newCapacityPages, NumPages);
        _mappedFile = MemoryMappedFile.CreateNew(null, (long)(_mappedCapacityPages * pageSize));
        _accessor = _mappedFile.CreateViewAccessor(0, 0, MemoryMappedFileAccess.ReadWrite);

        if (snapshot is not null)
        {
            byte* dst = null;
            try
            {
                _accessor.SafeMemoryMappedViewHandle.AcquirePointer(ref dst);
                fixed (byte* src = snapshot)
                {
                    Buffer.MemoryCopy(src, dst, bytesToCopy, bytesToCopy);
                }
            }
            finally
            {
                if (dst != null)
                    _accessor.SafeMemoryMappedViewHandle.ReleasePointer();
            }
        }
    }

    /// <summary>
    /// Reads a BOGDB_PAGE_SIZE frame directly from the memory mapped file into the provided pointer
    /// </summary>
    public unsafe void ReadPageFromDisk(byte* frame, uint pageIdx)
    {
        while (pageIdx >= NumPages)
        {
            AddNewPage();
        }

        ulong offset = pageIdx * GetPageSize();
        byte* srcPtr = null;
        try
        {
            _accessor.SafeMemoryMappedViewHandle.AcquirePointer(ref srcPtr);
            Buffer.MemoryCopy(srcPtr + offset, frame, GetPageSize(), GetPageSize());
        }
        finally
        {
            if (srcPtr != null)
                _accessor.SafeMemoryMappedViewHandle.ReleasePointer();
        }
    }

    /// <summary>
    /// Safe abstraction to read a page directly into a Span.
    /// </summary>
    public unsafe void ReadPage(uint pageIdx, Span<byte> frame)
    {
        fixed (byte* ptr = frame)
        {
            ReadPageFromDisk(ptr, pageIdx);
        }
    }

    /// <summary>
    /// Safe abstraction to write a page directly from a Span.
    /// </summary>
    public unsafe void WritePage(uint pageIdx, ReadOnlySpan<byte> frame)
    {
        while (pageIdx >= NumPages)
        {
            AddNewPage();
        }

        // NOTE: WAL logging happens at flush time (FlushPageIfDirtyWithoutLock),
        // not here. Logging here would double-log every page write.

        ulong offset = pageIdx * GetPageSize();
        byte* dstPtr = null;
        try
        {
            _accessor.SafeMemoryMappedViewHandle.AcquirePointer(ref dstPtr);
            fixed (byte* srcPtr = frame)
            {
                Buffer.MemoryCopy(srcPtr, dstPtr + offset, GetPageSize(), GetPageSize());
            }
        }
        finally
        {
            if (dstPtr != null)
                _accessor.SafeMemoryMappedViewHandle.ReleasePointer();
        }
    }

    /// <summary>
    /// Flushes dirty pages to disk map.
    /// </summary>
    public unsafe void FlushPageIfDirtyWithoutLock(uint pageIdx)
    {
        var state = _pageStates[pageIdx];
        if (state.IsDirty())
        {
            // The C++ BM manages finding the frame bytes, conceptually writing out the memory mapped changes
            if (!IsInMemoryMode() && _accessor != null)
            {
                byte* frame = _bm.GetFrame(this, pageIdx);
                if (_wal != null)
                {
                    var pageSize = (int)GetPageSize();
                    var data = new byte[pageSize];
                    unsafe
                    {
                        fixed (byte* dst = data)
                        {
                            Buffer.MemoryCopy(frame, dst, pageSize, pageSize);
                        }
                    }
                    _wal.LogPageUpdateWithData(_filePath, pageIdx, data, (uint)pageSize);
                }
                ulong offset = pageIdx * GetPageSize();
                byte* dstPtr = null;
                
                try
                {
                    _accessor.SafeMemoryMappedViewHandle.AcquirePointer(ref dstPtr);
                    Buffer.MemoryCopy(frame, dstPtr + offset, GetPageSize(), GetPageSize());
                }
                finally
                {
                    if (dstPtr != null)
                        _accessor.SafeMemoryMappedViewHandle.ReleasePointer();
                }

                _accessor.Flush();
            }
            state.ClearDirtyWithoutLock();
        }
    }

    public void Dispose()
    {
        _accessor?.Dispose();
        _mappedFile?.Dispose();
        _fileStream?.Dispose();
    }
}
