//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (logical_operator_type.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogDb.Core.Planner.Operator;

public enum LogicalOperatorType : byte
{
    LOGICAL_SCAN_NODE,
    LOGICAL_INDEX_SCAN_NODE,
    LOGICAL_EXTERNAL_INDEX_SCAN_NODE,
    LOGICAL_SCAN_FRONTIER,
    LOGICAL_FILTER,
    LOGICAL_PROJECTION,
    LOGICAL_HASH_JOIN,
    LOGICAL_EXTEND,
    LOGICAL_RECURSIVE_EXTEND,
    TABLE_FUNCTION_CALL,
    LOGICAL_FLATTEN,
    LOGICAL_LIMIT,
    LOGICAL_ORDER_BY,
    LOGICAL_SKIP,
    LOGICAL_AGGREGATE,
    LOGICAL_DISTINCT,
    LOGICAL_UNWIND,
    LOGICAL_UNION_ALL,
    LOGICAL_ACCUMULATE,
    LOGICAL_EXPRESSIONS_SCAN,
    LOGICAL_CREATE_NODE,
    LOGICAL_CREATE_REL,
    LOGICAL_SET_NODE_PROPERTY,
    LOGICAL_SET_REL_PROPERTY,
    LOGICAL_MERGE_NODE,
    LOGICAL_MERGE_REL,
    LOGICAL_MERGE_GRAPH,
    LOGICAL_DELETE_NODE,
    LOGICAL_DELETE_REL,
    LOGICAL_INSERT,
    LOGICAL_COPY_FROM,
    LOGICAL_COPY_TO,
    LOGICAL_ATTACH_DATABASE,
    LOGICAL_EXTENSION,
    LOGICAL_CREATE_MACRO,
    LOGICAL_STANDALONE_CALL,
    LOGICAL_IN_QUERY_CALL,
    LOGICAL_PROFILE,
    LOGICAL_CROSS_PRODUCT,
    LOGICAL_OPTIONAL_JOIN,
    LOGICAL_TOP_K,
    LOGICAL_SINGLE_ROW,
    LOGICAL_SEMI_MASKER,
    LOGICAL_INTERSECT,
    LOGICAL_MARK_JOIN,
    LOGICAL_CALL_SUBQUERY
}
