//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (logical_delete.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using BogDb.Core.Binder;

namespace BogDb.Core.Planner.Operator;

public sealed class LogicalDeleteNode : LogicalOperator
{
    public List<Expression> DeleteNodes { get; }

    public LogicalDeleteNode(
        List<Expression> deleteNodes,
        LogicalOperator child) 
        : base(LogicalOperatorType.LOGICAL_DELETE_NODE, child)
    {
        DeleteNodes = deleteNodes;
    }

    public override string GetExpressionsForPrinting()
    {
        var result = "DeleteNode(";
        foreach (var item in DeleteNodes)
        {
            result += item.ToString() + ", ";
        }
        result += ")";
        return result;
    }
}

public sealed class LogicalDeleteRel : LogicalOperator
{
    public List<Expression> DeleteRels { get; }

    public LogicalDeleteRel(
        List<Expression> deleteRels,
        LogicalOperator child) 
        : base(LogicalOperatorType.LOGICAL_DELETE_REL, child)
    {
        DeleteRels = deleteRels;
    }

    public override string GetExpressionsForPrinting()
    {
        var result = "DeleteRel(";
        foreach (var item in DeleteRels)
        {
            result += item.ToString() + ", ";
        }
        result += ")";
        return result;
    }
}
