//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (logical_insert.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using BogDb.Core.Binder;

namespace BogDb.Core.Planner.Operator;

public sealed class LogicalInsert : LogicalOperator
{
    public List<QueryNode> CreateNodes { get; }
    public List<QueryRel> CreateRels { get; }

    public LogicalInsert(
        List<QueryNode> createNodes,
        List<QueryRel> createRels,
        LogicalOperator child) 
        : base(LogicalOperatorType.LOGICAL_INSERT, child)
    {
        CreateNodes = createNodes;
        CreateRels = createRels;
    }

    public LogicalInsert(
        List<QueryNode> createNodes,
        List<QueryRel> createRels) 
        : base(LogicalOperatorType.LOGICAL_INSERT)
    {
        CreateNodes = createNodes;
        CreateRels = createRels;
    }

    public override string GetExpressionsForPrinting()
    {
        var result = "InsertNode(";
        foreach (var node in CreateNodes)
        {
            result += node.VariableName + ", ";
        }
        result += ") InsertRel(";
        foreach (var rel in CreateRels)
        {
            result += rel.VariableName + ", ";
        }
        result += ")";
        return result;
    }
}
