//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (logical_operator.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace BogDb.Core.Planner.Operator;

/// <summary>
/// The abstract base class representing any logical operation node inside the AST Plan.
/// Evaluated sequentially through BogDB's push-down Optimizers.
/// </summary>
public abstract class LogicalOperator
{
    public LogicalOperatorType OperatorType { get; }
    
    // Each operator tracks its children for recursive resolution
    public List<LogicalOperator> Children { get; }
    
    // Tracks expected tuple throughput traversing this graph sequence (Phase 11 CBO bounds)
    public double EstCardinality { get; set; } = 1.0;

    protected LogicalOperator(LogicalOperatorType operatorType)
    {
        OperatorType = operatorType;
        Children = new List<LogicalOperator>();
    }

    protected LogicalOperator(LogicalOperatorType operatorType, LogicalOperator child)
    {
        OperatorType = operatorType;
        Children = new List<LogicalOperator> { child };
    }

    protected LogicalOperator(LogicalOperatorType operatorType, LogicalOperator left, LogicalOperator right)
    {
        OperatorType = operatorType;
        Children = new List<LogicalOperator> { left, right };
    }

    public LogicalOperator GetChild(int index) => Children[index];
    public int GetNumChildren() => Children.Count;
    public bool HasChild() => Children.Count > 0;

    /// <summary>
    /// Computes schema (output column metadata) for this operator.
    /// Called by <see cref="BogDb.Core.Optimizer.SchemaPopulatorRule"/> bottom-up.
    /// Override in operators that need to propagate schema information.
    /// C++ parity: computeFactorizedSchema()
    /// </summary>
    public virtual void ComputeSchema() { /* no-op in base class */ }

    public abstract string GetExpressionsForPrinting();
}
