//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (logical_accumulate.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using BogDb.Core.Binder;
using BogDb.Core.Common;

namespace BogDb.Core.Planner.Operator;

public sealed class LogicalAccumulate : LogicalOperator
{
    public AccumulateType AccumulateType { get; }
    public IReadOnlyList<Expression> FlatExpressions { get; }
    public Expression? MarkExpression { get; }

    public LogicalAccumulate(
        AccumulateType accumulateType,
        IReadOnlyList<Expression> flatExpressions,
        Expression? markExpression,
        LogicalOperator child)
        : base(LogicalOperatorType.LOGICAL_ACCUMULATE, child)
    {
        AccumulateType = accumulateType;
        FlatExpressions = flatExpressions;
        MarkExpression = markExpression;
    }

    public override string GetExpressionsForPrinting() => string.Empty;
}
