//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (profile planning hooks)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations where applicable.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogDb.Core.Planner.Operator;

public sealed class LogicalProfile : LogicalOperator
{
    public LogicalProfile(LogicalOperator child)
        : base(LogicalOperatorType.LOGICAL_PROFILE, child)
    {
    }

    public override string GetExpressionsForPrinting() => string.Empty;
}
