//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (logical_copy_from.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogDb.Core.Planner.Operator;

using System.Collections.Generic;

/// <summary>
/// Logical operation representing a table import statement.
/// Output by the Planner to be resolved by the PlanMapper into
/// either a CopyNode or CopyRel physical operator based on catalog definitions.
/// </summary>
public sealed class LogicalCopyFrom : LogicalOperator
{
    public string TableName { get; }
    public string FilePath { get; }
    public IReadOnlyList<string> ColumnOrder { get; }

    public LogicalCopyFrom(string tableName, string filePath, IReadOnlyList<string> columnOrder)
        : base(LogicalOperatorType.LOGICAL_COPY_FROM)
    {
        TableName = tableName;
        FilePath = filePath;
        ColumnOrder = columnOrder;
    }

    public override string GetExpressionsForPrinting()
    {
        return $"COPY {TableName} FROM '{FilePath}'";
    }
}
