//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (logical_filter.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Binder;

namespace BogDb.Core.Planner.Operator;

/// <summary>
/// Logical Filter intercepts data frames and removes rows failing the boolean Expression.
/// Target of `FilterPushDown` Optimization rules.
/// </summary>
public sealed class LogicalFilter : LogicalOperator
{
    public Expression Predicate { get; }

    public LogicalFilter(Expression predicate, LogicalOperator child)
        : base(LogicalOperatorType.LOGICAL_FILTER, child)
    {
        Predicate = predicate;
    }

    public void SetChild(LogicalOperator newChild)
    {
        if (Children.Count > 0)
        {
            Children[0] = newChild;
        }
        else
        {
            Children.Add(newChild);
        }
    }

    public override string GetExpressionsForPrinting()
    {
        return $"FILTER {Predicate}";
    }
}
