//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (logical_set.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using BogDb.Core.Binder;

namespace BogDb.Core.Planner.Operator;

public sealed class LogicalSetNodeProperty : LogicalOperator
{
    public List<Expression> SetItems { get; }

    public LogicalSetNodeProperty(
        List<Expression> setItems,
        LogicalOperator child) 
        : base(LogicalOperatorType.LOGICAL_SET_NODE_PROPERTY, child)
    {
        SetItems = setItems;
    }

    public override string GetExpressionsForPrinting()
    {
        var result = "SetNodeProperty(";
        foreach (var item in SetItems)
        {
            result += item.ToString() + ", ";
        }
        result += ")";
        return result;
    }
}

public sealed class LogicalSetRelProperty : LogicalOperator
{
    public List<Expression> SetItems { get; }

    public LogicalSetRelProperty(
        List<Expression> setItems,
        LogicalOperator child) 
        : base(LogicalOperatorType.LOGICAL_SET_REL_PROPERTY, child)
    {
        SetItems = setItems;
    }

    public override string GetExpressionsForPrinting()
    {
        var result = "SetRelProperty(";
        foreach (var item in SetItems)
        {
            result += item.ToString() + ", ";
        }
        result += ")";
        return result;
    }
}
