//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (binder_scope.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BogDb.Core.Catalog;

namespace BogDb.Core.Binder;

/// <summary>
/// BinderScope keeps track of expressions in scope and their aliases resolving variable mapping
/// across chained querying (e.g MATCH (a) WITH a MATCH (a)-[]->()).
/// </summary>
public class BinderScope
{
    // Expressions in scope. Order should be preserved.
    private readonly List<Expression> _expressions;
    
    // case_insensitive_map_t in C++ -> Dictionary with StringComparer.OrdinalIgnoreCase
    private readonly Dictionary<string, int> _nameToExprIdx;
    
    // A node might be popped out of scope. But we may need to retain its table ID information.
    private readonly Dictionary<string, List<TableCatalogEntry>> _memorizedNodeNameToEntries;
    
    // A node pattern may not always be bound as a node expression.
    private readonly Dictionary<string, NodeExpression> _nodeReplacement;

    public BinderScope()
    {
        _expressions = new List<Expression>();
        _nameToExprIdx = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        _memorizedNodeNameToEntries = new Dictionary<string, List<TableCatalogEntry>>(StringComparer.OrdinalIgnoreCase);
        _nodeReplacement = new Dictionary<string, NodeExpression>(StringComparer.OrdinalIgnoreCase);
    }

    public bool IsEmpty() => _expressions.Count == 0;

    public bool Contains(string varName) => _nameToExprIdx.ContainsKey(varName);

    public Expression GetExpression(string varName)
    {
        if (!_nameToExprIdx.TryGetValue(varName, out int idx))
        {
            throw new InvalidOperationException($"Variable {varName} not found in scope.");
        }
        return _expressions[idx];
    }

    public IReadOnlyList<Expression> GetExpressions() => _expressions.AsReadOnly();

    public IEnumerable<(string, Expression)> GetAllExpressions()
    {
        foreach (var kvp in _nameToExprIdx)
        {
            yield return (kvp.Key, _expressions[kvp.Value]);
        }
    }

    /// <summary>Returns all variable names currently in scope.</summary>
    public IEnumerable<string> GetAllNames() => _nameToExprIdx.Keys;

    public void AddExpression(string varName, Expression expression)
    {
        if (_nameToExprIdx.ContainsKey(varName))
        {
            throw new InvalidOperationException($"Variable {varName} already exists in scope.");
        }
        _expressions.Add(expression);
        _nameToExprIdx[varName] = _expressions.Count - 1;
    }

    /// <summary>
    /// Removes a named expression from scope.
    /// Used by the binder to undo temporary scope augmentations (e.g. RETURN aliases during ORDER BY binding).
    /// Note: does NOT remove the backing expression from <c>_expressions</c> to preserve index stability;
    /// only the name→index mapping is removed.
    /// </summary>
    public void RemoveExpression(string varName)
    {
        _nameToExprIdx.Remove(varName);
        // We intentionally leave _expressions intact — indices of other variables must not shift.
    }

    public void ReplaceExpression(string oldName, string newName, Expression expression)
    {
        if (!_nameToExprIdx.TryGetValue(oldName, out int idx))
        {
            throw new InvalidOperationException($"Variable {oldName} not found in scope for replacement.");
        }
        
        _expressions[idx] = expression;
        _nameToExprIdx.Remove(oldName);
        _nameToExprIdx[newName] = idx;
    }

    public void MemorizeTableEntries(string name, List<TableCatalogEntry> entries)
    {
        _memorizedNodeNameToEntries[name] = entries;
    }

    public bool HasMemorizedTableIDs(string name) => _memorizedNodeNameToEntries.ContainsKey(name);

    public List<TableCatalogEntry> GetMemorizedTableEntries(string name)
    {
        return _memorizedNodeNameToEntries[name];
    }

    public void AddNodeReplacement(NodeExpression node)
    {
        _nodeReplacement[node.VariableName] = node;
    }

    public bool HasNodeReplacement(string name) => _nodeReplacement.ContainsKey(name);

    public NodeExpression GetNodeReplacement(string name)
    {
        return _nodeReplacement[name];
    }

    public void Clear()
    {
        _expressions.Clear();
        _nameToExprIdx.Clear();
        // C++ does not clear memorized maps on clear(), preserving context.
        _nodeReplacement.Clear(); 
    }
}
