//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (bound_copy_from.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Common;
using System.Collections.Generic;

namespace BogDb.Core.Binder;

/// <summary>
/// Represents a semantically validated COPY FROM instruction inside the AST.
/// Carries the target Catalog Table ID and the resolved File Path for the data load.
/// </summary>
public sealed class BoundCopyFrom : BoundStatement
{
    public string TableName { get; }
    public string FilePath { get; }
    public IReadOnlyList<string> ColumnOrder { get; }

    public BoundCopyFrom(string tableName, string filePath, IReadOnlyList<string> columnOrder)
        : base(StatementType.COPY_FROM)
    {
        TableName = tableName;
        FilePath = filePath;
        ColumnOrder = columnOrder;
    }
}
