//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (expression.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Common;

namespace BogDb.Core.Binder;

/// <summary>
/// Abstract Bound Node representing a strongly typed expression during Semantic Binding Phase.
/// Unlike ParsedExpression, this expression knows its exact LogicalTypeID constraints.
/// </summary>
public abstract class Expression
{
    public ExpressionType ExpressionType { get; }
    
    // Core property ensuring semantic evaluation bounds at planner phase
    public LogicalTypeID DataType { get; }
    private string _alias = string.Empty;

    protected Expression(ExpressionType expressionType, LogicalTypeID dataType)
    {
        ExpressionType = expressionType;
        DataType = dataType;
    }

    public void SetAlias(string name) => _alias = name;

    public bool HasAlias() => !string.IsNullOrEmpty(_alias);

    public string GetAlias() => _alias;
}
