//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (node_expression.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Common;

namespace BogDb.Core.Binder;

/// <summary>
/// Replaces the Parsed NodePattern inside the semantic binder determining Vertex bounds.
/// </summary>
public class NodeExpression : Expression
{
    public string VariableName { get; }

    public NodeExpression(string variableName) 
        : base(ExpressionType.PATTERN, LogicalTypeID.NODE)
    {
        VariableName = variableName;
    }
}
