//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (copy_from.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Common;

namespace BogDb.Core.Parser;

/// <summary>
/// The AST node representing the syntactic COPY FROM instruction parsed by ANTLR4.
/// </summary>
public sealed class CopyFrom : Statement
{
    public string TableName { get; }
    public string FilePath { get; }

    public CopyFrom(string tableName, string filePath) 
        : base(StatementType.COPY_FROM)
    {
        TableName = tableName;
        FilePath = filePath;
    }
}
