//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (statement.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Common;

namespace BogDb.Core.Parser;

/// <summary>
/// Abstract AST Node representing the root evaluated state of a parsed Cypher Query.
/// Maps internal query evaluation semantics over BogDb properties.
/// </summary>
public abstract class Statement
{
    private double _parsingTime;
    private readonly StatementType _statementType;
    
    // By setting the statement to internal, we still execute the statement, but will not return the
    // execution result as part of the query result returned to users.
    // The use case for this is when a query internally generates other queries to finish first,
    // e.g., `TableFunction::rewriteFunc`.
    private bool _internal;

    protected Statement(StatementType statementType)
    {
        _parsingTime = 0;
        _statementType = statementType;
        _internal = false;
    }

    public StatementType GetStatementType() => _statementType;
    
    public void SetToInternal() => _internal = true;
    
    public bool IsInternal() => _internal;
    
    public void SetParsingTime(double time) => _parsingTime = time;
    
    public double GetParsingTime() => _parsingTime;

    public bool RequireTransaction()
    {
        switch (_statementType)
        {
            case StatementType.TRANSACTION:
                return false;
            default:
                return true;
        }
    }
}
