//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (expression_evaluator.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using BogDb.Core.Common;

namespace BogDb.Core.ExpressionEvaluator;

/// <summary>
/// A runtime executor that evaluates a compiled AST Expression mathematically
/// across a Memory ValueVector chunk. Result is pushed to the pipeline.
/// </summary>
public abstract class ExpressionEvaluator
{
    public ValueVector ResultVector { get; protected set; }
    public List<ExpressionEvaluator> Children { get; }

    protected ExpressionEvaluator(bool hasResultVector = true)
    {
        Children = new List<ExpressionEvaluator>();
        // Native BogDb allocates the result vector dynamically.
        // We defer instantiation until the pipeline initializes natively.
    }

    /// <summary>
    /// Executes the evaluation algorithm over the configured DataPos arrays.
    /// Returns True if the expression mapped successfully (boolean filter pass over 1+ rows).
    /// </summary>
    public abstract bool Evaluate();

    /// <summary>
    /// Evaluates the expression across the unmanaged buffer and updates the output selection mask.
    /// Returns True if at least 1 value matched.
    /// </summary>
    public abstract bool Select(ref SelectionVector selVector);

    public void AddChild(ExpressionEvaluator child)
    {
        Children.Add(child);
    }
}
