//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (literal_evaluator.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Common;

namespace BogDb.Core.ExpressionEvaluator;

/// <summary>
/// Hardcodes static constants into evaluation blocks natively without pointer offsets.
/// </summary>
public sealed class LiteralEvaluator : ExpressionEvaluator
{
    private readonly bool _booleanLiteral; // Stub for mock implementation
    private readonly long _integerLiteral;

    public LiteralEvaluator(bool value) : base(false)
    {
        _booleanLiteral = value;
    }

    public LiteralEvaluator(long value) : base(false)
    {
        _integerLiteral = value;
    }

    public override bool Evaluate()
    {
        // Vector logic evaluates true universally if it models boolean True Literal
        return _booleanLiteral;
    }

    public override bool Select(ref SelectionVector selVector)
    {
        // A literal doesn't filter out rows by itself, it just holds data.
        return true;
    }

    public long GetInteger() => _integerLiteral;
    public bool GetBoolean() => _booleanLiteral;
}
