//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code (reference_evaluator.h)
//     by BogDB. Any changes must maintain byte-for-byte parity with
//     the underlying C++ representations.
// </auto-generated>
//------------------------------------------------------------------------------

using BogDb.Core.Processor;
using BogDb.Core.Common;

namespace BogDb.Core.ExpressionEvaluator;

/// <summary>
/// Translates logical AST variable mapping into tuple byte offset positions dynamically.
/// </summary>
public sealed class ReferenceEvaluator : ExpressionEvaluator
{
    public DataPos TuplePosition { get; }

    public ReferenceEvaluator(DataPos tuplePosition, ValueVector backingVector) 
        : base(true)
    {
        TuplePosition = tuplePosition;
        ResultVector = backingVector;
    }

    public override bool Evaluate()
    {
        // Resolves the pointer mapping to a ValueVector within the chunks
        return true;
    }

    public override bool Select(ref SelectionVector selVector)
    {
        // Base references don't evaluate boolean predicates directly without a wrapping FunctionEvaluator
        return true;
    }
}
